# Compiling barium star table

based on 
### "Barium and related stars, and their white-dwarf companions  I. Giant stars"
Jorissen et al. 2019
 https://ui.adsabs.harvard.edu/abs/2019A&A...626A.127J

 (table 8)


 and 
### "Barium and related stars, and their white-dwarf companions  II. Main-sequence and subgiant stars"
Escorza et al. 2019 
https://ui.adsabs.harvard.edu/abs/2019A&A...626A.128E

In [1]:
import numpy as np
import pandas as pd
import h5py
import json
import subprocess, re, ast
import sys

# Ensure project root is on sys.path so `import paths` finds the top-level paths.py
import os, sys
from pathlib import Path
proj_root = Path('/Users/liekevanson/Documents/Projects/post_mt_review').resolve()
if str(proj_root) not in sys.path:
    sys.path.insert(0, str(proj_root))

## Latex Tables 
(copy pasted directly from ArXiv > Other Formats > Download Source)

first 
### Jorissen et al 2019, "Barium and related stars, and their white-dwarf companions  I. Giant stars"

# table 8 data



``` latex
\renewcommand{\arraystretch}{1.5}
\setlength{\tabcolsep}{2pt}
\begin{table*}
\caption[]{\label{Tab:abundances}Abundances for s-process elements in barium stars, from various sources, as listed in the column Ref. The second column, labeled Ba, lists whether the star is considered as a mild (m) or strong (s) barium star. Assignment shifts (based on the abundances; see text) are indicated by an arrow. For completeness, the other columns list the component masses and orbital elements. Possibly inaccurate masses for the two stars with orbital periods close to 1~yr are listed in italics (see text). }



\begin{tabular}{ll|llrrr|ll|lll|rllllrr}
\hline
HD/DM  &  Ba & \multicolumn{1}{c}{$T_{\rm eff}$} & $\log g$ & $L_{\rm min}$ & \multicolumn{1}{c}{$L$} & $L_{\rm max}$ & $M_{\rm {Ba}}$ &  $M_{\rm WD}$ &   $P$        & $e$   & $f(M)$ &    [Fe/H] &   [Y/Fe]&   [Zr/Fe] & [La/Fe]&   [Ce/Fe]   &  [hs/ls]  & Ref\\
\cline{5-7}
             &          & \multicolumn{1}{c}{(K)} & &
             \multicolumn{3}{c}{(L$_{\odot}$)} & (M$_{\odot}$) & (M$_{\odot}$) & (d) & & (M$_{\odot}$)\\
\hline
$-64^\circ$4333&s    & $4900\pm100$  &  2.6   & 34  & 37  & 40  & {\sl 1.4$+0.1\atop-0.1$} &  {\sl 0.61}&  386    & 0.03  &  0.068 &  -0.10  &         1.13  &    1.12  &    2.52   &    1.41    &  0.84     &       2\\
$-42^\circ$2048&s    & $4400\pm100$ &   1.6     & 170 & 234 & 303 &1.9$+0.7\atop-0.5$ &  0.74 & 3260    & 0.08  &  0.065 &  -0.23  &          0.95  &    0.96  &    1.56   &    1.12   &  0.38     &        2\\
$-14^\circ$2678&m    & $5200\pm100$ &$3.1\pm0.2$& 57  & 73  & 92  & 3.0$+0.2\atop-0.2$ &  0.80 & 3470    & 0.22  &  0.023 &   0.01  &          1.02  &    0.85  &    1.08   &    0.87   &  0.04     &        2   \\
$-01^\circ$3022&m    & $4832\pm25$ &$2.7\pm0.4$& 51 & 56 & 61 & 1.6$+0.1\atop-0.1$ &  0.55  & 3253    & 0.28  &  0.016 &  -0.14  &         0.58 &    0.71  &    0.44   &    0.33     &  -0.26    &        4\\
 5424&s       &$4728\pm80$ &  $2.5\pm0.0$ &33&60        &90&1.3$+0.4\atop-0.3$ &  0.59& 1881    & 0.23  &  0.005 &  -0.43  &         1.30  &    1.05  &    1.82   &    1.67    &  0.57     &       1\\
 16458&s      &$4550\pm25$  & $1.8\pm0.2$ &205  &217    &229 &1.9$+0.1\atop-0.1$ &  0.72 & 2018        & 0.1   &  0.041 &  -0.64  &     1.06  &    1.29  &    1.43   &    1.29    &  0.19     &       1\\
 18182&m      &$4858\pm31$  & $2.5\pm0.4$ &60   &65     &71 &1.8$+0.2\atop-0.1$ &  0.59 & 8059        & 0.31  &  0.0002    &  -0.17  &     0.50  &    0.35  &    0.40   &    0.35    &  -0.05    &       2\\
 20394&s      &$4926\pm17$  & $2.5\pm0.0$ &578  &69     &82 &2.0$+0.2\atop-0.2$ &  0.76 & 2226        & 0.2   &  0.002 &  -0.27  &     1.00  &    1.14  &    1.70   &    1.28    &  0.42     &       2\\
 24035&s      &$4700\pm100$ &$2.5\pm0.2$&13&26  &39 &{\sl 1.3}$+0.3\atop-0.2$ &  {\sl 0.57} & 377.8   & 0.3       &  0.047 &  -0.23  &     1.35  &    1.20  &    2.70   &    1.58    &  0.87     &       2\\
 27271&m      &$5022\pm40$ &  $2.9\pm0.5$ &68   &82     &98 &2.9$+0.2\atop-0.2$ &  0.79 & 1693        & 0.22  &  0.024 &  -0.07  &     0.77  &    0.79  &    0.67   &    0.62    &  -0.13    &       1\\
 31487&s      &$4960\pm50$  & $3.1\pm0.2$ &124  &141    &160 &3.4$+0.2\atop-0.3$    &  1.03& 1066        & 0.05  &  0.038 &  -0.04  &     1.23  &    1.11  &    1.53   &    1.46    &  0.32     &       1\\
 40430&m      &$4930\pm29$  & $2.4\pm0.2$ &74   &84     &95 &2.3$+0.2\atop-0.2$    &  0.68& 5609        & 0.22  &  0.0025&  -0.34  &     0.76  &    0.58  &    0.91   &    0.89    &  0.23     &       2\\
 43389&s      &$4000\pm50$  & $2.0\pm0.5$ &196  &260    &330 &1.8$+0.4\atop-0.3$    &  0.72& 1689        & 0.08  &  0.043 &  -0.35  &     0.91  &    0.32  &    1.53   &    1.22    &  0.76     &       1\\
 44896&s      &$4300\pm100$&  0.7        &526   &676    &841 &3.0$+1.2\atop-1.0$    &  0.96& 629     & 0.02      &  0.048 &  -0.25  &     1.16  &    0.81  &    0.93   &    0.87    &  -0.09    &       11\\
 46407&s      &$4854\pm100$ & $2.2\pm0.4$ &35   &83     &135 &2.1$+0.6\atop-0.7$    &  0.78& 457     & 0.013     &  0.035 &  -0.35  &     1.15  &    1.28  &    1.56   &    1.50    &  0.31     &       1\\
 49641&s      &$4400\pm100$           &  $1.5\pm0.2$           &345     &457         &579 &2.7$+1.2\atop-0.8$    &  0.91& 1785    & 0.07  &  0.003 &  -0.3   &         0.89  &    0.53  &    1.86   &    1.04    &  0.74     &       2\\
 49841&m      &5200           &   3.2          &49      &61     &74 &2.8$+0.2\atop-0.2$    &  0.78& 897         & 0.16      &  0.032 &   0.2   & 0.85  &    0.65  &    0.81   &    0.56    &  -0.06    &       9\\
 50082&s      &$4789\pm100$ & $2.4\pm0.5$ &60   &63     &66 2&1.6$+0.3\atop-0.2$    &  0.67& 2896        & 0.19  &  0.027 &  -0.32  &     0.86  &    1.04  &    1.42   &    1.35    &  0.44     &       1\\
 51959&m      &$4814\pm34$  & $3.2\pm0.2$ &11   &13     &16 &1.2$+0.1\atop-0.1$    &  0.47& 9718        & 0.53  &  0.0005&  -0.21  &     0.98  &    1.25  &    0.94   &    1.02    &  -0.13    &       4\\
 53199&m      &$5119\pm28$  & $2.9\pm0.2$ &47   &55     &64 1&2.5$+0.1\atop-0.1$    &  0.71& 8314        & 0.24  &  0.028 &  -0.20  &     0.68  &    0.70  &    1.06   &    0.93    &  0.31     &       2\\
 58121&m      &$4600\pm100$& $1.8\pm0.2$&121    &142    &163    &2.6$+0.5\atop-0.4$    &  0.73 & 1214    & 0.14  &  0.015 &  -0.01  &     0.41  &    0.26  &    0.50   &    0.36    &  0.10     &       2\\
 58368&m      &$5000\pm100$& $2.6\pm0.2$ &37    &43     &49     &2.6$+0.1\atop-0.2$    & 0.73     & 672     & 0.22      &  0.021 &   0.04  &     0.85  &    0.60  &    1.13   &    0.86    &  0.27     &       2\\
 59852&m      &$5000\pm100$& $2.2\pm0.2$ &81    &90     &100 &2.5$+0.2\atop-0.3$    &  0.71& 3464        & 0.15  &  0.0022&  -0.22  &     0.40  &    0.27  &    0.39   &    0.41    &  0.06     &       2\\
 77247&m      &$5050\pm100$ & $2.5\pm0.5$ &306  &346    &388    &3.9$+0.1\atop-0.2$    &  0.94  & 80      & 0.09      &  0.005 &  -0.13  &     0.73  &    0.75  &    0.76   &    0.68    &  -0.02    &       4\\
 84678&s      &$4600\pm100$& $1.7\pm0.2$ &154   &189    &227 &2.3$+0.6\atop-0.5$    &  0.83  & 1630        & 0.06  &  0.062 &  -0.13  &     1.09  &    1.21  &    2.04   &    1.52    &  0.63     &       2\\
 88562&s      &$4000\pm50$  & $2.0\pm0.5$ &240  &277    &321 &1.0$+0.1\atop-0.1$    &  0.51  & 1445        & 0.2   &  0.048 &  -0.53  &     0.93  &    0.43  &    1.15   &    1.02    &  0.41     &       1\\
 91208&m      &$5093\pm67$  & $2.9\pm0.3$ &35 9 &39     &43     &2.3$+0.1\atop-0.2$    &  0.68  & 1754        & 0.17  &  0.022 &  -0.16  &     0.94  &    0.61  &    0.81   &    0.84    &  0.05     &       2\\
 92626&s      &$4800\pm100$&   2.3          &171        &214    &259 &3.1$+0.4\atop-0.6$    &  0.98  & 918     & 0.        &  0.042 &  -0.15  &     0.99  &    1.21  &    2.51   &    1.74    &  1.02     &       2\\
 95193&m      &$5008\pm22$  & $2.8\pm0.1$ &59   &69     &79 &2.7$+0.1\atop-0.1$    &  0.76  & 1653        & 0.13  &  0.026 &  -0.04  &     0.75  &    0.26  &    0.50   &    0.36    &  -0.07    &       2\\
 98839&m      &$4917\pm34$  & $2.3\pm0.6$ &276  &332    &395 &4.3$+0.2\atop-0.2$    &  1.00  & 16471   & 0.56      &  0.056 &  -0.05  &     0.10  &    0.17  &    0.35   &    0.30    &  0.19     &       4\\
 101013&s     &$4722\pm32$  & $2.3\pm0.2$ &77   &108    &141    &1.7$+0.3\atop-0.3$    &  0.68 & 1711        & 0.2   &  0.037 &  -0.40  &     1.17  &    0.97  &    1.23   &    1.11    &  0.10     &       4\\
 104979&m     &$5100\pm100$& $2.7\pm0.2$&80     &95     &111 &2.7$+0.1\atop-0.2$    &  0.75 & 19295   & 0.08      &  -     &  -0.26  &     0.71  &    0.85  &    1.11   &    1.06    &  0.31     &      6 \\
 107541&s     &$5000\pm100$&  $3.2\pm0.2$ &8.9  &11     &14 &1.1$+0.2\atop-0.1$    &  0.54 & 3570        & 0.1   &  0.029 &  -0.63  &     1.53  &    1.35  &    2.52   &    1.87    &  0.75     &      2\\
 119185&m     &$4919\pm18$ &  $2.5\pm0.0$ &65   &77     &90. &1.7$+0.2\atop-0.2$    &  0.57& 22065   & 0.6       &  -     &  -0.42  &     0.30  &    0.21  &    0.54   &    0.60    &  0.32     &       2\\
 121447&s     &$4000\pm50$ &  $1.0\pm0.5$ &                  - &     -             &        -        &1.6$+0.1\atop-0.1$                      &  0.6    & 185.7   & 0.015 &  0.025 &  -0.90  &     1.35  &    1.57  &    2.39   &    2.22    &  0.84     &       1\\
 \hline
 \end{tabular}
 \end{table*}
 
 \addtocounter{table}{-1}
 
\begin{table*}
\caption[]{Continued. }

\begin{tabular}{ll|llrrr|ll|lll|rllllrr}
\hline
HD/DM  &  Ba & \multicolumn{1}{c}{$T_{\rm eff}$} & $\log g$ & $L_{\rm min}$ & $L$ & $L_{\rm max}$ & $M_{\rm {Ba}}$ &  $M_{\rm WD}$ &   $P$        & $e$   & $f(M)$ &    [Fe/H] &   [Y/Fe]&   [Zr/Fe] & [La/Fe]&   [Ce/Fe]   &  [hs/ls]  & Ref\\
\cline{5-7}
             &          & \multicolumn{1}{c}{(K)} & &
             \multicolumn{3}{c}{(L$_{\odot}$)} & (M$_{\odot}$) & (M$_{\odot}$) & (d) & & (M$_{\odot}$)\\
\hline
 123949&s    &$4378\pm80$ & $1.8\pm0.5$ &59     &92     &128  &1.3$+0.3\atop-0.1$    &  0.58& 8523        & 0.92  &  0.046 &  -0.23  &     0.91  &    0.88  &    1.21   &    1.28    &  0.35     &       1\\
 134698&m    &$4438\pm30$ & $1.7\pm0.3$ &163    &192&225  &1.5$+0.2\atop-0.2$    &  0.53& 10005   & 0.95      &  0.054 &  -0.57  &     0.56  &    0.59  &    0.65   &    0.53    &  0.02     &        2\\
 139195&m    &$5029\pm29$ & $3.1\pm0.2$  &38    &44     &514  &2.6$+0.1\atop-0.1$    &  0.74& 5324        & 0.35  &  0.026 &  -0.07  &     0.72  &    0.79  &    0.62   &    0.54    &  -0.17    &       4\\
 143899&m    &$5144\pm26$ &  $2.9\pm0.3$ &43    &50     &67  &2.4$+0.1\atop-0.1$    &  0.71& 1461        & 0.19  &  0.017 &  -0.29  &     0.86  &    0.57  &    0.90   &    0.90    &  0.19     &        2\\
 154430&s    &$4200\pm100$ &  $1.2\pm0.2$&382   &685    &1046     &2.3$+1.4\atop-0.7$    &  0.81& 1668        & 0.11  &  0.034 &  -0.36  &     0.93  &    0.97  &    2.00   &    1.33    &  0.71     &       2\\
 178717&s    &$3800\pm50$  & $1.0\pm0.5$&156    &1617   &3189         &1.6$+0.9\atop-0.7$    &  0.66& 2866        & 0.43  &  0.006 &  -0.52  &     0.79  &    0.44  &    0.85   &    0.74    &  0.18     &       1\\
 180622&m    &$4600\pm100$ & $2.2\pm0.2$ &59    &63     &68       &1.8$+0.3\atop-0.2$    &  0.59& 4049        & 0.06  &  0.07  &   0.03  &     0.61  &    0.41  &    0.48   &    0.27    &  -0.13    &       2\\
 183915&m$\rightarrow$s&$4494\pm130$&$1.6\pm0.4$&153    &266    &386&1.8$+1.0\atop-0.6$    &  0.60 & 4382        & 0.27  &  7E-05 &  -0.59  &     0.88  &    0.68  &    2.16   &    1.22    &  0.91     &        2\\
 196673&m    &$4914\pm9$   & $2.5\pm0.3$ &618   &900    &1206 &5.0$+0.0\atop-0.1$    &  1.10 & 7780    & 0.59      &  0.020 &  0.12  &     0.00  &    0.25  &    0.39   &    0.31    &  0.23     &        4\\
 199939&s    &$4710\pm9$   & $2.4\pm0.4$ &159   &214    &271 &2.8$+0.4\atop-0.4$    &  0.93 & 584.9   & 0.28      &  0.025 &  -0.22  &     1.38  &    1.19  &    1.72   &    1.67    &  0.41     &       1\\
 200063&m    &$4100\pm100$ & $1.1\pm0.2$   &206 &753    &1349      &2.0$+1.3\atop-0.9$    &  0.64 & 1735        & 0.07  &  0.058 &  -0.34  &     0.88  &    0.62  &    1.33   &    0.93    &  0.38     &       2    \\
 201657&s    &$4700\pm100$ & $2.2\pm0.2$ &63    &80     &100 &1.8$+0.5\atop-0.4$    &   0.70    & 1710        & 0.17  &  0.004 &  -0.34  &     0.72  &    0.98  &    1.91   &    1.44    &  0.82     &       2\\
 201824&s    &$4937\pm52$  & $2.6\pm0.2$ &51    &69     &90 &1.7$+0.4\atop-0.2$    &  0.68 & 2837        & 0.34  &  0.04  &  -0.40   &     0.91  &    0.87  &    1.58   &    1.48    &  0.64     &        2\\
 202109&m    &4700  &  2.4            &120      &147        &176 &3.4$+0.2\atop-0.4$    &  0.87     & 6489        & 0.22  &  0.023 &  -0.03  &     0.42  &    0.39  &    0.40   &    0.21    &  -0.10    &       9\\
 204075&m    &$5269\pm53$  & $1.7\pm0.3$ &418   &561    &741 &4.5$+0.3\atop-0.2$    &  1.03     & 2378        & 0.28  &  0.004 &  -0.09  &     1.37  &    1.37  &    1.04   &    0.85    &  -0.43    &        5\\
 205011&m    &$4803\pm21$  & $2.5\pm0.1$ &59    &73     &88 &1.8$+0.3\atop-0.3$    &  0.60 & 2837        & 0.24  &  0.034 &  -0.26  &     0.82  &    0.86  &    0.88   &    0.76    &  -0.02    &        4\\
 210946&m    &$4780\pm76$  & $2.4\pm0.2$ &50    &74     &99 &1.8$+0.5\atop-0.4$    &  0.59 & 1529        & 0.13  &  0.041 &  -0.29  &     0.77  &    0.56  &    0.81   &    0.66    &  0.07     &        2\\
 211594&s    &$4947\pm57$  & $2.6\pm0.1$ &49    &63     &77 &2.0$+0.3\atop-0.2$    &  0.76 & 1019        & 0.06  &  0.014 &  -0.29  &     1.20  &    1.18  &    2.31   &    1.57    &  0.75     &        2\\
 218356&m    &$4500\pm100$ &  1.8     &543      &733    &976 &4.3$+0.2\atop-1.1$    &  1.00 & 111         &   0&  4E-05 &  -0.06 &     0.45  &    0.26  &    0.90   &    0.51    &  0.35     &        7\\
 223617&m    &$4560\pm20$  & $2.2\pm0.1$ &61    &65         &70 &1.4$+0.1\atop-0.1$    &    0.51   & 1294        & 0.06  &  0.0064&  -0.20  &     0.70  &    0.73  &    1.03   &    0.67    &  0.14     &        4\\
 NGC \\
 2420-173&s$\rightarrow$m&$5150\pm100$&2.2&95   &128    &173&3.0$+0.3\atop-0.4$& 0.80& 1479 & 0.43 & 0.008 & -0.26 & 1.00 & 0.72 & 0.62 & 0.59 & -0.26 & 10 \\
\hline\\

\end{tabular}

References: (1) Karinkuzhi et al. (2018); (2) \citet{2016MNRAS.459.4299D}; (3) \citet{2006A&A...454..895A}; (4) This work; (5) \citet{2016A&A...586A.151M}; (6) \citet{2015MNRAS.446.2348K};
(7) \citet{2014AJ....147..137L}
(8) \citet{1984A&A...132..326S}; (9) \citet{2011A&A...533A..51P}; (10) \citet{2017A&A...597A..68V}; (11) \citet{1984A&A...132..326S}

\end{table*}
\renewcommand{\arraystretch}{1}
\setlength{\tabcolsep}{3pt}

```

In [2]:
# ========= RAW LaTeX table =========
latex_text = r"""
\renewcommand{\arraystretch}{1.5}
\setlength{\tabcolsep}{2pt}
\begin{table*}
\caption[]{\label{Tab:abundances}Abundances for s-process elements in barium stars, from various sources, as listed in the column Ref. The second column, labeled Ba, lists whether the star is considered as a mild (m) or strong (s) barium star. Assignment shifts (based on the abundances; see text) are indicated by an arrow. For completeness, the other columns list the component masses and orbital elements. Possibly inaccurate masses for the two stars with orbital periods close to 1~yr are listed in italics (see text). }



\begin{tabular}{ll|llrrr|ll|lll|rllllrr}
\hline
HD/DM  &  Ba & \multicolumn{1}{c}{$T_{\rm eff}$} & $\log g$ & $L_{\rm min}$ & \multicolumn{1}{c}{$L$} & $L_{\rm max}$ & $M_{\rm {Ba}}$ &  $M_{\rm WD}$ &   $P$        & $e$   & $f(M)$ &    [Fe/H] &   [Y/Fe]&   [Zr/Fe] & [La/Fe]&   [Ce/Fe]   &  [hs/ls]  & Ref\\
\cline{5-7}
             &          & \multicolumn{1}{c}{(K)} & &
             \multicolumn{3}{c}{(L$_{\odot}$)} & (M$_{\odot}$) & (M$_{\odot}$) & (d) & & (M$_{\odot}$)\\
\hline
$-64^\circ$4333&s    & $4900\pm100$  &  2.6   & 34  & 37  & 40  & {\sl 1.4$+0.1\atop-0.1$} &  {\sl 0.61}&  386    & 0.03  &  0.068 &  -0.10  &         1.13  &    1.12  &    2.52   &    1.41    &  0.84     &       2\\
$-42^\circ$2048&s    & $4400\pm100$ &   1.6     & 170 & 234 & 303 &1.9$+0.7\atop-0.5$ &  0.74 & 3260    & 0.08  &  0.065 &  -0.23  &          0.95  &    0.96  &    1.56   &    1.12   &  0.38     &        2\\
$-14^\circ$2678&m    & $5200\pm100$ &$3.1\pm0.2$& 57  & 73  & 92  & 3.0$+0.2\atop-0.2$ &  0.80 & 3470    & 0.22  &  0.023 &   0.01  &          1.02  &    0.85  &    1.08   &    0.87   &  0.04     &        2   \\
$-01^\circ$3022&m    & $4832\pm25$ &$2.7\pm0.4$& 51 & 56 & 61 & 1.6$+0.1\atop-0.1$ &  0.55  & 3253    & 0.28  &  0.016 &  -0.14  &         0.58 &    0.71  &    0.44   &    0.33     &  -0.26    &        4\\
 5424&s       &$4728\pm80$ &  $2.5\pm0.0$ &33&60        &90&1.3$+0.4\atop-0.3$ &  0.59& 1881    & 0.23  &  0.005 &  -0.43  &         1.30  &    1.05  &    1.82   &    1.67    &  0.57     &       1\\
 16458&s      &$4550\pm25$  & $1.8\pm0.2$ &205  &217    &229 &1.9$+0.1\atop-0.1$ &  0.72 & 2018        & 0.1   &  0.041 &  -0.64  &     1.06  &    1.29  &    1.43   &    1.29    &  0.19     &       1\\
 18182&m      &$4858\pm31$  & $2.5\pm0.4$ &60   &65     &71 &1.8$+0.2\atop-0.1$ &  0.59 & 8059        & 0.31  &  0.0002    &  -0.17  &     0.50  &    0.35  &    0.40   &    0.35    &  -0.05    &       2\\
 20394&s      &$4926\pm17$  & $2.5\pm0.0$ &578  &69     &82 &2.0$+0.2\atop-0.2$ &  0.76 & 2226        & 0.2   &  0.002 &  -0.27  &     1.00  &    1.14  &    1.70   &    1.28    &  0.42     &       2\\
 24035&s      &$4700\pm100$ &$2.5\pm0.2$&13&26  &39 &{\sl 1.3}$+0.3\atop-0.2$ &  {\sl 0.57} & 377.8   & 0.3       &  0.047 &  -0.23  &     1.35  &    1.20  &    2.70   &    1.58    &  0.87     &       2\\
 27271&m      &$5022\pm40$ &  $2.9\pm0.5$ &68   &82     &98 &2.9$+0.2\atop-0.2$ &  0.79 & 1693        & 0.22  &  0.024 &  -0.07  &     0.77  &    0.79  &    0.67   &    0.62    &  -0.13    &       1\\
 31487&s      &$4960\pm50$  & $3.1\pm0.2$ &124  &141    &160 &3.4$+0.2\atop-0.3$    &  1.03& 1066        & 0.05  &  0.038 &  -0.04  &     1.23  &    1.11  &    1.53   &    1.46    &  0.32     &       1\\
 40430&m      &$4930\pm29$  & $2.4\pm0.2$ &74   &84     &95 &2.3$+0.2\atop-0.2$    &  0.68& 5609        & 0.22  &  0.0025&  -0.34  &     0.76  &    0.58  &    0.91   &    0.89    &  0.23     &       2\\
 43389&s      &$4000\pm50$  & $2.0\pm0.5$ &196  &260    &330 &1.8$+0.4\atop-0.3$    &  0.72& 1689        & 0.08  &  0.043 &  -0.35  &     0.91  &    0.32  &    1.53   &    1.22    &  0.76     &       1\\
 44896&s      &$4300\pm100$&  0.7        &526   &676    &841 &3.0$+1.2\atop-1.0$    &  0.96& 629     & 0.02      &  0.048 &  -0.25  &     1.16  &    0.81  &    0.93   &    0.87    &  -0.09    &       11\\
 46407&s      &$4854\pm100$ & $2.2\pm0.4$ &35   &83     &135 &2.1$+0.6\atop-0.7$    &  0.78& 457     & 0.013     &  0.035 &  -0.35  &     1.15  &    1.28  &    1.56   &    1.50    &  0.31     &       1\\
 49641&s      &$4400\pm100$           &  $1.5\pm0.2$           &345     &457         &579 &2.7$+1.2\atop-0.8$    &  0.91& 1785    & 0.07  &  0.003 &  -0.3   &         0.89  &    0.53  &    1.86   &    1.04    &  0.74     &       2\\
 49841&m      &5200           &   3.2          &49      &61     &74 &2.8$+0.2\atop-0.2$    &  0.78& 897         & 0.16      &  0.032 &   0.2   & 0.85  &    0.65  &    0.81   &    0.56    &  -0.06    &       9\\
 50082&s      &$4789\pm100$ & $2.4\pm0.5$ &60   &63     &66 2&1.6$+0.3\atop-0.2$    &  0.67& 2896        & 0.19  &  0.027 &  -0.32  &     0.86  &    1.04  &    1.42   &    1.35    &  0.44     &       1\\
 51959&m      &$4814\pm34$  & $3.2\pm0.2$ &11   &13     &16 &1.2$+0.1\atop-0.1$    &  0.47& 9718        & 0.53  &  0.0005&  -0.21  &     0.98  &    1.25  &    0.94   &    1.02    &  -0.13    &       4\\
 53199&m      &$5119\pm28$  & $2.9\pm0.2$ &47   &55     &64 1&2.5$+0.1\atop-0.1$    &  0.71& 8314        & 0.24  &  0.028 &  -0.20  &     0.68  &    0.70  &    1.06   &    0.93    &  0.31     &       2\\
 58121&m      &$4600\pm100$& $1.8\pm0.2$&121    &142    &163    &2.6$+0.5\atop-0.4$    &  0.73 & 1214    & 0.14  &  0.015 &  -0.01  &     0.41  &    0.26  &    0.50   &    0.36    &  0.10     &       2\\
 58368&m      &$5000\pm100$& $2.6\pm0.2$ &37    &43     &49     &2.6$+0.1\atop-0.2$    & 0.73     & 672     & 0.22      &  0.021 &   0.04  &     0.85  &    0.60  &    1.13   &    0.86    &  0.27     &       2\\
 59852&m      &$5000\pm100$& $2.2\pm0.2$ &81    &90     &100 &2.5$+0.2\atop-0.3$    &  0.71& 3464        & 0.15  &  0.0022&  -0.22  &     0.40  &    0.27  &    0.39   &    0.41    &  0.06     &       2\\
 77247&m      &$5050\pm100$ & $2.5\pm0.5$ &306  &346    &388    &3.9$+0.1\atop-0.2$    &  0.94  & 80      & 0.09      &  0.005 &  -0.13  &     0.73  &    0.75  &    0.76   &    0.68    &  -0.02    &       4\\
 84678&s      &$4600\pm100$& $1.7\pm0.2$ &154   &189    &227 &2.3$+0.6\atop-0.5$    &  0.83  & 1630        & 0.06  &  0.062 &  -0.13  &     1.09  &    1.21  &    2.04   &    1.52    &  0.63     &       2\\
 88562&s      &$4000\pm50$  & $2.0\pm0.5$ &240  &277    &321 &1.0$+0.1\atop-0.1$    &  0.51  & 1445        & 0.2   &  0.048 &  -0.53  &     0.93  &    0.43  &    1.15   &    1.02    &  0.41     &       1\\
 91208&m      &$5093\pm67$  & $2.9\pm0.3$ &35 9 &39     &43     &2.3$+0.1\atop-0.2$    &  0.68  & 1754        & 0.17  &  0.022 &  -0.16  &     0.94  &    0.61  &    0.81   &    0.84    &  0.05     &       2\\
 92626&s      &$4800\pm100$&   2.3          &171        &214    &259 &3.1$+0.4\atop-0.6$    &  0.98  & 918     & 0.        &  0.042 &  -0.15  &     0.99  &    1.21  &    2.51   &    1.74    &  1.02     &       2\\
 95193&m      &$5008\pm22$  & $2.8\pm0.1$ &59   &69     &79 &2.7$+0.1\atop-0.1$    &  0.76  & 1653        & 0.13  &  0.026 &  -0.04  &     0.75  &    0.26  &    0.50   &    0.36    &  -0.07    &       2\\
 98839&m      &$4917\pm34$  & $2.3\pm0.6$ &276  &332    &395 &4.3$+0.2\atop-0.2$    &  1.00  & 16471   & 0.56      &  0.056 &  -0.05  &     0.10  &    0.17  &    0.35   &    0.30    &  0.19     &       4\\
 101013&s     &$4722\pm32$  & $2.3\pm0.2$ &77   &108    &141    &1.7$+0.3\atop-0.3$    &  0.68 & 1711        & 0.2   &  0.037 &  -0.40  &     1.17  &    0.97  &    1.23   &    1.11    &  0.10     &       4\\
 104979&m     &$5100\pm100$& $2.7\pm0.2$&80     &95     &111 &2.7$+0.1\atop-0.2$    &  0.75 & 19295   & 0.08      &  -     &  -0.26  &     0.71  &    0.85  &    1.11   &    1.06    &  0.31     &      6 \\
 107541&s     &$5000\pm100$&  $3.2\pm0.2$ &8.9  &11     &14 &1.1$+0.2\atop-0.1$    &  0.54 & 3570        & 0.1   &  0.029 &  -0.63  &     1.53  &    1.35  &    2.52   &    1.87    &  0.75     &      2\\
 119185&m     &$4919\pm18$ &  $2.5\pm0.0$ &65   &77     &90. &1.7$+0.2\atop-0.2$    &  0.57& 22065   & 0.6       &  -     &  -0.42  &     0.30  &    0.21  &    0.54   &    0.60    &  0.32     &       2\\
 121447&s     &$4000\pm50$ &  $1.0\pm0.5$ &                  - &     -             &        -        &1.6$+0.1\atop-0.1$                      &  0.6    & 185.7   & 0.015 &  0.025 &  -0.90  &     1.35  &    1.57  &    2.39   &    2.22    &  0.84     &       1\\
 \hline
 \end{tabular}
 \end{table*}
 
 \addtocounter{table}{-1}
 
\begin{table*}
\caption[]{Continued. }

\begin{tabular}{ll|llrrr|ll|lll|rllllrr}
\hline
HD/DM  &  Ba & \multicolumn{1}{c}{$T_{\rm eff}$} & $\log g$ & $L_{\rm min}$ & $L$ & $L_{\rm max}$ & $M_{\rm {Ba}}$ &  $M_{\rm WD}$ &   $P$        & $e$   & $f(M)$ &    [Fe/H] &   [Y/Fe]&   [Zr/Fe] & [La/Fe]&   [Ce/Fe]   &  [hs/ls]  & Ref\\
\cline{5-7}
             &          & \multicolumn{1}{c}{(K)} & &
             \multicolumn{3}{c}{(L$_{\odot}$)} & (M$_{\odot}$) & (M$_{\odot}$) & (d) & & (M$_{\odot}$)\\
\hline
 123949&s    &$4378\pm80$ & $1.8\pm0.5$ &59     &92     &128  &1.3$+0.3\atop-0.1$    &  0.58& 8523        & 0.92  &  0.046 &  -0.23  &     0.91  &    0.88  &    1.21   &    1.28    &  0.35     &       1\\
 134698&m    &$4438\pm30$ & $1.7\pm0.3$ &163    &192&225  &1.5$+0.2\atop-0.2$    &  0.53& 10005   & 0.95      &  0.054 &  -0.57  &     0.56  &    0.59  &    0.65   &    0.53    &  0.02     &        2\\
 139195&m    &$5029\pm29$ & $3.1\pm0.2$  &38    &44     &514  &2.6$+0.1\atop-0.1$    &  0.74& 5324        & 0.35  &  0.026 &  -0.07  &     0.72  &    0.79  &    0.62   &    0.54    &  -0.17    &       4\\
 143899&m    &$5144\pm26$ &  $2.9\pm0.3$ &43    &50     &67  &2.4$+0.1\atop-0.1$    &  0.71& 1461        & 0.19  &  0.017 &  -0.29  &     0.86  &    0.57  &    0.90   &    0.90    &  0.19     &        2\\
 154430&s    &$4200\pm100$ &  $1.2\pm0.2$&382   &685    &1046     &2.3$+1.4\atop-0.7$    &  0.81& 1668        & 0.11  &  0.034 &  -0.36  &     0.93  &    0.97  &    2.00   &    1.33    &  0.71     &       2\\
 178717&s    &$3800\pm50$  & $1.0\pm0.5$&156    &1617   &3189         &1.6$+0.9\atop-0.7$    &  0.66& 2866        & 0.43  &  0.006 &  -0.52  &     0.79  &    0.44  &    0.85   &    0.74    &  0.18     &       1\\
 180622&m    &$4600\pm100$ & $2.2\pm0.2$ &59    &63     &68       &1.8$+0.3\atop-0.2$    &  0.59& 4049        & 0.06  &  0.07  &   0.03  &     0.61  &    0.41  &    0.48   &    0.27    &  -0.13    &       2\\
 183915&m$\rightarrow$s&$4494\pm130$&$1.6\pm0.4$&153    &266    &386&1.8$+1.0\atop-0.6$    &  0.60 & 4382        & 0.27  &  7E-05 &  -0.59  &     0.88  &    0.68  &    2.16   &    1.22    &  0.91     &        2\\
 196673&m    &$4914\pm9$   & $2.5\pm0.3$ &618   &900    &1206 &5.0$+0.0\atop-0.1$    &  1.10 & 7780    & 0.59      &  0.020 &  0.12  &     0.00  &    0.25  &    0.39   &    0.31    &  0.23     &        4\\
 199939&s    &$4710\pm9$   & $2.4\pm0.4$ &159   &214    &271 &2.8$+0.4\atop-0.4$    &  0.93 & 584.9   & 0.28      &  0.025 &  -0.22  &     1.38  &    1.19  &    1.72   &    1.67    &  0.41     &       1\\
 200063&m    &$4100\pm100$ & $1.1\pm0.2$   &206 &753    &1349      &2.0$+1.3\atop-0.9$    &  0.64 & 1735        & 0.07  &  0.058 &  -0.34  &     0.88  &    0.62  &    1.33   &    0.93    &  0.38     &       2    \\
 201657&s    &$4700\pm100$ & $2.2\pm0.2$ &63    &80     &100 &1.8$+0.5\atop-0.4$    &   0.70    & 1710        & 0.17  &  0.004 &  -0.34  &     0.72  &    0.98  &    1.91   &    1.44    &  0.82     &       2\\
 201824&s    &$4937\pm52$  & $2.6\pm0.2$ &51    &69     &90 &1.7$+0.4\atop-0.2$    &  0.68 & 2837        & 0.34  &  0.04  &  -0.40   &     0.91  &    0.87  &    1.58   &    1.48    &  0.64     &        2\\
 202109&m    &4700  &  2.4            &120      &147        &176 &3.4$+0.2\atop-0.4$    &  0.87     & 6489        & 0.22  &  0.023 &  -0.03  &     0.42  &    0.39  &    0.40   &    0.21    &  -0.10    &       9\\
 204075&m    &$5269\pm53$  & $1.7\pm0.3$ &418   &561    &741 &4.5$+0.3\atop-0.2$    &  1.03     & 2378        & 0.28  &  0.004 &  -0.09  &     1.37  &    1.37  &    1.04   &    0.85    &  -0.43    &        5\\
 205011&m    &$4803\pm21$  & $2.5\pm0.1$ &59    &73     &88 &1.8$+0.3\atop-0.3$    &  0.60 & 2837        & 0.24  &  0.034 &  -0.26  &     0.82  &    0.86  &    0.88   &    0.76    &  -0.02    &        4\\
 210946&m    &$4780\pm76$  & $2.4\pm0.2$ &50    &74     &99 &1.8$+0.5\atop-0.4$    &  0.59 & 1529        & 0.13  &  0.041 &  -0.29  &     0.77  &    0.56  &    0.81   &    0.66    &  0.07     &        2\\
 211594&s    &$4947\pm57$  & $2.6\pm0.1$ &49    &63     &77 &2.0$+0.3\atop-0.2$    &  0.76 & 1019        & 0.06  &  0.014 &  -0.29  &     1.20  &    1.18  &    2.31   &    1.57    &  0.75     &        2\\
 218356&m    &$4500\pm100$ &  1.8     &543      &733    &976 &4.3$+0.2\atop-1.1$    &  1.00 & 111         &   0&  4E-05 &  -0.06 &     0.45  &    0.26  &    0.90   &    0.51    &  0.35     &        7\\
 223617&m    &$4560\pm20$  & $2.2\pm0.1$ &61    &65         &70 &1.4$+0.1\atop-0.1$    &    0.51   & 1294        & 0.06  &  0.0064&  -0.20  &     0.70  &    0.73  &    1.03   &    0.67    &  0.14     &        4\\
 NGC \\
 2420-173&s$\rightarrow$m&$5150\pm100$&2.2&95   &128    &173&3.0$+0.3\atop-0.4$& 0.80& 1479 & 0.43 & 0.008 & -0.26 & 1.00 & 0.72 & 0.62 & 0.59 & -0.26 & 10 \\
\hline\\

\end{tabular}

References: (1) Karinkuzhi et al. (2018); (2) \citet{2016MNRAS.459.4299D}; (3) \citet{2006A&A...454..895A}; (4) This work; (5) \citet{2016A&A...586A.151M}; (6) \citet{2015MNRAS.446.2348K};
(7) \citet{2014AJ....147..137L}
(8) \citet{1984A&A...132..326S}; (9) \citet{2011A&A...533A..51P}; (10) \citet{2017A&A...597A..68V}; (11) \citet{1984A&A...132..326S}

\end{table*}
\renewcommand{\arraystretch}{1}
\setlength{\tabcolsep}{3pt}
"""

## Build the h5 table

In [3]:
# ---- helper functions ----
columns = [
    "System Name", "RA", "Dec", "Period", "Eccentricity",
    "M1","M1_sin3i", "M2", "M2_sin3i", "q", "Mass Function",
    "Type1", "Type2", "Detection Method", "Reference", "Notes"
]
df = pd.DataFrame(columns=columns)

def add_observation(df, system_name,
                    ra, dec, period, ecc,
                    m1, m1_sin3i, m2, m2_sin3i, q, mass_func,
                    type1, type2, method, reference, notes=""):
    new_row = {
        "System Name": system_name,
        "RA": ra,
        "Dec": dec,
        "Period": period,
        "Eccentricity": ecc,
        "M1": m1,
        "M1_sin3i": m1_sin3i,
        "M2": m2,
        "M2_sin3i": m2_sin3i,
        "q": q,
        "Mass Function": mass_func,
        "Type1": type1,
        "Type2": type2,
        "Detection Method": method,
        "Reference": reference,
        "Notes": notes,
    }
    return pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

TRI_NAN = [np.nan, np.nan, np.nan]

# ---- Parsing utilities (robust to odd TeX) ----
def clean_cell(s: str) -> str:
    s = s.strip()
    # join broken "NGC \\ \n 2420-173" cases in pre-pass
    return s

def to_float_or_nan(s: str) -> float | float:
    t = s.strip()
    t = t.replace(',', '')  # just in case
    # remove TeX wrappers
    t = re.sub(r"[${}\\]", "", t)
    t = t.replace(r"\,", "")
    t = t.replace(r"\cdot", "")
    t = t.replace("–", "-").replace("—", "-")
    # blanks or dashes
    if t == "" or t == "-" or t == "–":
        return np.nan
    # sometimes "0." appears; that's fine
    try:
        return float(t)
    except Exception:
        # pick the first number found (handles things like '0.' or '7E-05')
        m = re.search(r"[-+]?\d+(?:\.\d+)?(?:[Ee][-+]?\d+)?", t)
        return float(m.group(0)) if m else np.nan

def parse_asym_mass_triplet(s: str):
    """
    Parse M_Ba field like:
      '1.9$+0.7\\atop-0.5$'  → [0.5, 1.9, 0.7]
      '{\\sl 1.3}$+0.3\\atop-0.2$' → [0.2, 1.3, 0.3]
      '2.3$+1.4\\atop-0.7$' → [0.7, 2.3, 1.4]
      '1.6' → [nan, 1.6, nan]
    """
    t = s.strip()
    # keep a copy for fallback
    # normalize: turn "\atop" into a separator, strip TeX, keep signs
    t = t.replace("\\,", "")
    t = t.replace("\\atop", "|")
    t = re.sub(r"{\\sl\s*", "", t)       # drop slanted markup start
    t = t.replace("{", "").replace("}", "")
    t = t.replace("$", "")
    t = t.replace("\\", "")
    # extract numbers (value, +err, -err)
    nums = re.findall(r"[-+]?\d+(?:\.\d+)?(?:[Ee][-+]?\d+)?", t)
    if len(nums) >= 3:
        val = float(nums[0])
        plus = abs(float(nums[1]))
        minus = abs(float(nums[2]))
        return [minus, val, plus]
    elif len(nums) >= 1:
        val = float(nums[0])
        return [np.nan, val, np.nan]
    else:
        return TRI_NAN.copy()

def as_triplet_val(x):
    """Value only → [nan, value, nan] triplet."""
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return TRI_NAN.copy()
    try:
        v = float(x)
        return [np.nan, v, np.nan]
    except Exception:
        return TRI_NAN.copy()

def cleanup_name(cell0: str) -> str:
    """
    Turn the 'HD/DM' cell into a clean System Name:
     - ' 5424'  → 'HD 5424'
     - '$-64^\\circ$4333' → 'DM -64 4333'
     - 'NGC 2420-173' → as-is
    """
    raw = cell0.strip()
    # join DM pattern like $-64^\circ$4333
    m = re.match(r"\s*\$?\s*([+\-]?\d+)\s*\^\s*\\?circ\s*\$?\s*(\d+)", raw)
    if m:
        deg, num = m.group(1), m.group(2)
        return f"DM {deg} {num}"
    # strip TeX
    s = re.sub(r"[${}\\]", "", raw)
    s = s.replace("^circ", "")
    s = s.replace("^\circ", "")
    s = re.sub(r"\s+", " ", s).strip()
    if s.upper().startswith("NGC"):
        return s.replace(" \\\\", "").strip()
    # pure number → HD
    if re.fullmatch(r"\d+", s):
        return f"HD {s}"
    return s

def parse_ba_class(cell: str) -> str:
    # e.g., 'm', 's', 'm$\rightarrow$s'
    t = cell.strip()
    t = t.replace("$", "").replace("\\rightarrow", "->")
    return re.sub(r"\s+", "", t)

In [4]:
# ---- Pull data rows from both parts of the table ----
# pre-join the split "NGC \\ \n 2420-173" pattern
latex_text = re.sub(r"NGC\s*\\\\\s*\n\s*", "NGC ", latex_text)

data_rows = []
for line in latex_text.splitlines():
    if "&" in line and "\\" in line and not line.strip().startswith("\\"):
        data_rows.append(line.strip())

# some data rows may wrap onto the next line (rare). Join if the last cell lacks '\\'
# (We already filtered lines with '\\', so we’re fine.)

# ---- Parse each row into fields we need ----
REF_BIBCODES = ['2019A&A...626A.127J']  # you asked to use this for all rows

for raw in data_rows:
    # split columns
    cols = [c.strip() for c in raw.split("&")]
    # make sure we have enough columns (table has 19)
    if len(cols) < 12:
        continue

    # clean trailing '\\'
    cols[-1] = cols[-1].split("\\")[0].strip()

    # Column indices in this table:
    # 0: HD/DM, 1: Ba class, 2: Teff, 3: log g, 4: Lmin, 5: L, 6: Lmax,
    # 7: M_Ba, 8: M_WD, 9: P(d), 10: e, 11: f(M),
    # 12: [Fe/H], 13: [Y/Fe], 14: [Zr/Fe], 15: [La/Fe], 16: [Ce/Fe], 17: [hs/ls], 18: Ref
    # Some rows may slightly shift around in earlier columns; but 7..12 are quite stable.

    try:
        name = cleanup_name(cols[0])
        ba_class = parse_ba_class(cols[1])

        M_Ba_trip = parse_asym_mass_triplet(cols[7])
        M_WD_val  = to_float_or_nan(cols[8])
        P_val     = to_float_or_nan(cols[9])
        e_val     = to_float_or_nan(cols[10])
        fM_val    = to_float_or_nan(cols[11])
        feh_val   = to_float_or_nan(cols[12]) if len(cols) > 12 else np.nan
        hsls_val  = to_float_or_nan(cols[17]) if len(cols) > 17 else np.nan

        # Build triplets 
        M1 = M_Ba_trip                      # M1 = Ba star (accretor)
        M2 = as_triplet_val(M_WD_val)       # M2 = WD (past donor)
        Period = as_triplet_val(P_val)
        Ecc    = as_triplet_val(e_val)
        fM     = as_triplet_val(fM_val)

        # Mass ratio q = M2/M1 = WD/Ba (central values only, no propagated errs)
        q_val = np.nan
        if not np.isnan(M_WD_val) and not np.isnan(M_Ba_trip[1]) and M_Ba_trip[1] != 0:
            q_val = M_WD_val / M_Ba_trip[1]
        q_trip = as_triplet_val(q_val)

        # Notes
        notes_bits = [f"Ba class: {ba_class}"]
        if not np.isnan(feh_val):  notes_bits.append(f"[Fe/H]={feh_val:.2f}")
        if not np.isnan(hsls_val): notes_bits.append(f"[hs/ls]={hsls_val:.2f}")
        notes_bits.append("Type mapping: M1=Ba (accretor), M2=WD (previous donor)")
        notes = "; ".join(notes_bits)


        # Add row (CORRECTED types)
        df = add_observation(
            df,
            system_name=name,
            ra=TRI_NAN.copy(), dec=TRI_NAN.copy(),
            period=Period, ecc=Ecc,
            m1=M1, m1_sin3i=TRI_NAN.copy(),
            m2=M2, m2_sin3i=TRI_NAN.copy(),
            q=q_trip, mass_func=fM,
            type1="barium star", type2="white dwarf",
            method=["RV"],
            reference=['2019A&A...626A.127J'],
            notes=notes
        )


    except Exception as ex:
        # Skip malformed line but print it so you can inspect if needed
        print(f"[WARN] Could not parse row:\n{raw}\nReason: {ex}\n")

### Inspect table before continuing

In [5]:
# display(df)

## Turns out the HD/DM headers are accidentally taken in as data rows.
## Lets remove them.
no_header_bool = df['System Name'] != 'HD/DM'

df = df[no_header_bool].reset_index(drop=True)

display(df)

,System Name,RA,Dec,Period,Eccentricity,M1,M1_sin3i,M2,M2_sin3i,q,Mass Function,Type1,Type2,Detection Method,Reference,Notes
0,DM -64 4333,"[nan, nan, nan]","[nan, nan, nan]","[nan, 386.0, nan]","[nan, 0.03, nan]","[0.1, 1.4, 0.1]","[nan, nan, nan]","[nan, 0.61, nan]","[nan, nan, nan]","[nan, 0.4357142857142857, nan]","[nan, 0.068, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.10; [hs/ls]=0.84; Type ...
1,DM -42 2048,"[nan, nan, nan]","[nan, nan, nan]","[nan, 3260.0, nan]","[nan, 0.08, nan]","[0.5, 1.9, 0.7]","[nan, nan, nan]","[nan, 0.74, nan]","[nan, nan, nan]","[nan, 0.3894736842105263, nan]","[nan, 0.065, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.38; Type ...
2,DM -14 2678,"[nan, nan, nan]","[nan, nan, nan]","[nan, 3470.0, nan]","[nan, 0.22, nan]","[0.2, 3.0, 0.2]","[nan, nan, nan]","[nan, 0.8, nan]","[nan, nan, nan]","[nan, 0.26666666666666666, nan]","[nan, 0.023, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.01; [hs/ls]=0.04; Type m...
3,DM -01 3022,"[nan, nan, nan]","[nan, nan, nan]","[nan, 3253.0, nan]","[nan, 0.28, nan]","[0.1, 1.6, 0.1]","[nan, nan, nan]","[nan, 0.55, nan]","[nan, nan, nan]","[nan, 0.34375, nan]","[nan, 0.016, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.14; [hs/ls]=-0.26; Type...
4,HD 5424,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1881.0, nan]","[nan, 0.23, nan]","[0.3, 1.3, 0.4]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.4538461538461538, nan]","[nan, 0.005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.43; [hs/ls]=0.57; Type ...
5,HD 16458,"[nan, nan, nan]","[nan, nan, nan]","[nan, 2018.0, nan]","[nan, 0.1, nan]","[0.1, 1.9, 0.1]","[nan, nan, nan]","[nan, 0.72, nan]","[nan, nan, nan]","[nan, 0.37894736842105264, nan]","[nan, 0.041, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.64; [hs/ls]=0.19; Type ...
6,HD 18182,"[nan, nan, nan]","[nan, nan, nan]","[nan, 8059.0, nan]","[nan, 0.31, nan]","[0.1, 1.8, 0.2]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.0002, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.17; [hs/ls]=-0.05; Type...
7,HD 20394,"[nan, nan, nan]","[nan, nan, nan]","[nan, 2226.0, nan]","[nan, 0.2, nan]","[0.2, 2.0, 0.2]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.38, nan]","[nan, 0.002, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.27; [hs/ls]=0.42; Type ...
8,HD 24035,"[nan, nan, nan]","[nan, nan, nan]","[nan, 377.8, nan]","[nan, 0.3, nan]","[0.2, 1.3, 0.3]","[nan, nan, nan]","[nan, 0.57, nan]","[nan, nan, nan]","[nan, 0.4384615384615384, nan]","[nan, 0.047, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.87; Type ...
9,HD 27271,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1693.0, nan]","[nan, 0.22, nan]","[0.2, 2.9, 0.2]","[nan, nan, nan]","[nan, 0.79, nan]","[nan, nan, nan]","[nan, 0.2724137931034483, nan]","[nan, 0.024, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.07; [hs/ls]=-0.13; Type...
10,HD 31487,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1066.0, nan]","[nan, 0.05, nan]","[0.3, 3.4, 0.2]","[nan, nan, nan]","[nan, 1.03, nan]","[nan, nan, nan]","[nan, 0.30294117647058827, nan]","[nan, 0.038, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.04; [hs/ls]=0.32; Type ...
11,HD 40430,"[nan, nan, nan]","[nan, nan, nan]","[nan, 5609.0, nan]","[nan, 0.22, nan]","[0.2, 2.3, 0.2]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.29565217391304355, nan]","[nan, 0.0025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.34; [hs/ls]=0.23; Type ...
12,HD 43389,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1689.0, nan]","[nan, 0.08, nan]","[0.3, 1.8, 0.4]","[nan, nan, nan]","[nan, 0.72, nan]","[nan, nan, nan]","[nan, 0.39999999999999997, nan]","[nan, 0.043, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.35; [hs/ls]=0.76; Type ...
13,HD 44896,"[nan, nan, nan]","[nan, nan, nan]","[nan, 629.0, nan]","[nan, 0.02, nan]","[1.0, 3.0, 1.2]","[nan, nan, nan]","[nan, 0.96, nan]","[nan, nan, nan]","[nan, 0.32, nan]","[nan, 0.048, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.25; [hs/ls]=-0.09; Type...
14,HD 46407,"[nan, nan, nan]","[nan, nan, nan]","[nan, 457.0, nan]","[nan, 0.013, nan]","[0.7, 2.1, 0.6]","[nan, nan, nan]","[nan, 0.78, nan]","[nan, nan, nan]","[nan, 0.37142857142857144, nan]","[nan, 0.035, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.35; [hs/ls]=0.31; Type ...
15,HD 49641,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1785.0, nan]","[nan, 0.07, nan]","[0.8, 2.7, 1.2]","[nan, nan, nan]","[nan, 0.91, nan]","[nan, nan, nan]","[nan, 0.337037037037037, nan]","[nan, 0.003, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.30; [hs/ls]=0.74; Type ...
16,HD 49841,"[nan, nan, nan]","[nan, nan, nan]","[nan, 897.0, nan]","[nan, 0.16, nan]","[0.2, 2.8, 0.2]","[nan, nan, nan]","[nan, 0.78, nan]","[nan, nan, nan]","[nan, 0.2785714285714286, nan]","[nan, 0.032, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.20; [hs/ls]=-0.06; Type ...
17,HD 50082,"[nan, nan, nan]","[nan, nan, nan]","[nan, 2896.0, nan]","[nan, 0.19, nan]","[0.2, 1.6, 0.3]","[nan, nan, nan]","[nan, 0.67, nan]","[nan, nan, nan]","[nan, 0.41875, nan]","[nan, 0.027, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.32; [hs/ls]=0.44; Type ...
18,HD 51959,"[nan, nan, nan]","[nan, nan, nan]","[nan, 9718.0, nan]","[nan, 0.53, nan]","[0.1, 1.2, 0.1]","[nan, nan, nan]","[nan, 0.47, nan]","[nan, nan, nan]","[nan, 0.39166666666666666, nan]","[nan, 0.0005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.21; [hs/ls]=-0.13; Type...
19,HD 53199,"[nan, nan, nan]","[nan, nan, nan]","[nan, 8314.0, nan]","[nan, 0.24, nan]","[0.1, 2.5, 0.1]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.284, nan]","[nan, 0.028, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.20; [hs/ls]=0.31; Type ...
20,HD 58121,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1214.0, nan]","[nan, 0.14, nan]","[0.4, 2.6, 0.5]","[nan, nan, nan]","[nan, 0.73, nan]","[nan, nan, nan]","[nan, 0.28076923076923077, nan]","[nan, 0.015, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.01; [hs/ls]=0.10; Type ...
21,HD 58368,"[nan, nan, nan]","[nan, nan, nan]","[nan, 672.0, nan]","[nan, 0.22, nan]","[0.2, 2.6, 0.1]","[nan, nan, nan]","[nan, 0.73, nan]","[nan, nan, nan]","[nan, 0.28076923076923077, nan]","[nan, 0.021, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.04; [hs/ls]=0.27; Type m...
22,HD 59852,"[nan, nan, nan]","[nan, nan, nan]","[nan, 3464.0, nan]","[nan, 0.15, nan]","[0.3, 2.5, 0.2]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.284, nan]","[nan, 0.0022, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.22; [hs/ls]=0.06; Type ...
23,HD 77247,"[nan, nan, nan]","[nan, nan, nan]","[nan, 80.0, nan]","[nan, 0.09, nan]","[0.2, 3.9, 0.1]","[nan, nan, nan]","[nan, 0.94, nan]","[nan, nan, nan]","[nan, 0.24102564102564103, nan]","[nan, 0.005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.13; [hs/ls]=-0.02; Type...
24,HD 84678,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1630.0, nan]","[nan, 0.06, nan]","[0.5, 2.3, 0.6]","[nan, nan, nan]","[nan, 0.83, nan]","[nan, nan, nan]","[nan, 0.36086956521739133, nan]","[nan, 0.062, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.13; [hs/ls]=0.63; Type ...
25,HD 88562,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1445.0, nan]","[nan, 0.2, nan]","[0.1, 1.0, 0.1]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, 0.048, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.53; [hs/ls]=0.41; Type ...
26,HD 91208,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1754.0, nan]","[nan, 0.17, nan]","[0.2, 2.3, 0.1]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.29565217391304355, nan]","[nan, 0.022, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.16; [hs/ls]=0.05; Type ...
27,HD 92626,"[nan, nan, nan]","[nan, nan, nan]","[nan, 918.0, nan]","[nan, 0.0, nan]","[0.6, 3.1, 0.4]","[nan, nan, nan]","[nan, 0.98, nan]","[nan, nan, nan]","[nan, 0.3161290322580645, nan]","[nan, 0.042, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.15; [hs/ls]=1.02; Type ...
28,HD 95193,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1653.0, nan]","[nan, 0.13, nan]","[0.1, 2.7, 0.1]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.28148148148148144, nan]","[nan, 0.026, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.04; [hs/ls]=-0.07; Type...
29,HD 98839,"[nan, nan, nan]","[nan, nan, nan]","[nan, 16471.0, nan]","[nan, 0.56, nan]","[0.2, 4.3, 0.2]","[nan, nan, nan]","[nan, 1.0, nan]","[nan, nan, nan]","[nan, 0.23255813953488372, nan]","[nan, 0.056, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.05; [hs/ls]=0.19; Type ...
30,HD 101013,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1711.0, nan]","[nan, 0.2, nan]","[0.3, 1.7, 0.3]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.4, nan]","[nan, 0.037, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.40; [hs/ls]=0.10; Type ...
31,HD 104979,"[nan, nan, nan]","[nan, nan, nan]","[nan, 19295.0, nan]","[nan, 0.08, nan]","[0.2, 2.7, 0.1]","[nan, nan, nan]","[nan, 0.75, nan]","[nan, nan, nan]","[nan, 0.27777777777777773, nan]","[nan, nan, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.26; [hs/ls]=0.31; Type ...
32,HD 107541,"[nan, nan, nan]","[nan, nan, nan]","[nan, 3570.0, nan]","[nan, 0.1, nan]","[0.1, 1.1, 0.2]","[nan, nan, nan]","[nan, 0.54, nan]","[nan, nan, nan]","[nan, 0.4909090909090909, nan]","[nan, 0.029, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.63; [hs/ls]=0.75; Type ...
33,HD 119185,"[nan, nan, nan]","[nan, nan, nan]","[nan, 22065.0, nan]","[nan, 0.6, nan]","[0.2, 1.7, 0.2]","[nan, nan, nan]","[nan, 0.57, nan]","[nan, nan, nan]","[nan, 0.3352941176470588, nan]","[nan, nan, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.42; [hs/ls]=0.32; Type ...
34,HD 121447,"[nan, nan, nan]","[nan, nan, nan]","[nan, 185.7, nan]","[nan, 0.015, nan]","[0.1, 1.6, 0.1]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.37499999999999994, nan]","[nan, 0.025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.90; [hs/ls]=0.84; Type ...
35,HD 123949,"[nan, nan, nan]","[nan, nan, nan]","[nan, 8523.0, nan]","[nan, 0.92, nan]","[0.1, 1.3, 0.3]","[nan, nan, nan]","[nan, 0.58, nan]","[nan, nan, nan]","[nan, 0.4461538461538461, nan]","[nan, 0.046, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.35; Type ...
36,HD 134698,"[nan, nan, nan]","[nan, nan, nan]","[nan, 10005.0, nan]","[nan, 0.95, nan]","[0.2, 1.5, 0.2]","[nan, nan, nan]","[nan, 0.53, nan]","[nan, nan, nan]","[nan, 0.35333333333333333, nan]","[nan, 0.054, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.57; [hs/ls]=0.02; Type ...
37,HD 139195,"[nan, nan, nan]","[nan, nan, nan]","[nan, 5324.0, nan]","[nan, 0.35, nan]","[0.1, 2.6, 0.1]","[nan, nan, nan]","[nan, 0.74, nan]","[nan, nan, nan]","[nan, 0.2846153846153846, nan]","[nan, 0.026, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.07; [hs/ls]=-0.17; Type...
38,HD 143899,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1461.0, nan]","[nan, 0.19, nan]","[0.1, 2.4, 0.1]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.29583333333333334, nan]","[nan, 0.017, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.29; [hs/ls]=0.19; Type ...
39,HD 154430,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1668.0, nan]","[nan, 0.11, nan]","[0.7, 2.3, 1.4]","[nan, nan, nan]","[nan, 0.81, nan]","[nan, nan, nan]","[nan, 0.35217391304347834, nan]","[nan, 0.034, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.36; [hs/ls]=0.71; Type ...
40,HD 178717,"[nan, nan, nan]","[nan, nan, nan]","[nan, 2866.0, nan]","[nan, 0.43, nan]","[0.7, 1.6, 0.9]","[nan, nan, nan]","[nan, 0.66, nan]","[nan, nan, nan]","[nan, 0.4125, nan]","[nan, 0.006, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.52; [hs/ls]=0.18; Type ...
41,HD 180622,"[nan, nan, nan]","[nan, nan, nan]","[nan, 4049.0, nan]","[nan, 0.06, nan]","[0.2, 1.8, 0.3]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.07, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.03; [hs/ls]=-0.13; Type ...
42,HD 183915,"[nan, nan, nan]","[nan, nan, nan]","[nan, 4382.0, nan]","[nan, 0.27, nan]","[0.6, 1.8, 1.0]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.3333333333333333, nan]","[nan, 7e-05, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m->s; [Fe/H]=-0.59; [hs/ls]=0.91; Ty...
43,HD 196673,"[nan, nan, nan]","[nan, nan, nan]","[nan, 7780.0, nan]","[nan, 0.59, nan]","[0.1, 5.0, 0.0]","[nan, nan, nan]","[nan, 1.1, nan]","[nan, nan, nan]","[nan, 0.22000000000000003, nan]","[nan, 0.02, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.12; [hs/ls]=0.23; Type m...
44,HD 199939,"[nan, nan, nan]","[nan, nan, nan]","[nan, 584.9, nan]","[nan, 0.28, nan]","[0.4, 2.8, 0.4]","[nan, nan, nan]","[nan, 0.93, nan]","[nan, nan, nan]","[nan, 0.3321428571428572, nan]","[nan, 0.025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.22; [hs/ls]=0.41; Type ...
45,HD 200063,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1735.0, nan]","[nan, 0.07, nan]","[0.9, 2.0, 1.3]","[nan, nan, nan]","[nan, 0.64, nan]","[nan, nan, nan]","[nan, 0.32, nan]","[nan, 0.058, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.34; [hs/ls]=0.38; Type ...
46,HD 201657,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1710.0, nan]","[nan, 0.17, nan]","[0.4, 1.8, 0.5]","[nan, nan, nan]","[nan, 0.7, nan]","[nan, nan, nan]","[nan, 0.38888888888888884, nan]","[nan, 0.004, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.34; [hs/ls]=0.82; Type ...
47,HD 201824,"[nan, nan, nan]","[nan, nan, nan]","[nan, 2837.0, nan]","[nan, 0.34, nan]","[0.2, 1.7, 0.4]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.4, nan]","[nan, 0.04, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.40; [hs/ls]=0.64; Type ...
48,HD 202109,"[nan, nan, nan]","[nan, nan, nan]","[nan, 6489.0, nan]","[nan, 0.22, nan]","[0.4, 3.4, 0.2]","[nan, nan, nan]","[nan, 0.87, nan]","[nan, nan, nan]","[nan, 0.25588235294117645, nan]","[nan, 0.023, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.03; [hs/ls]=-0.10; Type...
49,HD 204075,"[nan, nan, nan]","[nan, nan, nan]","[nan, 2378.0, nan]","[nan, 0.28, nan]","[0.2, 4.5, 0.3]","[nan, nan, nan]","[nan, 1.03, nan]","[nan, nan, nan]","[nan, 0.2288888888888889, nan]","[nan, 0.004, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.09; [hs/ls]=-0.43; Type...
50,HD 205011,"[nan, nan, nan]","[nan, nan, nan]","[nan, 2837.0, nan]","[nan, 0.24, nan]","[0.3, 1.8, 0.3]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.3333333333333333, nan]","[nan, 0.034, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.26; [hs/ls]=-0.02; Type...
51,HD 210946,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1529.0, nan]","[nan, 0.13, nan]","[0.4, 1.8, 0.5]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.041, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.29; [hs/ls]=0.07; Type ...
52,HD 211594,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1019.0, nan]","[nan, 0.06, nan]","[0.2, 2.0, 0.3]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.38, nan]","[nan, 0.014, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.29; [hs/ls]=0.75; Type ...
53,HD 218356,"[nan, nan, nan]","[nan, nan, nan]","[nan, 111.0, nan]","[nan, 0.0, nan]","[1.1, 4.3, 0.2]","[nan, nan, nan]","[nan, 1.0, nan]","[nan, nan, nan]","[nan, 0.23255813953488372, nan]","[nan, 4e-05, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.06; [hs/ls]=0.35; Type ...
54,HD 223617,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1294.0, nan]","[nan, 0.06, nan]","[0.1, 1.4, 0.1]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, nan, nan]","[nan, 0.3642857142857143, nan]","[nan, 0.0064, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.20; [hs/ls]=0.14; Type ...
55,NGC 2420-173,"[nan, nan, nan]","[nan, nan, nan]","[nan, 1479.0, nan]","[nan, 0.43, nan]","[0.4, 3.0, 0.3]","[nan, nan, nan]","[nan, 0.8, nan]","[nan, nan, nan]","[nan, 0.26666666666666666, nan]","[nan, 0.008, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s->m; [Fe/H]=-0.26; [hs/ls]=-0.26; T...

## RA and DEC in the right format

In [6]:
# Collect the system names from the DataFrame
targets = df["System Name"].tolist()

display(df['System Name'].values)
targets = df['System Name'].values.tolist()

# Run the script and capture output
result = subprocess.run(["python3", "Get_Coords_From_SIMBAD.py"] + targets, capture_output=True, text=True)


# print("STDOUT:\n", result.stdout)
# Script prints one dict per system like:
#  *__89_HER = {
#     "System Name": '*  89 Her',
#     "RA":  [0.00001144, 268.854951, 0.00001144],
#     "Dec": [0.00001275, 26.049991, 0.00001275],
# }

# Get the printed output as a string
RA_DEC = result.stdout

entries = re.findall(r'([A-Z0-9_]+)\s*=\s*({.*?})', RA_DEC, re.DOTALL)
RADEC_data = {}

for name, dict_str in entries:
    RADEC_data[name] = ast.literal_eval(dict_str)

RADEC_data.keys()
# Now `RADEC_data` is a Python dictionary with the object data
# print(RADEC_data['HD__58978']['RA'])
# print(RADEC_data['HD__58978']['Dec'])

# Extract RA and Dec values
RA_values = [RADEC_data[key]['RA'] for key in RADEC_data.keys() ]
DEC_values = [RADEC_data[key]['Dec'] for key in RADEC_data.keys() ]


print(RA_values)
print(DEC_values)

df["RA"]  = RA_values
df["Dec"] = DEC_values

array(['DM -64 4333', 'DM -42 2048', 'DM -14 2678', 'DM -01 3022',
       'HD 5424', 'HD 16458', 'HD 18182', 'HD 20394', 'HD 24035',
       'HD 27271', 'HD 31487', 'HD 40430', 'HD 43389', 'HD 44896',
       'HD 46407', 'HD 49641', 'HD 49841', 'HD 50082', 'HD 51959',
       'HD 53199', 'HD 58121', 'HD 58368', 'HD 59852', 'HD 77247',
       'HD 84678', 'HD 88562', 'HD 91208', 'HD 92626', 'HD 95193',
       'HD 98839', 'HD 101013', 'HD 104979', 'HD 107541', 'HD 119185',
       'HD 121447', 'HD 123949', 'HD 134698', 'HD 139195', 'HD 143899',
       'HD 154430', 'HD 178717', 'HD 180622', 'HD 183915', 'HD 196673',
       'HD 199939', 'HD 200063', 'HD 201657', 'HD 201824', 'HD 202109',
       'HD 204075', 'HD 205011', 'HD 210946', 'HD 211594', 'HD 218356',
       'HD 223617', 'NGC 2420-173'], dtype=object)

[[2.567e-05, 349.129716, 2.567e-05], [3.87e-06, 84.501334, 3.87e-06], [3.13e-06, 132.981509, 3.13e-06], [8.62e-06, 226.86194, 8.62e-06], [1.691e-05, 13.933035, 1.691e-05], [0.0001076, 41.948857, 0.0001076], [4.07e-06, 43.796224, 4.07e-06], [1.29e-05, 49.223252, 1.29e-05], [7.361e-05, 55.927469, 7.361e-05], [2.447e-05, 64.640935, 2.447e-05], [2.677e-05, 74.765533, 2.677e-05], [5.94e-06, 89.585, 5.94e-06], [1.084e-05, 93.946117, 1.084e-05], [1.815e-05, 95.724037, 1.815e-05], [4.275e-05, 98.195305, 4.275e-05], [1.086e-05, 102.372703, 1.086e-05], [2.367e-05, 102.662379, 2.367e-05], [2.673e-05, 102.974829, 2.673e-05], [5.26e-06, 104.792067, 5.26e-06], [5.08e-06, 106.201188, 5.08e-06], [1.503e-05, 111.11849, 1.503e-05], [2.298e-05, 111.412367, 2.298e-05], [5.63e-06, 112.94398, 5.63e-06], [7.31e-06, 135.884467, 7.31e-06], [3.938e-05, 145.46907, 3.938e-05], [1.82e-05, 153.124761, 1.82e-05], [1.563e-05, 157.888064, 1.563e-05], [3.227e-05, 160.208219, 3.227e-05], [1.882e-05, 164.861565, 1.882e-05], [2.274e-05, 170.706575, 2.274e-05], [2.846e-05, 174.470837, 2.846e-05], [3.519e-05, 181.302216, 3.519e-05], [9.74e-06, 185.450318, 9.74e-06], [5.16e-06, 205.489634, 5.16e-06], [7.4e-06, 208.94569, 7.4e-06], [2.496e-05, 212.747131, 2.496e-05], [5.99e-06, 227.923757, 5.99e-06], [2.124e-05, 234.123225, 2.124e-05], [1.636e-05, 240.932528, 1.636e-05], [1.757e-05, 257.226142, 1.757e-05], [6.27e-06, 287.341706, 6.27e-06], [1.131e-05, 289.295952, 1.131e-05], [6.1e-06, 292.856266, 6.1e-06], [0.00015632, 309.434684, 0.00015632], [1.454e-05, 314.681226, 1.454e-05], [7.83e-06, 315.266853, 7.83e-06], [2.283e-05, 317.639716, 2.283e-05], [6.18e-06, 318.073264, 6.18e-06], [2.575e-05, 318.234108, 2.575e-05], [7.217e-05, 321.666794, 7.217e-05], [9.08e-06, 322.958936, 9.08e-06], [1.715e-05, 333.458969, 1.715e-05], [4.018e-05, 334.562273, 4.018e-05], [2.975e-05, 346.778091, 2.975e-05], [4.184e-05, 357.778324, 4.184e-05], [5.59e-06, 114.612357, 5.59e-06]]
[[1.178e-05, -63.451273, 1.178e-05], [3.03e-06, -42.326459, 3.03e-06], [2.67e-06, -14.652608, 2.67e-06], [7.56e-06, -2.305382, 7.56e-06], [1.397e-05, -27.893684, 1.397e-05], [1.678e-05, 81.448474, 1.678e-05], [3.94e-06, -4.316631, 3.94e-06], [1.178e-05, 2.339352, 1.178e-05], [2.25e-05, -72.609111, 2.25e-05], [1.803e-05, 2.470529, 1.803e-05], [1.322e-05, 51.942231, 1.322e-05], [5.58e-06, -10.874762, 5.58e-06], [9.81e-06, -2.385622, 9.81e-06], [1.694e-05, -33.614603, 1.694e-05], [4.85e-05, -11.166385, 4.85e-05], [9.33e-06, 3.691706, 9.33e-06], [2.353e-05, 5.66287, 2.353e-05], [2.417e-05, 6.6068, 2.417e-05], [5.47e-06, -7.108898, 5.47e-06], [4.39e-06, 13.238671, 4.39e-06], [1.239e-05, 6.150253, 1.239e-05], [1.969e-05, 7.560846, 1.969e-05], [5.03e-06, -4.359804, 5.03e-06], [3.92e-06, 53.108283, 3.92e-06], [1.075e-05, -75.664277, 1.075e-05], [1.614e-05, -15.889798, 1.614e-05], [1.447e-05, -17.076536, 1.447e-05], [2.283e-05, -48.025103, 2.283e-05], [1.447e-05, -14.171594, 1.447e-05], [2.233e-05, 43.482698, 2.233e-05], [2.258e-05, 50.618186, 2.258e-05], [2.853e-05, 8.733019, 2.853e-05], [5.83e-06, -34.780037, 5.83e-06], [4.22e-06, -13.027725, 4.22e-06], [6.17e-06, -18.249024, 6.17e-06], [1.669e-05, -19.143952, 1.669e-05], [5.06e-06, -10.507657, 5.06e-06], [2.081e-05, 10.010147, 2.081e-05], [1.033e-05, -19.575203, 1.033e-05], [7.86e-06, -59.287852, 7.86e-06], [6.33e-06, 10.241178, 6.33e-06], [1.078e-05, 0.497366, 1.078e-05], [6.36e-06, 11.627951, 6.36e-06], [0.00012222, 33.366492, 0.00012222], [1.047e-05, 44.414578, 1.047e-05], [3.36e-06, 1.034923, 3.36e-06], [1.589e-05, 16.979567, 1.589e-05], [5.64e-06, -8.356904, 5.64e-06], [2.478e-05, 30.226899, 2.478e-05], [4.614e-05, -22.41132, 4.614e-05], [5.92e-06, 23.845163, 5.92e-06], [1.789e-05, 1.60893, 1.789e-05], [3.919e-05, -5.841626, 3.919e-05], [1.933e-05, 25.468271, 1.933e-05], [2.228e-05, 2.237851, 2.228e-05], [4.19e-06, 21.558695, 4.19e-06]]

# Check what it looks like:

In [7]:
display(df)

,System Name,RA,Dec,Period,Eccentricity,M1,M1_sin3i,M2,M2_sin3i,q,Mass Function,Type1,Type2,Detection Method,Reference,Notes
0,DM -64 4333,"[2.567e-05, 349.129716, 2.567e-05]","[1.178e-05, -63.451273, 1.178e-05]","[nan, 386.0, nan]","[nan, 0.03, nan]","[0.1, 1.4, 0.1]","[nan, nan, nan]","[nan, 0.61, nan]","[nan, nan, nan]","[nan, 0.4357142857142857, nan]","[nan, 0.068, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.10; [hs/ls]=0.84; Type ...
1,DM -42 2048,"[3.87e-06, 84.501334, 3.87e-06]","[3.03e-06, -42.326459, 3.03e-06]","[nan, 3260.0, nan]","[nan, 0.08, nan]","[0.5, 1.9, 0.7]","[nan, nan, nan]","[nan, 0.74, nan]","[nan, nan, nan]","[nan, 0.3894736842105263, nan]","[nan, 0.065, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.38; Type ...
2,DM -14 2678,"[3.13e-06, 132.981509, 3.13e-06]","[2.67e-06, -14.652608, 2.67e-06]","[nan, 3470.0, nan]","[nan, 0.22, nan]","[0.2, 3.0, 0.2]","[nan, nan, nan]","[nan, 0.8, nan]","[nan, nan, nan]","[nan, 0.26666666666666666, nan]","[nan, 0.023, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.01; [hs/ls]=0.04; Type m...
3,DM -01 3022,"[8.62e-06, 226.86194, 8.62e-06]","[7.56e-06, -2.305382, 7.56e-06]","[nan, 3253.0, nan]","[nan, 0.28, nan]","[0.1, 1.6, 0.1]","[nan, nan, nan]","[nan, 0.55, nan]","[nan, nan, nan]","[nan, 0.34375, nan]","[nan, 0.016, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.14; [hs/ls]=-0.26; Type...
4,HD 5424,"[1.691e-05, 13.933035, 1.691e-05]","[1.397e-05, -27.893684, 1.397e-05]","[nan, 1881.0, nan]","[nan, 0.23, nan]","[0.3, 1.3, 0.4]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.4538461538461538, nan]","[nan, 0.005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.43; [hs/ls]=0.57; Type ...
5,HD 16458,"[0.0001076, 41.948857, 0.0001076]","[1.678e-05, 81.448474, 1.678e-05]","[nan, 2018.0, nan]","[nan, 0.1, nan]","[0.1, 1.9, 0.1]","[nan, nan, nan]","[nan, 0.72, nan]","[nan, nan, nan]","[nan, 0.37894736842105264, nan]","[nan, 0.041, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.64; [hs/ls]=0.19; Type ...
6,HD 18182,"[4.07e-06, 43.796224, 4.07e-06]","[3.94e-06, -4.316631, 3.94e-06]","[nan, 8059.0, nan]","[nan, 0.31, nan]","[0.1, 1.8, 0.2]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.0002, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.17; [hs/ls]=-0.05; Type...
7,HD 20394,"[1.29e-05, 49.223252, 1.29e-05]","[1.178e-05, 2.339352, 1.178e-05]","[nan, 2226.0, nan]","[nan, 0.2, nan]","[0.2, 2.0, 0.2]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.38, nan]","[nan, 0.002, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.27; [hs/ls]=0.42; Type ...
8,HD 24035,"[7.361e-05, 55.927469, 7.361e-05]","[2.25e-05, -72.609111, 2.25e-05]","[nan, 377.8, nan]","[nan, 0.3, nan]","[0.2, 1.3, 0.3]","[nan, nan, nan]","[nan, 0.57, nan]","[nan, nan, nan]","[nan, 0.4384615384615384, nan]","[nan, 0.047, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.87; Type ...
9,HD 27271,"[2.447e-05, 64.640935, 2.447e-05]","[1.803e-05, 2.470529, 1.803e-05]","[nan, 1693.0, nan]","[nan, 0.22, nan]","[0.2, 2.9, 0.2]","[nan, nan, nan]","[nan, 0.79, nan]","[nan, nan, nan]","[nan, 0.2724137931034483, nan]","[nan, 0.024, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.07; [hs/ls]=-0.13; Type...
10,HD 31487,"[2.677e-05, 74.765533, 2.677e-05]","[1.322e-05, 51.942231, 1.322e-05]","[nan, 1066.0, nan]","[nan, 0.05, nan]","[0.3, 3.4, 0.2]","[nan, nan, nan]","[nan, 1.03, nan]","[nan, nan, nan]","[nan, 0.30294117647058827, nan]","[nan, 0.038, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.04; [hs/ls]=0.32; Type ...
11,HD 40430,"[5.94e-06, 89.585, 5.94e-06]","[5.58e-06, -10.874762, 5.58e-06]","[nan, 5609.0, nan]","[nan, 0.22, nan]","[0.2, 2.3, 0.2]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.29565217391304355, nan]","[nan, 0.0025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.34; [hs/ls]=0.23; Type ...
12,HD 43389,"[1.084e-05, 93.946117, 1.084e-05]","[9.81e-06, -2.385622, 9.81e-06]","[nan, 1689.0, nan]","[nan, 0.08, nan]","[0.3, 1.8, 0.4]","[nan, nan, nan]","[nan, 0.72, nan]","[nan, nan, nan]","[nan, 0.39999999999999997, nan]","[nan, 0.043, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.35; [hs/ls]=0.76; Type ...
13,HD 44896,"[1.815e-05, 95.724037, 1.815e-05]","[1.694e-05, -33.614603, 1.694e-05]","[nan, 629.0, nan]","[nan, 0.02, nan]","[1.0, 3.0, 1.2]","[nan, nan, nan]","[nan, 0.96, nan]","[nan, nan, nan]","[nan, 0.32, nan]","[nan, 0.048, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.25; [hs/ls]=-0.09; Type...
14,HD 46407,"[4.275e-05, 98.195305, 4.275e-05]","[4.85e-05, -11.166385, 4.85e-05]","[nan, 457.0, nan]","[nan, 0.013, nan]","[0.7, 2.1, 0.6]","[nan, nan, nan]","[nan, 0.78, nan]","[nan, nan, nan]","[nan, 0.37142857142857144, nan]","[nan, 0.035, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.35; [hs/ls]=0.31; Type ...
15,HD 49641,"[1.086e-05, 102.372703, 1.086e-05]","[9.33e-06, 3.691706, 9.33e-06]","[nan, 1785.0, nan]","[nan, 0.07, nan]","[0.8, 2.7, 1.2]","[nan, nan, nan]","[nan, 0.91, nan]","[nan, nan, nan]","[nan, 0.337037037037037, nan]","[nan, 0.003, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.30; [hs/ls]=0.74; Type ...
16,HD 49841,"[2.367e-05, 102.662379, 2.367e-05]","[2.353e-05, 5.66287, 2.353e-05]","[nan, 897.0, nan]","[nan, 0.16, nan]","[0.2, 2.8, 0.2]","[nan, nan, nan]","[nan, 0.78, nan]","[nan, nan, nan]","[nan, 0.2785714285714286, nan]","[nan, 0.032, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.20; [hs/ls]=-0.06; Type ...
17,HD 50082,"[2.673e-05, 102.974829, 2.673e-05]","[2.417e-05, 6.6068, 2.417e-05]","[nan, 2896.0, nan]","[nan, 0.19, nan]","[0.2, 1.6, 0.3]","[nan, nan, nan]","[nan, 0.67, nan]","[nan, nan, nan]","[nan, 0.41875, nan]","[nan, 0.027, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.32; [hs/ls]=0.44; Type ...
18,HD 51959,"[5.26e-06, 104.792067, 5.26e-06]","[5.47e-06, -7.108898, 5.47e-06]","[nan, 9718.0, nan]","[nan, 0.53, nan]","[0.1, 1.2, 0.1]","[nan, nan, nan]","[nan, 0.47, nan]","[nan, nan, nan]","[nan, 0.39166666666666666, nan]","[nan, 0.0005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.21; [hs/ls]=-0.13; Type...
19,HD 53199,"[5.08e-06, 106.201188, 5.08e-06]","[4.39e-06, 13.238671, 4.39e-06]","[nan, 8314.0, nan]","[nan, 0.24, nan]","[0.1, 2.5, 0.1]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.284, nan]","[nan, 0.028, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.20; [hs/ls]=0.31; Type ...
20,HD 58121,"[1.503e-05, 111.11849, 1.503e-05]","[1.239e-05, 6.150253, 1.239e-05]","[nan, 1214.0, nan]","[nan, 0.14, nan]","[0.4, 2.6, 0.5]","[nan, nan, nan]","[nan, 0.73, nan]","[nan, nan, nan]","[nan, 0.28076923076923077, nan]","[nan, 0.015, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.01; [hs/ls]=0.10; Type ...
21,HD 58368,"[2.298e-05, 111.412367, 2.298e-05]","[1.969e-05, 7.560846, 1.969e-05]","[nan, 672.0, nan]","[nan, 0.22, nan]","[0.2, 2.6, 0.1]","[nan, nan, nan]","[nan, 0.73, nan]","[nan, nan, nan]","[nan, 0.28076923076923077, nan]","[nan, 0.021, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.04; [hs/ls]=0.27; Type m...
22,HD 59852,"[5.63e-06, 112.94398, 5.63e-06]","[5.03e-06, -4.359804, 5.03e-06]","[nan, 3464.0, nan]","[nan, 0.15, nan]","[0.3, 2.5, 0.2]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.284, nan]","[nan, 0.0022, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.22; [hs/ls]=0.06; Type ...
23,HD 77247,"[7.31e-06, 135.884467, 7.31e-06]","[3.92e-06, 53.108283, 3.92e-06]","[nan, 80.0, nan]","[nan, 0.09, nan]","[0.2, 3.9, 0.1]","[nan, nan, nan]","[nan, 0.94, nan]","[nan, nan, nan]","[nan, 0.24102564102564103, nan]","[nan, 0.005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.13; [hs/ls]=-0.02; Type...
24,HD 84678,"[3.938e-05, 145.46907, 3.938e-05]","[1.075e-05, -75.664277, 1.075e-05]","[nan, 1630.0, nan]","[nan, 0.06, nan]","[0.5, 2.3, 0.6]","[nan, nan, nan]","[nan, 0.83, nan]","[nan, nan, nan]","[nan, 0.36086956521739133, nan]","[nan, 0.062, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.13; [hs/ls]=0.63; Type ...
25,HD 88562,"[1.82e-05, 153.124761, 1.82e-05]","[1.614e-05, -15.889798, 1.614e-05]","[nan, 1445.0, nan]","[nan, 0.2, nan]","[0.1, 1.0, 0.1]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, 0.048, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.53; [hs/ls]=0.41; Type ...
26,HD 91208,"[1.563e-05, 157.888064, 1.563e-05]","[1.447e-05, -17.076536, 1.447e-05]","[nan, 1754.0, nan]","[nan, 0.17, nan]","[0.2, 2.3, 0.1]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.29565217391304355, nan]","[nan, 0.022, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.16; [hs/ls]=0.05; Type ...
27,HD 92626,"[3.227e-05, 160.208219, 3.227e-05]","[2.283e-05, -48.025103, 2.283e-05]","[nan, 918.0, nan]","[nan, 0.0, nan]","[0.6, 3.1, 0.4]","[nan, nan, nan]","[nan, 0.98, nan]","[nan, nan, nan]","[nan, 0.3161290322580645, nan]","[nan, 0.042, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.15; [hs/ls]=1.02; Type ...
28,HD 95193,"[1.882e-05, 164.861565, 1.882e-05]","[1.447e-05, -14.171594, 1.447e-05]","[nan, 1653.0, nan]","[nan, 0.13, nan]","[0.1, 2.7, 0.1]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.28148148148148144, nan]","[nan, 0.026, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.04; [hs/ls]=-0.07; Type...
29,HD 98839,"[2.274e-05, 170.706575, 2.274e-05]","[2.233e-05, 43.482698, 2.233e-05]","[nan, 16471.0, nan]","[nan, 0.56, nan]","[0.2, 4.3, 0.2]","[nan, nan, nan]","[nan, 1.0, nan]","[nan, nan, nan]","[nan, 0.23255813953488372, nan]","[nan, 0.056, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.05; [hs/ls]=0.19; Type ...
30,HD 101013,"[2.846e-05, 174.470837, 2.846e-05]","[2.258e-05, 50.618186, 2.258e-05]","[nan, 1711.0, nan]","[nan, 0.2, nan]","[0.3, 1.7, 0.3]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.4, nan]","[nan, 0.037, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.40; [hs/ls]=0.10; Type ...
31,HD 104979,"[3.519e-05, 181.302216, 3.519e-05]","[2.853e-05, 8.733019, 2.853e-05]","[nan, 19295.0, nan]","[nan, 0.08, nan]","[0.2, 2.7, 0.1]","[nan, nan, nan]","[nan, 0.75, nan]","[nan, nan, nan]","[nan, 0.27777777777777773, nan]","[nan, nan, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.26; [hs/ls]=0.31; Type ...
32,HD 107541,"[9.74e-06, 185.450318, 9.74e-06]","[5.83e-06, -34.780037, 5.83e-06]","[nan, 3570.0, nan]","[nan, 0.1, nan]","[0.1, 1.1, 0.2]","[nan, nan, nan]","[nan, 0.54, nan]","[nan, nan, nan]","[nan, 0.4909090909090909, nan]","[nan, 0.029, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.63; [hs/ls]=0.75; Type ...
33,HD 119185,"[5.16e-06, 205.489634, 5.16e-06]","[4.22e-06, -13.027725, 4.22e-06]","[nan, 22065.0, nan]","[nan, 0.6, nan]","[0.2, 1.7, 0.2]","[nan, nan, nan]","[nan, 0.57, nan]","[nan, nan, nan]","[nan, 0.3352941176470588, nan]","[nan, nan, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.42; [hs/ls]=0.32; Type ...
34,HD 121447,"[7.4e-06, 208.94569, 7.4e-06]","[6.17e-06, -18.249024, 6.17e-06]","[nan, 185.7, nan]","[nan, 0.015, nan]","[0.1, 1.6, 0.1]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.37499999999999994, nan]","[nan, 0.025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.90; [hs/ls]=0.84; Type ...
35,HD 123949,"[2.496e-05, 212.747131, 2.496e-05]","[1.669e-05, -19.143952, 1.669e-05]","[nan, 8523.0, nan]","[nan, 0.92, nan]","[0.1, 1.3, 0.3]","[nan, nan, nan]","[nan, 0.58, nan]","[nan, nan, nan]","[nan, 0.4461538461538461, nan]","[nan, 0.046, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.35; Type ...
36,HD 134698,"[5.99e-06, 227.923757, 5.99e-06]","[5.06e-06, -10.507657, 5.06e-06]","[nan, 10005.0, nan]","[nan, 0.95, nan]","[0.2, 1.5, 0.2]","[nan, nan, nan]","[nan, 0.53, nan]","[nan, nan, nan]","[nan, 0.35333333333333333, nan]","[nan, 0.054, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.57; [hs/ls]=0.02; Type ...
37,HD 139195,"[2.124e-05, 234.123225, 2.124e-05]","[2.081e-05, 10.010147, 2.081e-05]","[nan, 5324.0, nan]","[nan, 0.35, nan]","[0.1, 2.6, 0.1]","[nan, nan, nan]","[nan, 0.74, nan]","[nan, nan, nan]","[nan, 0.2846153846153846, nan]","[nan, 0.026, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.07; [hs/ls]=-0.17; Type...
38,HD 143899,"[1.636e-05, 240.932528, 1.636e-05]","[1.033e-05, -19.575203, 1.033e-05]","[nan, 1461.0, nan]","[nan, 0.19, nan]","[0.1, 2.4, 0.1]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.29583333333333334, nan]","[nan, 0.017, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.29; [hs/ls]=0.19; Type ...
39,HD 154430,"[1.757e-05, 257.226142, 1.757e-05]","[7.86e-06, -59.287852, 7.86e-06]","[nan, 1668.0, nan]","[nan, 0.11, nan]","[0.7, 2.3, 1.4]","[nan, nan, nan]","[nan, 0.81, nan]","[nan, nan, nan]","[nan, 0.35217391304347834, nan]","[nan, 0.034, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.36; [hs/ls]=0.71; Type ...
40,HD 178717,"[6.27e-06, 287.341706, 6.27e-06]","[6.33e-06, 10.241178, 6.33e-06]","[nan, 2866.0, nan]","[nan, 0.43, nan]","[0.7, 1.6, 0.9]","[nan, nan, nan]","[nan, 0.66, nan]","[nan, nan, nan]","[nan, 0.4125, nan]","[nan, 0.006, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.52; [hs/ls]=0.18; Type ...
41,HD 180622,"[1.131e-05, 289.295952, 1.131e-05]","[1.078e-05, 0.497366, 1.078e-05]","[nan, 4049.0, nan]","[nan, 0.06, nan]","[0.2, 1.8, 0.3]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.07, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.03; [hs/ls]=-0.13; Type ...
42,HD 183915,"[6.1e-06, 292.856266, 6.1e-06]","[6.36e-06, 11.627951, 6.36e-06]","[nan, 4382.0, nan]","[nan, 0.27, nan]","[0.6, 1.8, 1.0]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.3333333333333333, nan]","[nan, 7e-05, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m->s; [Fe/H]=-0.59; [hs/ls]=0.91; Ty...
43,HD 196673,"[0.00015632, 309.434684, 0.00015632]","[0.00012222, 33.366492, 0.00012222]","[nan, 7780.0, nan]","[nan, 0.59, nan]","[0.1, 5.0, 0.0]","[nan, nan, nan]","[nan, 1.1, nan]","[nan, nan, nan]","[nan, 0.22000000000000003, nan]","[nan, 0.02, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.12; [hs/ls]=0.23; Type m...
44,HD 199939,"[1.454e-05, 314.681226, 1.454e-05]","[1.047e-05, 44.414578, 1.047e-05]","[nan, 584.9, nan]","[nan, 0.28, nan]","[0.4, 2.8, 0.4]","[nan, nan, nan]","[nan, 0.93, nan]","[nan, nan, nan]","[nan, 0.3321428571428572, nan]","[nan, 0.025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.22; [hs/ls]=0.41; Type ...
45,HD 200063,"[7.83e-06, 315.266853, 7.83e-06]","[3.36e-06, 1.034923, 3.36e-06]","[nan, 1735.0, nan]","[nan, 0.07, nan]","[0.9, 2.0, 1.3]","[nan, nan, nan]","[nan, 0.64, nan]","[nan, nan, nan]","[nan, 0.32, nan]","[nan, 0.058, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.34; [hs/ls]=0.38; Type ...
46,HD 201657,"[2.283e-05, 317.639716, 2.283e-05]","[1.589e-05, 16.979567, 1.589e-05]","[nan, 1710.0, nan]","[nan, 0.17, nan]","[0.4, 1.8, 0.5]","[nan, nan, nan]","[nan, 0.7, nan]","[nan, nan, nan]","[nan, 0.38888888888888884, nan]","[nan, 0.004, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.34; [hs/ls]=0.82; Type ...
47,HD 201824,"[6.18e-06, 318.073264, 6.18e-06]","[5.64e-06, -8.356904, 5.64e-06]","[nan, 2837.0, nan]","[nan, 0.34, nan]","[0.2, 1.7, 0.4]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.4, nan]","[nan, 0.04, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.40; [hs/ls]=0.64; Type ...
48,HD 202109,"[2.575e-05, 318.234108, 2.575e-05]","[2.478e-05, 30.226899, 2.478e-05]","[nan, 6489.0, nan]","[nan, 0.22, nan]","[0.4, 3.4, 0.2]","[nan, nan, nan]","[nan, 0.87, nan]","[nan, nan, nan]","[nan, 0.25588235294117645, nan]","[nan, 0.023, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.03; [hs/ls]=-0.10; Type...
49,HD 204075,"[7.217e-05, 321.666794, 7.217e-05]","[4.614e-05, -22.41132, 4.614e-05]","[nan, 2378.0, nan]","[nan, 0.28, nan]","[0.2, 4.5, 0.3]","[nan, nan, nan]","[nan, 1.03, nan]","[nan, nan, nan]","[nan, 0.2288888888888889, nan]","[nan, 0.004, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.09; [hs/ls]=-0.43; Type...
50,HD 205011,"[9.08e-06, 322.958936, 9.08e-06]","[5.92e-06, 23.845163, 5.92e-06]","[nan, 2837.0, nan]","[nan, 0.24, nan]","[0.3, 1.8, 0.3]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.3333333333333333, nan]","[nan, 0.034, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.26; [hs/ls]=-0.02; Type...
51,HD 210946,"[1.715e-05, 333.458969, 1.715e-05]","[1.789e-05, 1.60893, 1.789e-05]","[nan, 1529.0, nan]","[nan, 0.13, nan]","[0.4, 1.8, 0.5]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.041, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.29; [hs/ls]=0.07; Type ...
52,HD 211594,"[4.018e-05, 334.562273, 4.018e-05]","[3.919e-05, -5.841626, 3.919e-05]","[nan, 1019.0, nan]","[nan, 0.06, nan]","[0.2, 2.0, 0.3]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.38, nan]","[nan, 0.014, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.29; [hs/ls]=0.75; Type ...
53,HD 218356,"[2.975e-05, 346.778091, 2.975e-05]","[1.933e-05, 25.468271, 1.933e-05]","[nan, 111.0, nan]","[nan, 0.0, nan]","[1.1, 4.3, 0.2]","[nan, nan, nan]","[nan, 1.0, nan]","[nan, nan, nan]","[nan, 0.23255813953488372, nan]","[nan, 4e-05, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.06; [hs/ls]=0.35; Type ...
54,HD 223617,"[4.184e-05, 357.778324, 4.184e-05]","[2.228e-05, 2.237851, 2.228e-05]","[nan, 1294.0, nan]","[nan, 0.06, nan]","[0.1, 1.4, 0.1]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, nan, nan]","[nan, 0.3642857142857143, nan]","[nan, 0.0064, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.20; [hs/ls]=0.14; Type ...
55,NGC 2420-173,"[5.59e-06, 114.612357, 5.59e-06]","[4.19e-06, 21.558695, 4.19e-06]","[nan, 1479.0, nan]","[nan, 0.43, nan]","[0.4, 3.0, 0.3]","[nan, nan, nan]","[nan, 0.8, nan]","[nan, nan, nan]","[nan, 0.26666666666666666, nan]","[nan, 0.008, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s->m; [Fe/H]=-0.26; [hs/ls]=-0.26; T...

## Finally convert and save your table to hdf5 format

In [9]:
# ---- Save HDF5 (triplets as datasets, rest as JSON metadata) ----
def save_triplet_columns_and_metadata(df, triplet_columns, h5_filename):
    with h5py.File(h5_filename, "w") as f:
        for col in triplet_columns:
            try:
                # Coerce to numeric triplets
                arr = np.array(df[col].tolist(), dtype=float)
                if arr.ndim != 2 or arr.shape[1] != 3:
                    raise ValueError(f"{col} is not triplets")
                f.create_dataset(col, data=arr)
            except Exception as e:
                print(f"Skipping column '{col}' due to: {e}")
        meta_cols = [c for c in df.columns if c not in triplet_columns]
        meta_json = df[meta_cols].to_json(orient="records")
        f.create_dataset("metadata_json", data=np.bytes_(meta_json))


#  Run the function with metadata saving
triplet_cols = ["RA", "Dec", "Period", "Eccentricity", "M1", "M1_sin3i", "M2", "M2_sin3i", "q", "Mass Function",]

from paths import DATA_DIR

save_triplet_columns_and_metadata(df, triplet_cols, DATA_DIR / "result_tables/barium_stars_Jorissen2019.h5")

print(f"Built {len(df)} systems and saved to barium_stars.h5")
print(df[["System Name","Period","Eccentricity","M1","M2","q","Mass Function"]].head())

Built 56 systems and saved to barium_stars.h5
   System Name              Period      Eccentricity               M1  \
0  DM -64 4333   [nan, 386.0, nan]  [nan, 0.03, nan]  [0.1, 1.4, 0.1]
1  DM -42 2048  [nan, 3260.0, nan]  [nan, 0.08, nan]  [0.5, 1.9, 0.7]
2  DM -14 2678  [nan, 3470.0, nan]  [nan, 0.22, nan]  [0.2, 3.0, 0.2]
3  DM -01 3022  [nan, 3253.0, nan]  [nan, 0.28, nan]  [0.1, 1.6, 0.1]
4      HD 5424  [nan, 1881.0, nan]  [nan, 0.23, nan]  [0.3, 1.3, 0.4]

                 M2                                q      Mass Function
0  [nan, 0.61, nan]   [nan, 0.4357142857142857, nan]  [nan, 0.068, nan]
1  [nan, 0.74, nan]   [nan, 0.3894736842105263, nan]  [nan, 0.065, nan]
2   [nan, 0.8, nan]  [nan, 0.26666666666666666, nan]  [nan, 0.023, nan]
3  [nan, 0.55, nan]              [nan, 0.34375, nan]  [nan, 0.016, nan]
4  [nan, 0.59, nan]   [nan, 0.4538461538461538, nan]  [nan, 0.005, nan]

***
***

# Now "Barium and related stars, and their white-dwarf companions  II. Main-sequence and subgiant stars"
### Escorza et al. 2019 
https://ui.adsabs.harvard.edu/abs/2019A&A...626A.128E





### Table 1

``` latex
\setlength{\tabcolsep}{3pt}
\renewcommand{\arraystretch}{1.3}
\begin{sidewaystable*}
\caption{Orbital parameters (i.e., period, $P$; eccentricity, $e$; time of periastron passage, $T\rm_0$; longitude of periastron, $\omega$; velocity semi-amplitude, $K_1$; and the systemic velocity of the system, $\gamma$) derived in this study. The mass function $f(m)$ and the apparent orbital separation $a_1\sin{i}$, which depend on $P$, $e$ and $K_1$ are also included. The last column shows the standard deviation of the residuals of the fit. In the upper part of the table, we list the 25 dwarf and subgiant Ba and CH stars that are in SB1 systems. In the bottom part, we include the orbital parameters of the inner and outer orbits of the confirmed triple system, HD\,48565 (see Sect. \ref{ssec:HD48565}), and the parameters of the constrained Ba SB2 system, HD\,114520 (see Sect. \ref{ssec:HD114520}).}\label{table_dBa}
\centering
\begin{tabular}{lcccccccccc}
\hline\hline
\rule[0mm]{0mm}{4mm}
Name & Type & Period [d] & e & T$_0$ [HJD] & $\omega$ [$^{\circ}$] & $K_{\rm{1}}$ [$\mathrm{km\,s}^{-1}$] & $\gamma$ [$\mathrm{km\,s}^{-1}$] & f(m) [M$_{\sun}$] & $a_1\sin{i}$ [AU] & $\sigma$(O-C) [$\mathrm{km\,s}^{-1}$]\\
\hline
BD-10$^\circ$4311 & sgCH & 4865 $\pm$ 20 & 0.075 $\pm$ 0.019 & 2451183 $\pm$ 2500 & 157 $\pm$ 17 & 5.29 $\pm$ 0.11 & 50.95 $\pm$ 0.08 & 0.074 $\pm$ 0.005 & 2.36 $\pm$ 0.05 & 0.48\\
BD-18$^\circ$255 & dBa & 1585 $\pm$ 6 & 0.075 $\pm$ 0.011 & 2458136 $\pm$ 730 & 124 $\pm$ 8 & 7.25 $\pm$ 0.07 & 34.65 $\pm$ 0.05 & 0.0620 $\pm$ 0.0017 & 1.053 $\pm$ 0.010 & 0.28\\
BD+18$^\circ$5215 & dBa & 1516 $\pm$ 11 & 0.13 $\pm$ 0.06 & 2447317 $\pm$ 800 & 72 $\pm$ 28 & 3.09 $\pm$ 0.16 & -30.19 $\pm$ 0.10 & 0.0045 $\pm$ 0.0007 & 0.43 $\pm$ 0.02 & 0.53\\
HD\,15306 & dBa & 8383 $\pm$ 48 & 0.20 $\pm$ 0.03 & 2448335 $\pm$ 2400 & 140 $\pm$ 16 & 3.67 $\pm$ 0.14 & 46.82 $\pm$ 0.14 & 0.040 $\pm$ 0.005 & 2.77 $\pm$ 0.11 & 0.46\\
HD\,22589 & gBa & 5573 $\pm$ 33 & 0.232 $\pm$ 0.016 & 2448567 $\pm$ 2800 & 333 $\pm$ 4 & 1.90 $\pm$ 0.03 & -27.51 $\pm$ 0.03 & 0.00367 $\pm$ 0.00018 & 0.949 $\pm$ 0.017 & 0.13\\
HD\,24864 & dBa & 430 $\pm$ 3 & 0.0 + 0.05 & 2449475 $\pm$ 600 & - $\pm$ - & 7.6 $\pm$ 0.8 & 13.1 $\pm$ 0.3 & 0.019 $\pm$ 0.005 & 0.30 $\pm$ 0.03 & 0.98\\
HD\,34654 & dBa & 975.6 $\pm$ 0.6 & 0.110 $\pm$ 0.007 & 2457161 $\pm$ 130 & 326 $\pm$ 2 & 8.90 $\pm$ 0.04 & -6.89 $\pm$ 0.02 & 0.0699 $\pm$ 0.0011 & 0.793 $\pm$ 0.004 & 0.05\\
HD\,50264 & dBa & 909.9 $\pm$ 1.2 & 0.091 $\pm$ 0.03 & 2449541 $\pm$ 60 & 230 $\pm$ 15 & 9.52 $\pm$ 0.14 & 63.27 $\pm$ 0.19 & 0.080 $\pm$ 0.003 & 0.793 $\pm$ 0.012 & 0.35\\
HD\,76225 & dBa & 2410 $\pm$ 2 & 0.098 $\pm$ 0.005 & 2451159 $\pm$ 400 & 267 $\pm$ 3 & 6.11 $\pm$ 0.04 & 30.34 $\pm$ 0.02 & 0.0561 $\pm$ 0.0010 & 1.347 $\pm$ 0.008 & 0.09\\
HD\,87080 & sgCH & 274.3 $\pm$ 1.9 & 0.161 $\pm$ 0.007 & 2448921 $\pm$ 20 & 128 $\pm$ 2 & 12.17 $\pm$ 0.07 & -2.94 $\pm$ 0.05 & 0.0492 $\pm$ 0.0008 & 0.3029 $\pm$ 0.0017 & 0.14\\
HD\,89948 & sgCH & 673 $\pm$ 3 & 0.12 $\pm$ 0.03 & 2448225 $\pm$ 300 & 135 $\pm$ 7 & 9.9 $\pm$ 0.2 & 14.91 $\pm$ 0.14 & 0.065 $\pm$ 0.005 & 0.606 $\pm$ 0.016 & 0.32\\
HD\,95241 & dBa & 5244 $\pm$ 56 & 0.82 $\pm$ 0.02 & 2450499 $\pm$ 2000 & 112 $\pm$ 3 & 4.5 $\pm$ 0.2 & -7.98 $\pm$ 0.05 & 0.0091 $\pm$ 0.0013 & 1.23 $\pm$ 0.05 & 0.2\\
HD\,98991 & dBa & 2836 $\pm$ 99 & 0.317 $\pm$ 0.008 & 2455888 $\pm$ 1400 & 25 $\pm$ 20 & 4.70 $\pm$ 0.08 & 14.06 $\pm$ 0.04 & 0.0259 $\pm$ 0.0007 & 1.16 $\pm$ 0.03 & 0.11\\
HD\,106191 & dBa & 1314 $\pm$ 13 & 0.15 $\pm$ 0.10 & 2446527 $\pm$ 1300 & 120 $\pm$ 34 & 7.1 $\pm$ 0.5 & -3.3 $\pm$ 0.2 & 0.048 $\pm$ 0.008 & 0.85 $\pm$ 0.07 & 0.58\\
HD\,107574 & dBa & 1384 $\pm$ 2 & 0.084 $\pm$ 0.004 & 2457910 $\pm$ 160 & 218 $\pm$ 4 & 2.238 $\pm$ 0.009 & -28.579 $\pm$ 0.008 & 0.00159 $\pm$ 0.00002 & 0.284 $\pm$ 0.002 & 0.05\\
HD\,120620 & gBa & 217.2 $\pm$ 1.0 & 0.0 + 0.05 & 2456980 $\pm$ 100 & - $\pm$ - & 14.02 $\pm$ 0.16 & 33.56 $\pm$ 0.13 & 0.062 $\pm$ 0.002 & 0.280 $\pm$ 0.004 & 0.401\\
HD\,123585 & sgCH & 459.4 $\pm$ 1.5 & 0.0 + 0.05 & 2448419 $\pm$ 500 & - $\pm$ - & 11.7 $\pm$ 0.2 & 25.49 $\pm$ 0.17 & 0.077 $\pm$ 0.004 & 0.496 $\pm$ 0.008 & 0.49\\ 
HD\,127392 & sgCH & 1508 $\pm$ 2 & 0.093 $\pm$ 0.010 & 2448739 $\pm$ 700 & 1711 $\pm$ 10 & 8.25 $\pm$ 0.09 & -64.21 $\pm$ 0.07 & 0.087 $\pm$ 0.003 & 1.14 $\pm$ 0.02 & 0.17\\
HD\,141804 & sgCH & 2652 $\pm$ 95 & 0.0 + 0.05 & 2449979 $\pm$ 1500 & - $\pm$ - & 6.28 $\pm$ 0.16 & -49.3 $\pm$ 0.2 & 0.068 $\pm$ 0.007 & 1.531 $\pm$ 0.09 & 0.20\\ 
HD\,147609 & dBa & 1146.2 $\pm$ 1.5 & 0.058 $\pm$ 0.005 & 2455716 $\pm$ 130 & 123 $\pm$ 5 & 2.974 $\pm$ 0.016 & -16.277 $\pm$ 0.009 & 0.00310 $\pm$ 0.00005 & 0.3128 $\pm$ 0.0016 & 0.057\\
HD\,150862 & sgCH & 291 $\pm$ 4 & 0.28 $\pm$ 0.09 & 2448733 $\pm$ 100 & 299 $\pm$ 21 & 12 $\pm$ 2 & -82.1 $\pm$ 0.7 & 0.045 $\pm$ 0.003 & 0.305 $\pm$ 0.009 & 0.15\\
HD\,182274 & sgCH & 8231 $\pm$ 54 & 0.0 + 0.05 & 2451522 $\pm$ 3000 & - $\pm$ - & 2.99 $\pm$ 0.16 & -16.34 $\pm$ 0.19 & 0.0227 $\pm$ 0.005 & 2.26 $\pm$ 0.12 & 0.24\\
HD\,207585 & sgCH & 672 $\pm$ 2 & 0.0 + 0.05 & 2452172 $\pm$ 500 & - $\pm$ - & 10.4 $\pm$ 0.3 & -62.3 $\pm$ 0.2 & 0.078 $\pm$ 0.007 & 0.641 $\pm$ 0.018 & 0.73\\
HD\,216219 & gBa & 4117 $\pm$ 122 & 0.0 + 0.05 & 2456272 $\pm$ 2000 & - $\pm$ - & 2.98 $\pm$ 0.10 & -6.82 $\pm$ 0.10 & 0.0113 $\pm$ 0.0013 & 1.13 $\pm$ 0.05 & 0.383\\
HD\,221531 & dBa & 1399 $\pm$ 3 & 0.163 $\pm$ 0.007 & 2456940 $\pm$ 81 & 184 $\pm$ 4 & 6.44 $\pm$ 0.04 & 2.82 $\pm$ 0.02 & 0.0372 $\pm$ 0.0007 & 0.818 $\pm$ 0.006 & 0.14\\
\hline\hline
\rule[0mm]{0mm}{4mm}
Name & Type & Period [d] & e & T$_0$ [HJD] & $\omega$ [$^{\circ}$] & $K_{\rm{i}}$ [$\mathrm{km\,s}^{-1}$] & $\gamma$ [$\mathrm{km\,s}^{-1}$] & f(m) [M$_{\sun}$] & $a_{\rm{i}}\sin{i}$ [AU] & $\sigma$(O-C) [$\mathrm{km\,s}^{-1}$]\\
\hline
HD\,48565$_{\rm{in}}$ & Trip. & 73.344 $\pm$ 0.013 & 0.220 $\pm$ 0.007 & 2446943 $\pm$ 2 & 214 $\pm$ 3 & 9.17 $\pm$ 0.06 & - & 0.00542 $\pm$ 0.00010 & 0.0603 $\pm$ 0.0004 & 1.41\\
HD\,48565$_{\rm{out}}$ & Trip. & 10\,531 $\pm$ 210 & 0.37 $\pm$ 0.06 & 2464195 $\pm$ 120 & 222 $\pm$ 5 & 3.9 $\pm$ 0.2 & -21.01 $\pm$ 0.12 & 0.053 $\pm$ 0.003 & 3.5 $\pm$ 0.3 & 0.31\\
HD\,114520a & SB2 & 437.94 $\pm$ 0.18 & 0.523 $\pm$ 0.003 & 2456152 $\pm$ 2 & 249.7 $\pm$ 0.5 & 12.41 $\pm$ 0.06 & -9.07 $\pm$ 0.03 & 0.054 $\pm$ 0.002 & 0.426 $\pm$ 0.005 & 0.11\\
HD\,114520b & SB2 & " & " & " & " & -17.02 $\pm$ 0.12 & " & " & -0.138 $\pm$ 0.015 & 0.75\\
\hline\hline
\end{tabular}
\end{sidewaystable*}

```






### Table 3


``` latex
\begin{table*}[t] 
\begin{small}
\caption{Effective temperature ($T_{\rm eff}$), surface gravity (log$g$), metallicity ([Fe/H]), and microturbulence velocity ($\xi$) of the objects with a determined orbit. Column 7 gives the reference of the adopted stellar parameters when no HERMES spectra were available. Column 8 gives the line-of-sight extinction, and columns 9 and 10 list the derived luminosities and masses.
\textbf{References for the spectroscopic stellar parameters:} L\&B91: \citet{LuckBond91}; K+13: \citet{Kordopatis13}; K\&G14: \citet{Karinkuzhi14}; P\&J03: \citet{PereiraJunqueira03}; N+94: \citet{North94}.}
\label{params}
\begin{center}
\begin{tabular}{lccccccccc}
\hline\hline
\rule[0mm]{0mm}{4mm}
Name & Type & $T_{\rm eff}$ [K] & log$g$ [dex] & [Fe/H] [dex] & $\xi$ [$\mathrm{km\,s}^{-1}$] & Ref. & E(B-V) & L/L$_{\sun}$ & M/M$_{\sun}$\\
\hline
BD-10$^\circ$4311 & sgCH & 5858 $\pm$ 50 & 3.9 $\pm$ 0.3 & -0.65 $\pm$ 0.10 & 1.25 $\pm$ 0.07 & This work & 0.042 $\pm$ 0.015 & 1.99 $\pm$ 0.05 & 0.80 $\pm$ 0.10 \\
BD-18$^\circ$255 & dBa & 6800 $\pm$ 400 & 4.3 $\pm$ 0.3 & -0.18 $\pm$ 0.05 & 2.4 $\pm$ 0.5 & L\&B91 & 0.015 $\pm$ 0.005 & 4.2 $\pm$ 1.2 & 1.30 $\pm$ 0.15\\
BD+18$^\circ$5215 & dBa & 6452 $\pm$ 50 & 4.4 $\pm$ 0.4 & -0.50 $\pm$ 0.09 & 0.82 $\pm$ 0.09 & This work & 0.014 $\pm$ 0.007 & 1.86 $\pm$ 0.11 & 1.10 $\pm$ 0.10\\
HD\,15306 & dBa & 6898 $\pm$ 50 & 3.8 $\pm$ 0.2 & -0.40 $\pm$ 0.14 & 0.9 $\pm$ 0.3 & This work & 0.037 $\pm$ 0.007 & 8.7 $\pm$ 2.3 & 1.30 $\pm$ 0.10 \\
HD\,22589 & gBa & 5672 $\pm$ 56 & 3.9 $\pm$ 0.2 & -0.07 $\pm$ 0.09 & 1.20 $\pm$ 0.04 & This work & 0.048 $\pm$ 0.008 & 6.9 $\pm$ 0.8 & 1.30 $\pm$ 0.10 \\
HD\,24864 & dBa & 6337 $\pm$ 95 & 3.82 $\pm$ 0.18 & 0.0 $\pm$ 0.11 & 1.0 $\pm$ 1.0 & K+13 & 0.0 + 0.005 & 9.2 $\pm$ 0.6 & 1.38 $\pm$ 0.06\\
HD\,34654 & dBa & 6174 $\pm$ 50 & 4.4 $\pm$ 0.3 & -0.09 $\pm$ 0.07 & 1.36 $\pm$ 0.04 & This work & 0.012 $\pm$ 0.008 & 1.8 $\pm$ 0.3 & 1.19 $\pm$ 0.05 \\
HD\,48565 & dBa & 6030 $\pm$ 100 & 3.8 $\pm$ 0.3 & -0.6 $\pm$ 0.3 & 1.3 $\pm$ 0.3 & K\&G14 & 0.018 $\pm$ 0.010 & 2.8 $\pm$ 0.3 & 0.92 $\pm$ 0.05 \\
HD\,50264 & dBa & 5800 $\pm$ 100 & 4.2 $\pm$ 0.2 & -0.34 $\pm$ 0.08 & 1.0 $\pm$ 0.3 & P\&J03 & 0.002 $\pm$ 0.010 & 0.89 $\pm$ 0.08 & 0.90 $\pm$ 0.10\\
HD\,76225 & dBa & 6340 $\pm$ 50 & 3.9 $\pm$ 0.2 & -0.37 $\pm$ 0.08 & 1.30 $\pm$ 0.06 & This work & 0.053 $\pm$ 0.010 & 5.9 $\pm$ 0.7 & 1.21 $\pm$ 0.06 \\
HD\,87080 & sgCH & 5483 $\pm$ 50 & 3.6 $\pm$ 0.3 & -0.60 $\pm$ 0.08 & 1.20 $\pm$ 0.04 & This work & 0.028 $\pm$ 0.012 & 12.5 $\pm$ 0.8 & 1.6 $\pm$ 0.2\\
HD\,89948 & sgCH & 6000 $\pm$ 400 & 4.0 $\pm$ 0.3 & -0.13 $\pm$ 0.05 & 1.8 $\pm$ 0.5 & L\&B91 & 0.0 $\pm$ 0.003 & 1.36 $\pm$ 0.07 & 0.95 $\pm$ 0.08\\
HD\,95241 & dBa & 5837 $\pm$ 50 & 3.6 $\pm$ 0.2 & -0.37 $\pm$ 0.07 & 1.36 $\pm$ 0.04 & This work & 0.0 + 0.008 & 7.8 $\pm$ 0.8 & 1.30 $\pm$ 0.10 \\
HD\,98991 & dBa & 6388 $\pm$ 50 & 2.7 $\pm$ 0.4 & -0.44 $\pm$ 0.08 & 0.07$^{(1)}$ & This work & 0.0 + 0.014 & 14.7 $\pm$ 1.0 & 1.45 $\pm$ 0.08 \\
HD\,106191 & dBa & 5946 $\pm$ 50 & 4.3 $\pm$ 0.4 & -0.29 $\pm$ 0.10 & 1.21 $\pm$ 0.06 & This work & 0.010 $\pm$ 0.010 & 2.0 $\pm$ 0.2 & 0.95 $\pm$ 0.05 \\
HD\,107574 & dBa & 6340 $\pm$ 100 & 3.6 $\pm$ 0.5 & -0.80 $\pm$ 0.25 & 1.8 $\pm$ 0.3 & N+94 & 0.0 + 0.005 & 5.6 $\pm$ 0.2 & 1.11 $\pm$ 0.05 \\
HD\,120620 & gBa & 4831 $\pm$ 50 & 3.0 $\pm$ 0.3 & -0.29 $\pm$ 0.10 & 1.11 $\pm$ 0.05 & This work & 0.055 $\pm$ 0.013 & 12.2 $\pm$ 1.6 & 1.2 $\pm$ 0.2 \\
HD\,123585 & sgCH & 6047 $\pm$ 100 & 3.5 $\pm$ 0.5 & -0.50 $\pm$ 0.25 & 1.8 $\pm$ 0.3 & N+94 & 0.054 $\pm$ 0.012 & 3.5 $\pm$ 1.0 & 1.00 $\pm$ 0.10\\ 
HD\,127392 & sgCH & 5600 $\pm$ 300 & 3.9 $\pm$ 0.3 & -0.52 $\pm$ 0.05 & 2.6 $\pm$ 0.5 & L\&B91 & 0.011 $\pm$ 0.011 & 0.98 $\pm$ 0.13 & 0.8 $\pm$ 0.3\\
HD\,141804 & sgCH & 6000 $\pm$ 400 & 3.5 $\pm$ 0.3 & -0.41 $\pm$ 0.05 & 1.7 $\pm$ 0.5 & L\&B91 & 0.0 + 0.003 & 1.77 $\pm$ 0.07 & 0.9 $\pm$ 0.2 \\ 
HD\,147609 & dBa & 6411 $\pm$ 50 & 3.9 $\pm$ 0.5 & -0.23 $\pm$ 0.09 & 1.26 $\pm$ 0.07 & This work & 0.044 $\pm$ 0.007 & 10.2 $\pm$ 1.3 & 1.40 $\pm$ 0.10\\
HD\,150862 & sgCH & 6182 $\pm$ 50 & 4.1 $\pm$ 0.3 & -0.33 $\pm$ 0.08 & 0.94 $\pm$ 0.06 & This work & 0.006 $\pm$ 0.006 & 2.2 $\pm$ 0.2 & 1.04 $\pm$ 0.05\\
HD\,182274 & sgCH & 6327 $\pm$ 50 & 4.3 $\pm$ 0.2 & -0.32 $\pm$ 0.09 & 1.05 $\pm$ 0.06 & This work & 0.012 $\pm$ 0.007 & 2.06 $\pm$ 0.14 & 1.09 $\pm$ 0.05 \\
HD\,207585 & sgCH & 5400 $\pm$ 300 & 3.3 $\pm$ 0.3 & -0.57 $\pm$ 0.05 & 1.8 $\pm$ 0.5 & L\&B91 & 0.0 + 0.003 & 3.8 $\pm$ 0.8 & 0.96 $\pm$ 0.15\\
HD\,216219 & gBa & 5900 $\pm$ 50 & 3.6 $\pm$ 0.3 & -0.17 $\pm$ 0.08 & 1.42 $\pm$ 0.04 & This work & 0.042 $\pm$ 0.009 & 9.9 $\pm$ 0.8 & 1.45 $\pm$ 0.10\\
HD\,221531 & dBa & 6460 $\pm$ 100 & 4.2 $\pm$ 0.5 & -0.30 $\pm$ 0.25 & 2.4 $\pm$ 0.3 & N+94 & 0.0 + 0.004 & 4.7 $\pm$ 1.4 & 1.20 $\pm$ 0.10\\
\hline\hline
\end{tabular}
\end{center}
\end{small}
\tablefoot{$^{(1)}$ Uncertain value due to the low signal-to-noise ratio of the spectrum around Fe lines.}
\end{table*}
```


### Table 4

``` latex
\begin{table}[t] 
\begin{small}
\caption{Parallaxes and orbital inclinations from the combination of spectroscopic parameters and Hipparcos astrometric data and companion masses of the Ba and CH stars that passed the tests presented in \cite{Pourbaix01} and \cite{Jancart05}. }
\label{WD}
\begin{center}
\begin{tabular}{lccc}
\hline
\rule[0mm]{0mm}{4mm}
ID & $\varpi$ [mas] & Inclination [$^{\circ}$] & Companion mass [M$_{\sun}$]\\
\hline
HD\,34654 & 21.5 $\pm$ 1.0 & 80 $\pm$ 4 & 0.621 $\pm$ 0.018\\
HD\,50264 & 14.1 $\pm$ 1.1 & 109 $\pm$ 5 & 0.60 $\pm$ 0.05\\ 
HD\,89948 & 23.9 $\pm$ 0.8 & 102 $\pm$ 3 & 0.54 $\pm$ 0.03\\
HD\,123585 & 9.5 $\pm$ 1.7 & 64 $\pm$ 13 & 0.66 $\pm$ 0.11\\
\hline
\end{tabular}
\end{center}
\end{small}
\end{table}
```