# Compiling Algol (semi-detached) systems 
## from Malkov 2020

based on 
### "Semidetached double-lined eclipsing binaries: Stellar parameters and rare classes "
Malkov 2020
 https://ui.adsabs.harvard.edu/abs/2020MNRAS.491.5489M/abstract



*** 
From Malkov (2020MNRAS.491.5489M): 

The well-known Catalogue of Algol-Type Binary Stars \cite{2004A&A...417..263B} lists 411 Semi detached stars, however, the majority of those stars are drawn from the \cite{1980AcA....30..501B} and \cite{2004yCat.5124....0S} catalogues which only contain approximate data. Lastly \cite{2004yCat.5115....0S} provide parameters for 96 semi-detached binaries.

\cite{2020MNRAS.491.5489M} makes a new comprehensive list of semi-detached binaries with reliable absolute parameters containing 119 semidetached double-lined eclipsing binaries containing the orbital parameters and physical parameters of the components.

In [9]:
import numpy as np
import pandas as pd
import h5py
import json
import sys

from astroquery.vizier import Vizier

# Ensure project root is on sys.path so `import paths` finds the top-level paths.py
import os, sys
from pathlib import Path
proj_root = Path('/Users/liekevanson/Documents/Projects/post_mt_review').resolve()
if str(proj_root) not in sys.path:
    sys.path.insert(0, str(proj_root))

from paths import DATA_DIR

## Helper functions to build the h5 table in consistent format

In [10]:
# ---- helper functions ----
columns = [
    "System Name", "RA", "Dec", "Period", "Eccentricity",
    "M1","M1_sin3i", "M2", "M2_sin3i", "q", "Mass Function",
    "Type1", "Type2", "Detection Method", "Reference", "Notes"
]
df = pd.DataFrame(columns=columns)

def add_observation(df, system_name,
                    ra, dec, period, ecc,
                    m1, m1_sin3i, m2, m2_sin3i, q, mass_func,
                    type1, type2, method, reference, notes=""):
    new_row = {
        "System Name": system_name,
        "RA": ra,
        "Dec": dec,
        "Period": period,
        "Eccentricity": ecc,
        "M1": m1,
        "M1_sin3i": m1_sin3i,
        "M2": m2,
        "M2_sin3i": m2_sin3i,
        "q": q,
        "Mass Function": mass_func,
        "Type1": type1,
        "Type2": type2,
        "Detection Method": method,
        "Reference": reference,
        "Notes": notes,
    }
    return pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

TRI_NAN = [np.nan, np.nan, np.nan]

# ---- Parsing utilities (robust to odd TeX) ----
def clean_cell(s: str) -> str:
    s = s.strip()
    # join broken "NGC \\ \n 2420-173" cases in pre-pass
    return s

def to_float_or_nan(s: str) -> float | float:
    t = s.strip()
    t = t.replace(',', '')  # just in case
    # remove TeX wrappers
    t = re.sub(r"[${}\\]", "", t)
    t = t.replace(r"\,", "")
    t = t.replace(r"\cdot", "")
    t = t.replace("–", "-").replace("—", "-")
    # blanks or dashes
    if t == "" or t == "-" or t == "–":
        return np.nan
    # sometimes "0." appears; that's fine
    try:
        return float(t)
    except Exception:
        # pick the first number found (handles things like '0.' or '7E-05')
        m = re.search(r"[-+]?\d+(?:\.\d+)?(?:[Ee][-+]?\d+)?", t)
        return float(m.group(0)) if m else np.nan

def parse_asym_mass_triplet(s: str):
    """
    Parse M_Ba field like:
      '1.9$+0.7\\atop-0.5$'  → [0.5, 1.9, 0.7]
      '{\\sl 1.3}$+0.3\\atop-0.2$' → [0.2, 1.3, 0.3]
      '2.3$+1.4\\atop-0.7$' → [0.7, 2.3, 1.4]
      '1.6' → [nan, 1.6, nan]
    """
    t = s.strip()
    # keep a copy for fallback
    # normalize: turn "\atop" into a separator, strip TeX, keep signs
    t = t.replace("\\,", "")
    t = t.replace("\\atop", "|")
    t = re.sub(r"{\\sl\s*", "", t)       # drop slanted markup start
    t = t.replace("{", "").replace("}", "")
    t = t.replace("$", "")
    t = t.replace("\\", "")
    # extract numbers (value, +err, -err)
    nums = re.findall(r"[-+]?\d+(?:\.\d+)?(?:[Ee][-+]?\d+)?", t)
    if len(nums) >= 3:
        val = float(nums[0])
        plus = abs(float(nums[1]))
        minus = abs(float(nums[2]))
        return [minus, val, plus]
    elif len(nums) >= 1:
        val = float(nums[0])
        return [np.nan, val, np.nan]
    else:
        return TRI_NAN.copy()

def as_triplet_val(x):
    """Value only → [nan, value, nan] triplet."""
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return TRI_NAN.copy()
    try:
        v = float(x)
        return [np.nan, v, np.nan]
    except Exception:
        return TRI_NAN.copy()

def cleanup_name(cell0: str) -> str:
    """
    Turn the 'HD/DM' cell into a clean System Name:
     - ' 5424'  → 'HD 5424'
     - '$-64^\\circ$4333' → 'DM -64 4333'
     - 'NGC 2420-173' → as-is
    """
    raw = cell0.strip()
    # join DM pattern like $-64^\circ$4333
    m = re.match(r"\s*\$?\s*([+\-]?\d+)\s*\^\s*\\?circ\s*\$?\s*(\d+)", raw)
    if m:
        deg, num = m.group(1), m.group(2)
        return f"DM {deg} {num}"
    # strip TeX
    s = re.sub(r"[${}\\]", "", raw)
    s = s.replace("^circ", "")
    s = s.replace("^\circ", "")
    s = re.sub(r"\s+", " ", s).strip()
    if s.upper().startswith("NGC"):
        return s.replace(" \\\\", "").strip()
    # pure number → HD
    if re.fullmatch(r"\d+", s):
        return f"HD {s}"
    return s

def parse_ba_class(cell: str) -> str:
    # e.g., 'm', 's', 'm$\rightarrow$s'
    t = cell.strip()
    t = t.replace("$", "").replace("\\rightarrow", "->")
    return re.sub(r"\s+", "", t)


# ---- Save HDF5 (triplets as datasets, rest as JSON metadata) ----
def save_triplet_columns_and_metadata(df, triplet_columns, h5_filename):
    with h5py.File(h5_filename, "w") as f:
        for col in triplet_columns:
            try:
                # Coerce to numeric triplets
                arr = np.array(df[col].tolist(), dtype=float)
                if arr.ndim != 2 or arr.shape[1] != 3:
                    raise ValueError(f"{col} is not triplets")
                f.create_dataset(col, data=arr)
            except Exception as e:
                print(f"Skipping column '{col}' due to: {e}")
        meta_cols = [c for c in df.columns if c not in triplet_columns]
        meta_json = df[meta_cols].to_json(orient="records")
        f.create_dataset("metadata_json", data=np.bytes_(meta_json))


#  Run the function with metadata saving
triplet_cols = ["RA", "Dec", "Period", "Eccentricity", "M1", "M1_sin3i", "M2", "M2_sin3i", "q", "Mass Function",]

In [11]:

def symerr_to_triplet(val, err):
    """Convert (val, symmetric_err) -> [err, val, err] with NaNs handled."""
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return TRI_NAN.copy()
    if err is None or (isinstance(err, float) and np.isnan(err)):
        return [np.nan, float(val), np.nan]
    return [abs(float(err)), float(val), abs(float(err))]

def build_algols_malkov2020_h5(df_out_path):
    # VizieR config: get *all* rows, choose only columns we need
    Vizier.ROW_LIMIT = -1

    # Table metadata (from VizieR):
    # - GCVS : system name
    # - Per  : orbital period [days]
    # - M1, e_M1 ; M2, e_M2
    # - SpType
    # - BibCode (reference for that system’s parameters)
    # - _RA, _DE (coords from SIMBAD, injected by VizieR)
    # :contentReference[oaicite:2]{index=2}
    cols = ["GCVS", "Per", "M1", "e_M1", "M2", "e_M2", "SpType", "BibCode", "_RA", "_DE"]

    cat = "J/MNRAS/491/5489"
    tab = "tablea1"

    tables = Vizier(columns=cols).get_catalogs(f"{cat}/{tab}")
    if len(tables) == 0:
        raise RuntimeError("No tables returned from VizieR. Check catalog/table name.")
    t = tables[0].to_pandas()

    # Prepare your dataframe
    columns = [
        "System Name", "RA", "Dec", "Period", "Eccentricity",
        "M1","M1_sin3i", "M2", "M2_sin3i", "q", "Mass Function",
        "Type1", "Type2", "Detection Method", "Reference", "Notes"
    ]
    df = pd.DataFrame(columns=columns)

    for _, row in t.iterrows():
        name = str(row["GCVS"]).strip() if pd.notna(row["GCVS"]) else ""
        if name == "" or name.lower() == "nan":
            # fallback: if any row lacks GCVS name, you can use another identifier,
            # but for this table GCVS is the primary.
            continue

        # Coordinates in degrees from SIMBAD
        ra_trip = as_triplet_val(row["_RA"])   # deg
        de_trip = as_triplet_val(row["_DE"])   # deg

        # Period (days)
        per_trip = as_triplet_val(row["Per"])

        # Eccentricity is NOT in this table → leave NaN triplet
        ecc_trip = TRI_NAN.copy()

        # Masses with symmetric errors
        m1_trip = symerr_to_triplet(row["M1"], row["e_M1"])
        m2_trip = symerr_to_triplet(row["M2"], row["e_M2"])

        # No sin^3 i products in this catalog (these are EB+SB2 physical masses)
        m1_sin3i = TRI_NAN.copy()
        m2_sin3i = TRI_NAN.copy()

        # Mass ratio
        if pd.notna(row["M1"]) and pd.notna(row["M2"]) and float(row["M1"]) != 0.0:
            q_val = float(row["M2"]) / float(row["M1"])
            q_trip = as_triplet_val(q_val)
        else:
            q_trip = TRI_NAN.copy()

        # Mass function not provided
        mf_trip = TRI_NAN.copy()

        # Types: you can keep spectral type as Type1 and leave Type2 blank,
        # or parse "B5+K3III" into two components.
        # Here: keep raw SpType in Type1 for now.
        sptype = str(row["SpType"]).strip() if pd.notna(row["SpType"]) else ""
        type1 = sptype
        type2 = ""

        # Detection method: this catalog is semidetached, *double-lined eclipsing binaries*
        method = "Eclipsing binary (phot) + SB2 (spec)"

        # Reference: per-row BibCode exists in the table
        ref = str(row["BibCode"]).strip() if pd.notna(row["BibCode"]) else "2020MNRAS.491.5489M"

        df = add_observation(
            df, system_name=name,
            ra=ra_trip, dec=de_trip, period=per_trip, ecc=ecc_trip,
            m1=m1_trip, m1_sin3i=m1_sin3i, m2=m2_trip, m2_sin3i=m2_sin3i,
            q=q_trip, mass_func=mf_trip,
            type1=type1, type2=type2,
            method=method, reference=ref,
            notes=""
        )

    # Save in your format
    triplet_cols = ["RA", "Dec", "Period", "Eccentricity", "M1", "M1_sin3i",
                    "M2", "M2_sin3i", "q", "Mass Function"]

    save_triplet_columns_and_metadata(df, triplet_cols, df_out_path)
    print(f"Built {len(df)} systems and saved to {df_out_path}")
    print(df[["System Name","Period","Eccentricity","M1","M2","q","Mass Function"]].head())

    return df

In [12]:
# Example usage:
from paths import DATA_DIR
out = DATA_DIR / "result_tables/Algols_Malkov2020.h5"
df = build_algols_malkov2020_h5(out)

Built 50 systems and saved to /Users/liekevanson/Documents/Projects/post_mt_review/data/result_tables/Algols_Malkov2020.h5
  System Name                  Period     Eccentricity  \
0      TW And  [nan, 4.12276035, nan]  [nan, nan, nan]
1      WW And    [nan, 23.28525, nan]  [nan, nan, nan]
2      RY Aqr   [nan, 1.9665826, nan]  [nan, nan, nan]
3      XZ Aql    [nan, 2.139181, nan]  [nan, nan, nan]
4      KO Aql    [nan, 2.864055, nan]  [nan, nan, nan]

                                                  M1  \
0                      [nan, 1.684999942779541, nan]
1  [0.09000000357627869, 3.180000066757202, 0.090...
2  [0.07000000029802322, 1.2699999809265137, 0.07...
3  [0.14000000059604645, 2.4200000762939453, 0.14...
4  [0.05000000074505806, 2.5299999713897705, 0.05...

                                                  M2  \
0                    [nan, 0.32499998807907104, nan]
1  [0.09000000357627869, 0.5099999904632568, 0.09...
2  [0.019999999552965164, 0.25999999046325684, 0....
3  [0.05999999865889549, 0.44999998807907104, 0.0...
4  [0.009999999776482582, 0.550000011920929, 0.00...

                                 q    Mass Function
0  [nan, 0.19287833775409974, nan]  [nan, nan, nan]
1  [nan, 0.16037735212481558, nan]  [nan, nan, nan]
2   [nan, 0.2047244050142244, nan]  [nan, nan, nan]
3   [nan, 0.1859504024347856, nan]  [nan, nan, nan]
4  [nan, 0.21739131151800167, nan]  [nan, nan, nan]

### Inspect table before continuing

In [13]:
display(df)

# ## Turns out the HD/DM headers are accidentally taken in as data rows.
# ## Lets remove them.
# no_header_bool = df['System Name'] != 'HD/DM'

# df = df[no_header_bool].reset_index(drop=True)

# display(df)

,System Name,RA,Dec,Period,Eccentricity,M1,M1_sin3i,M2,M2_sin3i,q,Mass Function,Type1,Type2,Detection Method,Reference,Notes
0,TW And,"[nan, 0.82595, nan]","[nan, 32.84586, nan]","[nan, 4.12276035, nan]","[nan, nan, nan]","[nan, 1.684999942779541, nan]","[nan, nan, nan]","[nan, 0.32499998807907104, nan]","[nan, nan, nan]","[nan, 0.19287833775409974, nan]","[nan, nan, nan]",FV+KIV,,Eclipsing binary (phot) + SB2 (spec),2014AN....335.1064M,
1,WW And,"[nan, 356.22311, nan]","[nan, 45.68651, nan]","[nan, 23.28525, nan]","[nan, nan, nan]","[0.09000000357627869, 3.180000066757202, 0.090...","[nan, nan, nan]","[0.09000000357627869, 0.5099999904632568, 0.09...","[nan, nan, nan]","[nan, 0.16037735212481558, nan]","[nan, nan, nan]",A5+F3p,,Eclipsing binary (phot) + SB2 (spec),2012NewA...17..691S,
2,RY Aqr,"[nan, 320.06675, nan]","[nan, -10.80226, nan]","[nan, 1.9665826, nan]","[nan, nan, nan]","[0.07000000029802322, 1.2699999809265137, 0.07...","[nan, nan, nan]","[0.019999999552965164, 0.25999999046325684, 0....","[nan, nan, nan]","[nan, 0.2047244050142244, nan]","[nan, nan, nan]",A7+G8III,,Eclipsing binary (phot) + SB2 (spec),2016AJ....152...26M,
3,XZ Aql,"[nan, 305.55566, nan]","[nan, -7.35096, nan]","[nan, 2.139181, nan]","[nan, nan, nan]","[0.14000000059604645, 2.4200000762939453, 0.14...","[nan, nan, nan]","[0.05999999865889549, 0.44999998807907104, 0.0...","[nan, nan, nan]","[nan, 0.1859504024347856, nan]","[nan, nan, nan]",A2,,Eclipsing binary (phot) + SB2 (spec),2016AJ....152...33Z,
4,KO Aql,"[nan, 281.79476, nan]","[nan, 10.76368, nan]","[nan, 2.864055, nan]","[nan, nan, nan]","[0.05000000074505806, 2.5299999713897705, 0.05...","[nan, nan, nan]","[0.009999999776482582, 0.550000011920929, 0.00...","[nan, nan, nan]","[nan, 0.21739131151800167, nan]","[nan, nan, nan]",AV+[G8IV],,Eclipsing binary (phot) + SB2 (spec),2007MNRAS.379.1533S,
5,QS Aql,"[nan, 295.27303, nan]","[nan, 13.81568, nan]","[nan, 2.513294, nan]","[nan, nan, nan]","[0.09000000357627869, 4.070000171661377, 0.090...","[nan, nan, nan]","[0.05000000074505806, 1.4900000095367432, 0.05...","[nan, nan, nan]","[nan, 0.3660933529957381, nan]","[nan, nan, nan]",B5V+[A8IV],,Eclipsing binary (phot) + SB2 (spec),2017AJ....153...36Z,
6,V337 Aql,"[nan, 286.04247, nan]","[nan, -2.02974, nan]","[nan, 2.7338794, nan]","[nan, nan, nan]","[0.3100000023841858, 17.440000534057617, 0.310...","[nan, nan, nan]","[0.18000000715255737, 7.829999923706055, 0.180...","[nan, nan, nan]","[nan, 0.44896787178505404, nan]","[nan, nan, nan]",B0V+B3V,,Eclipsing binary (phot) + SB2 (spec),2014NewA...28...44T,
7,TT Aur,"[nan, 77.4262, nan]","[nan, 39.58632, nan]","[nan, 1.332735, nan]","[nan, nan, nan]","[nan, 8.100000381469727, nan]","[nan, nan, nan]","[nan, 5.400000095367432, nan]","[nan, nan, nan]","[nan, 0.6666666470437392, nan]","[nan, nan, nan]",B2V+B4,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
8,IM Aur,"[nan, 78.87393, nan]","[nan, 46.40596, nan]","[nan, 1.24728912, nan]","[nan, nan, nan]","[nan, 2.380000114440918, nan]","[nan, nan, nan]","[nan, 0.7699999809265137, nan]","[nan, nan, nan]","[nan, 0.32352938819391325, nan]","[nan, nan, nan]",B7V+A5V,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
9,IU Aur,"[nan, 81.96836, nan]","[nan, 34.78287, nan]","[nan, 1.8114743, nan]","[nan, nan, nan]","[0.07999999821186066, 11.989999771118164, 0.07...","[nan, nan, nan]","[0.03999999910593033, 6.070000171661377, 0.039...","[nan, nan, nan]","[nan, 0.5062552366583823, nan]","[nan, nan, nan]",O9.5V+B0.5IV-V,,Eclipsing binary (phot) + SB2 (spec),2009ASPC..404..178S,
10,Y Cam,"[nan, 115.29585, nan]","[nan, 76.07391, nan]","[nan, 3.305689, nan]","[nan, nan, nan]","[0.09000000357627869, 2.0799999237060547, 0.09...","[nan, nan, nan]","[0.029999999329447746, 0.47999998927116394, 0....","[nan, nan, nan]","[nan, 0.23076923407570157, nan]","[nan, nan, nan]",A7V+gK5,,Eclipsing binary (phot) + SB2 (spec),2015AJ....150..131H,
11,S Cnc,"[nan, 130.9839, nan]","[nan, 19.03418, nan]","[nan, 9.4845011, nan]","[nan, nan, nan]","[nan, 2.3299999237060547, nan]","[nan, nan, nan]","[nan, 0.18000000715255737, nan]","[nan, nan, nan]","[nan, 0.07725322448348097, nan]","[nan, nan, nan]",B9.5V+G8IV,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
12,RZ Cnc,"[nan, 129.78558, nan]","[nan, 31.79568, nan]","[nan, 21.642998, nan]","[nan, nan, nan]","[0.15000000596046448, 3.200000047683716, 0.150...","[nan, nan, nan]","[0.05000000074505806, 0.5400000214576721, 0.05...","[nan, nan, nan]","[nan, 0.1687500041909515, nan]","[nan, nan, nan]",K0-2III+K4,,Eclipsing binary (phot) + SB2 (spec),1976ApJ...208..142P,
13,R CMa,"[nan, 109.86741, nan]","[nan, -16.39525, nan]","[nan, 1.1359405, nan]","[nan, nan, nan]","[0.07999999821186066, 1.6699999570846558, 0.07...","[nan, nan, nan]","[0.07000000029802322, 0.2199999988079071, 0.07...","[nan, nan, nan]","[nan, 0.13173652961762014, nan]","[nan, nan, nan]",F1V+G8IV,,Eclipsing binary (phot) + SB2 (spec),2011MNRAS.418.1764B,
14,HH Car,"[nan, 163.40279, nan]","[nan, -59.45495, nan]","[nan, 3.231497, nan]","[nan, nan, nan]","[nan, 17.0, nan]","[nan, nan, nan]","[nan, 14.0, nan]","[nan, nan, nan]","[nan, 0.8235294117647058, nan]","[nan, nan, nan]",8V+BIII,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
15,QZ Car,"[nan, 161.09547, nan]","[nan, -59.99333, nan]","[nan, 5.9986, nan]","[nan, nan, nan]","[5.0, 30.0, 5.0]","[nan, nan, nan]","[5.0, 20.0, 5.0]","[nan, nan, nan]","[nan, 0.6666666666666666, nan]","[nan, nan, nan]",late-OV+O8III,,Eclipsing binary (phot) + SB2 (spec),2017MNRAS.470.2007W,
16,RZ Cas,"[nan, 42.23129, nan]","[nan, 69.63429, nan]","[nan, 1.1952592, nan]","[nan, nan, nan]","[0.09000000357627869, 2.2799999713897705, 0.09...","[nan, nan, nan]","[0.029999999329447746, 0.7699999809265137, 0.0...","[nan, nan, nan]","[nan, 0.3377192941178685, nan]","[nan, nan, nan]",A(2-3)V+K1IV,,Eclipsing binary (phot) + SB2 (spec),2006AN....327..905S,
17,SX Cas,"[nan, 2.67528, nan]","[nan, 54.89149, nan]","[nan, 36.561, nan]","[nan, nan, nan]","[0.4000000059604645, 5.099999904632568, 0.4000...","[nan, nan, nan]","[0.4000000059604645, 1.5, 0.4000000059604645]","[nan, nan, nan]","[nan, 0.2941176525586755, nan]","[nan, nan, nan]",midB+K3III,,Eclipsing binary (phot) + SB2 (spec),1988A&A...207...37A,
18,TV Cas,"[nan, 4.82809, nan]","[nan, 59.13904, nan]","[nan, 1.812598, nan]","[nan, nan, nan]","[nan, 3.7799999713897705, nan]","[nan, nan, nan]","[nan, 1.5299999713897705, nan]","[nan, nan, nan]","[nan, 0.40476190025664055, nan]","[nan, nan, nan]",B9V+G5IV,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
19,TW Cas,"[nan, 41.47843, nan]","[nan, 65.7264, nan]","[nan, 1.428324, nan]","[nan, nan, nan]","[nan, 2.9000000953674316, nan]","[nan, nan, nan]","[nan, 1.1799999475479126, nan]","[nan, nan, nan]","[nan, 0.4068965202562885, nan]","[nan, nan, nan]",B9V+F6IV,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
20,ZZ Cas,"[nan, 8.37659, nan]","[nan, 62.51116, nan]","[nan, 1.243527, nan]","[nan, nan, nan]","[nan, 4.900000095367432, nan]","[nan, nan, nan]","[nan, 1.649999976158142, nan]","[nan, nan, nan]","[nan, 0.3367346824580858, nan]","[nan, nan, nan]",B3+[B9],,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
21,AQ Cas,"[nan, 19.79312, nan]","[nan, 62.39677, nan]","[nan, 11.72107, nan]","[nan, nan, nan]","[0.9100000262260437, 17.6299991607666, 0.91000...","[nan, nan, nan]","[0.8100000023841858, 12.5600004196167, 0.81000...","[nan, nan, nan]","[nan, 0.712422065655422, nan]","[nan, nan, nan]",B0.5II-III+B3II,,Eclipsing binary (phot) + SB2 (spec),2013NewA...25...68I,
22,GG Cas,"[nan, 19.05393, nan]","[nan, 56.32856, nan]","[nan, 3.758719, nan]","[nan, nan, nan]","[nan, 4.349999904632568, nan]","[nan, nan, nan]","[nan, 3.4100000858306885, nan]","[nan, nan, nan]","[nan, 0.7839080828942503, nan]","[nan, nan, nan]",B5V+KIII-IV,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
23,SV Cen,"[nan, 176.98841, nan]","[nan, -60.56604, nan]","[nan, 1.6585318, nan]","[nan, nan, nan]","[nan, 7.699999809265137, nan]","[nan, nan, nan]","[nan, 9.600000381469727, nan]","[nan, nan, nan]","[nan, 1.2467533271777989, nan]","[nan, nan, nan]",B1V+B6.5III,,Eclipsing binary (phot) + SB2 (spec),1991ApJ...379..721L,
24,BF Cen,"[nan, 174.07098, nan]","[nan, -61.46706, nan]","[nan, 3.69334, nan]","[nan, nan, nan]","[nan, 8.699999809265137, nan]","[nan, nan, nan]","[nan, 3.799999952316284, nan]","[nan, nan, nan]","[nan, 0.4367816132903179, nan]","[nan, nan, nan]",B7V+[A],,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
25,MP Cen,"[nan, 175.94064, nan]","[nan, -61.74334, nan]","[nan, 2.993456, nan]","[nan, nan, nan]","[0.4000000059604645, 11.399999618530273, 0.400...","[nan, nan, nan]","[0.20000000298023224, 4.400000095367432, 0.200...","[nan, nan, nan]","[nan, 0.3859649335615236, nan]","[nan, nan, nan]",B3+B6/7,,Eclipsing binary (phot) + SB2 (spec),2005MNRAS.360..583T,
26,V716 Cen,"[nan, 213.41594, nan]","[nan, -54.62563, nan]","[nan, 1.4900943, nan]","[nan, nan, nan]","[0.07000000029802322, 5.679999828338623, 0.070...","[nan, nan, nan]","[0.05000000074505806, 2.390000104904175, 0.050...","[nan, nan, nan]","[nan, 0.42077467907305205, nan]","[nan, nan, nan]",B5.5V+A2V,,Eclipsing binary (phot) + SB2 (spec),2008MNRAS.385..381B,
27,U Cep,"[nan, 15.57684, nan]","[nan, 81.87558, nan]","[nan, 2.4930801, nan]","[nan, nan, nan]","[nan, 4.039999961853027, nan]","[nan, nan, nan]","[nan, 2.5, nan]","[nan, nan, nan]","[nan, 0.6188118870311387, nan]","[nan, nan, nan]",B8Ve+G8IV,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
28,RS Cep,"[nan, 76.51335, nan]","[nan, 80.24786, nan]","[nan, 12.4200107, nan]","[nan, nan, nan]","[nan, 2.799999952316284, nan]","[nan, nan, nan]","[nan, 0.4099999964237213, nan]","[nan, nan, nan]","[nan, 0.14642857264499276, nan]","[nan, nan, nan]",AVe+G8III-IV,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
29,XX Cep,"[nan, 354.58452, nan]","[nan, 64.33408, nan]","[nan, 2.3373265, nan]","[nan, nan, nan]","[0.05999999865889549, 2.490000009536743, 0.059...","[nan, nan, nan]","[0.009999999776482582, 0.3799999952316284, 0.0...","[nan, nan, nan]","[nan, 0.152610439267559, nan]","[nan, nan, nan]",A8V+K1IV,,Eclipsing binary (phot) + SB2 (spec),2016AJ....151...77K,
30,XY Cep,"[nan, 358.13721, nan]","[nan, 68.93379, nan]","[nan, 2.774527, nan]","[nan, nan, nan]","[nan, 4.699999809265137, nan]","[nan, nan, nan]","[nan, 1.2000000476837158, nan]","[nan, nan, nan]","[nan, 0.25531916944297506, nan]","[nan, nan, nan]",B8+G4,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
31,XZ Cep,"[nan, 338.1045, nan]","[nan, 67.15069, nan]","[nan, 5.0972267, nan]","[nan, nan, nan]","[1.2999999523162842, 18.700000762939453, 1.299...","[nan, nan, nan]","[0.5, 9.300000190734863, 0.5]","[nan, nan, nan]","[nan, 0.4973261931179192, nan]","[nan, nan, nan]",BII+B2III,,Eclipsing binary (phot) + SB2 (spec),2017A&A...607A..82M,
32,GT Cep,"[nan, 344.44714, nan]","[nan, 68.40723, nan]","[nan, 4.908756, nan]","[nan, nan, nan]","[0.5, 10.699999809265137, 0.5]","[nan, nan, nan]","[0.14000000059604645, 2.5799999237060547, 0.14...","[nan, nan, nan]","[nan, 0.24112149249498407, nan]","[nan, nan, nan]",B2V+A0IV,,Eclipsing binary (phot) + SB2 (spec),2015NewA...35...71C,
33,LZ Cep,"[nan, 330.51905, nan]","[nan, 58.00036, nan]","[nan, 3.070507, nan]","[nan, nan, nan]","[9.800000190734863, 15.899999618530273, 9.8000...","[nan, nan, nan]","[2.4000000953674316, 4.099999904632568, 2.4000...","[nan, nan, nan]","[nan, 0.25786163540874063, nan]","[nan, nan, nan]",O9III+ON9.7V,,Eclipsing binary (phot) + SB2 (spec),2011A&A...533A...9M,
34,YY Cet,"[nan, 30.05017, nan]","[nan, -18.20783, nan]","[nan, 0.7904596, nan]","[nan, nan, nan]","[0.1899999976158142, 1.7699999809265137, 0.189...","[nan, nan, nan]","[0.10000000149011612, 0.9200000166893005, 0.10...","[nan, nan, nan]","[nan, 0.5197740263294934, nan]","[nan, nan, nan]",A8V+G2IV,,Eclipsing binary (phot) + SB2 (spec),2012PASP..124..411W,
35,U CrB,"[nan, 229.5473, nan]","[nan, 31.64706, nan]","[nan, 3.45220552, nan]","[nan, nan, nan]","[0.2800000011920929, 4.739999771118164, 0.2800...","[nan, nan, nan]","[0.05999999865889549, 1.4600000381469727, 0.05...","[nan, nan, nan]","[nan, 0.30801690055832204, nan]","[nan, nan, nan]",B6V+F8-GIII-IV,,Eclipsing binary (phot) + SB2 (spec),2003MNRAS.342.1349Y,
36,RW CrB,"[nan, 234.81347, nan]","[nan, 29.62212, nan]","[nan, 0.7264114, nan]","[nan, nan, nan]","[nan, 1.5, nan]","[nan, nan, nan]","[nan, 0.4000000059604645, nan]","[nan, nan, nan]","[nan, 0.26666667064030963, nan]","[nan, nan, nan]",A9V+[K1IV],,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
37,AB Cru,"[nan, 184.40468, nan]","[nan, -58.16457, nan]","[nan, 3.4133135, nan]","[nan, nan, nan]","[1.0399999618530273, 19.75, 1.0399999618530273]","[nan, nan, nan]","[0.6499999761581421, 6.949999809265137, 0.6499...","[nan, nan, nan]","[nan, 0.35189872451975374, nan]","[nan, nan, nan]",O8Vn,,Eclipsing binary (phot) + SB2 (spec),1994A&A...291..185L,
38,AI Cru,"[nan, 181.53203, nan]","[nan, -61.2569, nan]","[nan, 1.4177112, nan]","[nan, nan, nan]","[0.20000000298023224, 10.300000190734863, 0.20...","[nan, nan, nan]","[0.10000000149011612, 6.300000190734863, 0.100...","[nan, nan, nan]","[nan, 0.6116504926283292, nan]","[nan, nan, nan]",B2IVe,,Eclipsing binary (phot) + SB2 (spec),1987MNRAS.226..879B,
39,SW Cyg,"[nan, 301.74138, nan]","[nan, 46.29949, nan]","[nan, 4.5731, nan]","[nan, nan, nan]","[nan, 1.2400000095367432, nan]","[nan, nan, nan]","[nan, 0.44999998807907104, nan]","[nan, nan, nan]","[nan, 0.362903213401739, nan]","[nan, nan, nan]",A2Ve+[KI],,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
40,WW Cyg,"[nan, 301.0113, nan]","[nan, 41.58791, nan]","[nan, 3.317747, nan]","[nan, nan, nan]","[nan, 4.849999904632568, nan]","[nan, nan, nan]","[nan, 1.649999976158142, nan]","[nan, nan, nan]","[nan, 0.3402061873407696, nan]","[nan, nan, nan]",B7V+[G0IV],,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
41,KU Cyg,"[nan, 303.18795, nan]","[nan, 47.39483, nan]","[nan, 38.439484, nan]","[nan, nan, nan]","[nan, 3.8499999046325684, nan]","[nan, nan, nan]","[nan, 0.47999998927116394, nan]","[nan, nan, nan]","[nan, 0.12467532497691675, nan]","[nan, nan, nan]",A7V+M2III,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
42,V448 Cyg,"[nan, 301.54145, nan]","[nan, 35.386, nan]","[nan, 6.5197162, nan]","[nan, nan, nan]","[0.699999988079071, 24.700000762939453, 0.6999...","[nan, nan, nan]","[0.699999988079071, 13.699999809265137, 0.6999...","[nan, nan, nan]","[nan, 0.5546558455909437, nan]","[nan, nan, nan]",O9.5V+B1Ib,,Eclipsing binary (phot) + SB2 (spec),2009MNRAS.396.1553D,
43,V548 Cyg,"[nan, 299.24294, nan]","[nan, 54.79952, nan]","[nan, 1.80524695, nan]","[nan, nan, nan]","[0.14000000059604645, 2.180000066757202, 0.140...","[nan, nan, nan]","[0.05400000140070915, 0.7689999938011169, 0.05...","[nan, nan, nan]","[nan, 0.352752279932276, nan]","[nan, nan, nan]",AV+[K],,Eclipsing binary (phot) + SB2 (spec),2016AJ....152...49Y,
44,W Del,"[nan, 309.41702, nan]","[nan, 18.28438, nan]","[nan, 4.8061, nan]","[nan, nan, nan]","[nan, 2.009999990463257, nan]","[nan, nan, nan]","[nan, 0.41999998688697815, nan]","[nan, nan, nan]","[nan, 0.20895521834812458, nan]","[nan, nan, nan]",B9.5Ve+G5IV,,Eclipsing binary (phot) + SB2 (spec),2004yCat.5115....0S,
45,AV Del,"[nan, 311.38124, nan]","[nan, 11.17402, nan]","[nan, 3.8534528, nan]","[nan, nan, nan]","[0.02800000086426735, 1.4529999494552612, 0.02...","[nan, nan, nan]","[0.014000000432133675, 0.7049999833106995, 0.0...","[nan, nan, nan]","[nan, 0.48520303360988304, nan]","[nan, nan, nan]",F8,,Eclipsing binary (phot) + SB2 (spec),2005AJ....130..234M,
46,Z Dra,"[nan, 176.37171, nan]","[nan, 72.24954, nan]","[nan, 1.3574226, nan]","[nan, nan, nan]","[0.05000000074505806, 1.3899999856948853, 0.05...","[nan, nan, nan]","[0.019999999552965164, 0.41999998688697815, 0....","[nan, nan, nan]","[nan, 0.30215826705711285, nan]","[nan, nan, nan]",A5V+gK2,,Eclipsing binary (phot) + SB2 (spec),2017IBVS.6223....1T,
47,RZ Dra,"[nan, 275.77254, nan]","[nan, 58.90356, nan]","[nan, 0.55087623, nan]","[nan, nan, nan]","[0.029999999329447746, 1.6299999952316284, 0.0...","[nan, nan, nan]","[0.019999999552965164, 0.699999988079071, 0.01...","[nan, nan, nan]","[nan, 0.42944784670358155, nan]","[nan, nan, nan]",A5V+K2IV,,Eclipsing binary (phot) + SB2 (spec),2011NewA...16....6E,
48,TW Dra,"[nan, 233.46275, nan]","[nan, 63.90714, nan]","[nan, 2.80686656, nan]","[nan, nan, nan]","[0.05299999937415123, 2.111999988555908, 0.052...","[nan, nan, nan]","[0.020999999716877937, 0.8500000238418579, 0.0...","[nan, nan, nan]","[nan, 0.40246213468166264, nan]","[nan, nan, nan]",A6V+KIII,,Eclipsing binary (phot) + SB2 (spec),2010arXiv1012.5679Z,
49,AI Dra,"[nan, 254.07564, nan]","[nan, 52.69843, nan]","[nan, 1.1988146, nan]","[nan, nan, nan]","[0.09000000357627869, 2.859999895095825, 0.090...","[nan, nan, nan]","[0.05000000074505806, 1.340000033378601, 0.050...","[nan, nan, nan]","[nan, 0.468531497387941, nan]","[nan, nan, nan]",A0V+G4V,,Eclipsing binary (phot) + SB2 (spec),2004MNRAS.351..707L,

## RA and DEC in the right format

In [6]:
# Collect the system names from the DataFrame
targets = df["System Name"].tolist()

display(df['System Name'].values)
targets = df['System Name'].values.tolist()

# Run the script and capture output
result = subprocess.run(["python3", "Get_Coords_From_SIMBAD.py"] + targets, capture_output=True, text=True)


# print("STDOUT:\n", result.stdout)
# Script prints one dict per system like:
#  *__89_HER = {
#     "System Name": '*  89 Her',
#     "RA":  [0.00001144, 268.854951, 0.00001144],
#     "Dec": [0.00001275, 26.049991, 0.00001275],
# }

# Get the printed output as a string
RA_DEC = result.stdout

entries = re.findall(r'([A-Z0-9_]+)\s*=\s*({.*?})', RA_DEC, re.DOTALL)
RADEC_data = {}

for name, dict_str in entries:
    RADEC_data[name] = ast.literal_eval(dict_str)

RADEC_data.keys()
# Now `RADEC_data` is a Python dictionary with the object data
# print(RADEC_data['HD__58978']['RA'])
# print(RADEC_data['HD__58978']['Dec'])

# Extract RA and Dec values
RA_values = [RADEC_data[key]['RA'] for key in RADEC_data.keys() ]
DEC_values = [RADEC_data[key]['Dec'] for key in RADEC_data.keys() ]


print(RA_values)
print(DEC_values)

df["RA"]  = RA_values
df["Dec"] = DEC_values

array(['DM -64 4333', 'DM -42 2048', 'DM -14 2678', 'DM -01 3022',
       'HD 5424', 'HD 16458', 'HD 18182', 'HD 20394', 'HD 24035',
       'HD 27271', 'HD 31487', 'HD 40430', 'HD 43389', 'HD 44896',
       'HD 46407', 'HD 49641', 'HD 49841', 'HD 50082', 'HD 51959',
       'HD 53199', 'HD 58121', 'HD 58368', 'HD 59852', 'HD 77247',
       'HD 84678', 'HD 88562', 'HD 91208', 'HD 92626', 'HD 95193',
       'HD 98839', 'HD 101013', 'HD 104979', 'HD 107541', 'HD 119185',
       'HD 121447', 'HD 123949', 'HD 134698', 'HD 139195', 'HD 143899',
       'HD 154430', 'HD 178717', 'HD 180622', 'HD 183915', 'HD 196673',
       'HD 199939', 'HD 200063', 'HD 201657', 'HD 201824', 'HD 202109',
       'HD 204075', 'HD 205011', 'HD 210946', 'HD 211594', 'HD 218356',
       'HD 223617', 'NGC 2420-173'], dtype=object)

[[2.567e-05, 349.129716, 2.567e-05], [3.87e-06, 84.501334, 3.87e-06], [3.13e-06, 132.981509, 3.13e-06], [8.62e-06, 226.86194, 8.62e-06], [1.691e-05, 13.933035, 1.691e-05], [0.0001076, 41.948857, 0.0001076], [4.07e-06, 43.796224, 4.07e-06], [1.29e-05, 49.223252, 1.29e-05], [7.361e-05, 55.927469, 7.361e-05], [2.447e-05, 64.640935, 2.447e-05], [2.677e-05, 74.765533, 2.677e-05], [5.94e-06, 89.585, 5.94e-06], [1.084e-05, 93.946117, 1.084e-05], [1.815e-05, 95.724037, 1.815e-05], [4.275e-05, 98.195305, 4.275e-05], [1.086e-05, 102.372703, 1.086e-05], [2.367e-05, 102.662379, 2.367e-05], [2.673e-05, 102.974829, 2.673e-05], [5.26e-06, 104.792067, 5.26e-06], [5.08e-06, 106.201188, 5.08e-06], [1.503e-05, 111.11849, 1.503e-05], [2.298e-05, 111.412367, 2.298e-05], [5.63e-06, 112.94398, 5.63e-06], [7.31e-06, 135.884467, 7.31e-06], [3.938e-05, 145.46907, 3.938e-05], [1.82e-05, 153.124761, 1.82e-05], [1.563e-05, 157.888064, 1.563e-05], [3.227e-05, 160.208219, 3.227e-05], [1.882e-05, 164.861565, 1.882e-05], [2.274e-05, 170.706575, 2.274e-05], [2.846e-05, 174.470837, 2.846e-05], [3.519e-05, 181.302216, 3.519e-05], [9.74e-06, 185.450318, 9.74e-06], [5.16e-06, 205.489634, 5.16e-06], [7.4e-06, 208.94569, 7.4e-06], [2.496e-05, 212.747131, 2.496e-05], [5.99e-06, 227.923757, 5.99e-06], [2.124e-05, 234.123225, 2.124e-05], [1.636e-05, 240.932528, 1.636e-05], [1.757e-05, 257.226142, 1.757e-05], [6.27e-06, 287.341706, 6.27e-06], [1.131e-05, 289.295952, 1.131e-05], [6.1e-06, 292.856266, 6.1e-06], [0.00015632, 309.434684, 0.00015632], [1.454e-05, 314.681226, 1.454e-05], [7.83e-06, 315.266853, 7.83e-06], [2.283e-05, 317.639716, 2.283e-05], [6.18e-06, 318.073264, 6.18e-06], [2.575e-05, 318.234108, 2.575e-05], [7.217e-05, 321.666794, 7.217e-05], [9.08e-06, 322.958936, 9.08e-06], [1.715e-05, 333.458969, 1.715e-05], [4.018e-05, 334.562273, 4.018e-05], [2.975e-05, 346.778091, 2.975e-05], [4.184e-05, 357.778324, 4.184e-05], [5.59e-06, 114.612357, 5.59e-06]]
[[1.178e-05, -63.451273, 1.178e-05], [3.03e-06, -42.326459, 3.03e-06], [2.67e-06, -14.652608, 2.67e-06], [7.56e-06, -2.305382, 7.56e-06], [1.397e-05, -27.893684, 1.397e-05], [1.678e-05, 81.448474, 1.678e-05], [3.94e-06, -4.316631, 3.94e-06], [1.178e-05, 2.339352, 1.178e-05], [2.25e-05, -72.609111, 2.25e-05], [1.803e-05, 2.470529, 1.803e-05], [1.322e-05, 51.942231, 1.322e-05], [5.58e-06, -10.874762, 5.58e-06], [9.81e-06, -2.385622, 9.81e-06], [1.694e-05, -33.614603, 1.694e-05], [4.85e-05, -11.166385, 4.85e-05], [9.33e-06, 3.691706, 9.33e-06], [2.353e-05, 5.66287, 2.353e-05], [2.417e-05, 6.6068, 2.417e-05], [5.47e-06, -7.108898, 5.47e-06], [4.39e-06, 13.238671, 4.39e-06], [1.239e-05, 6.150253, 1.239e-05], [1.969e-05, 7.560846, 1.969e-05], [5.03e-06, -4.359804, 5.03e-06], [3.92e-06, 53.108283, 3.92e-06], [1.075e-05, -75.664277, 1.075e-05], [1.614e-05, -15.889798, 1.614e-05], [1.447e-05, -17.076536, 1.447e-05], [2.283e-05, -48.025103, 2.283e-05], [1.447e-05, -14.171594, 1.447e-05], [2.233e-05, 43.482698, 2.233e-05], [2.258e-05, 50.618186, 2.258e-05], [2.853e-05, 8.733019, 2.853e-05], [5.83e-06, -34.780037, 5.83e-06], [4.22e-06, -13.027725, 4.22e-06], [6.17e-06, -18.249024, 6.17e-06], [1.669e-05, -19.143952, 1.669e-05], [5.06e-06, -10.507657, 5.06e-06], [2.081e-05, 10.010147, 2.081e-05], [1.033e-05, -19.575203, 1.033e-05], [7.86e-06, -59.287852, 7.86e-06], [6.33e-06, 10.241178, 6.33e-06], [1.078e-05, 0.497366, 1.078e-05], [6.36e-06, 11.627951, 6.36e-06], [0.00012222, 33.366492, 0.00012222], [1.047e-05, 44.414578, 1.047e-05], [3.36e-06, 1.034923, 3.36e-06], [1.589e-05, 16.979567, 1.589e-05], [5.64e-06, -8.356904, 5.64e-06], [2.478e-05, 30.226899, 2.478e-05], [4.614e-05, -22.41132, 4.614e-05], [5.92e-06, 23.845163, 5.92e-06], [1.789e-05, 1.60893, 1.789e-05], [3.919e-05, -5.841626, 3.919e-05], [1.933e-05, 25.468271, 1.933e-05], [2.228e-05, 2.237851, 2.228e-05], [4.19e-06, 21.558695, 4.19e-06]]

# Check what it looks like:

In [7]:
display(df)

,System Name,RA,Dec,Period,Eccentricity,M1,M1_sin3i,M2,M2_sin3i,q,Mass Function,Type1,Type2,Detection Method,Reference,Notes
0,DM -64 4333,"[2.567e-05, 349.129716, 2.567e-05]","[1.178e-05, -63.451273, 1.178e-05]","[nan, 386.0, nan]","[nan, 0.03, nan]","[0.1, 1.4, 0.1]","[nan, nan, nan]","[nan, 0.61, nan]","[nan, nan, nan]","[nan, 0.4357142857142857, nan]","[nan, 0.068, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.10; [hs/ls]=0.84; Type ...
1,DM -42 2048,"[3.87e-06, 84.501334, 3.87e-06]","[3.03e-06, -42.326459, 3.03e-06]","[nan, 3260.0, nan]","[nan, 0.08, nan]","[0.5, 1.9, 0.7]","[nan, nan, nan]","[nan, 0.74, nan]","[nan, nan, nan]","[nan, 0.3894736842105263, nan]","[nan, 0.065, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.38; Type ...
2,DM -14 2678,"[3.13e-06, 132.981509, 3.13e-06]","[2.67e-06, -14.652608, 2.67e-06]","[nan, 3470.0, nan]","[nan, 0.22, nan]","[0.2, 3.0, 0.2]","[nan, nan, nan]","[nan, 0.8, nan]","[nan, nan, nan]","[nan, 0.26666666666666666, nan]","[nan, 0.023, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.01; [hs/ls]=0.04; Type m...
3,DM -01 3022,"[8.62e-06, 226.86194, 8.62e-06]","[7.56e-06, -2.305382, 7.56e-06]","[nan, 3253.0, nan]","[nan, 0.28, nan]","[0.1, 1.6, 0.1]","[nan, nan, nan]","[nan, 0.55, nan]","[nan, nan, nan]","[nan, 0.34375, nan]","[nan, 0.016, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.14; [hs/ls]=-0.26; Type...
4,HD 5424,"[1.691e-05, 13.933035, 1.691e-05]","[1.397e-05, -27.893684, 1.397e-05]","[nan, 1881.0, nan]","[nan, 0.23, nan]","[0.3, 1.3, 0.4]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.4538461538461538, nan]","[nan, 0.005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.43; [hs/ls]=0.57; Type ...
5,HD 16458,"[0.0001076, 41.948857, 0.0001076]","[1.678e-05, 81.448474, 1.678e-05]","[nan, 2018.0, nan]","[nan, 0.1, nan]","[0.1, 1.9, 0.1]","[nan, nan, nan]","[nan, 0.72, nan]","[nan, nan, nan]","[nan, 0.37894736842105264, nan]","[nan, 0.041, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.64; [hs/ls]=0.19; Type ...
6,HD 18182,"[4.07e-06, 43.796224, 4.07e-06]","[3.94e-06, -4.316631, 3.94e-06]","[nan, 8059.0, nan]","[nan, 0.31, nan]","[0.1, 1.8, 0.2]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.0002, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.17; [hs/ls]=-0.05; Type...
7,HD 20394,"[1.29e-05, 49.223252, 1.29e-05]","[1.178e-05, 2.339352, 1.178e-05]","[nan, 2226.0, nan]","[nan, 0.2, nan]","[0.2, 2.0, 0.2]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.38, nan]","[nan, 0.002, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.27; [hs/ls]=0.42; Type ...
8,HD 24035,"[7.361e-05, 55.927469, 7.361e-05]","[2.25e-05, -72.609111, 2.25e-05]","[nan, 377.8, nan]","[nan, 0.3, nan]","[0.2, 1.3, 0.3]","[nan, nan, nan]","[nan, 0.57, nan]","[nan, nan, nan]","[nan, 0.4384615384615384, nan]","[nan, 0.047, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.87; Type ...
9,HD 27271,"[2.447e-05, 64.640935, 2.447e-05]","[1.803e-05, 2.470529, 1.803e-05]","[nan, 1693.0, nan]","[nan, 0.22, nan]","[0.2, 2.9, 0.2]","[nan, nan, nan]","[nan, 0.79, nan]","[nan, nan, nan]","[nan, 0.2724137931034483, nan]","[nan, 0.024, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.07; [hs/ls]=-0.13; Type...
10,HD 31487,"[2.677e-05, 74.765533, 2.677e-05]","[1.322e-05, 51.942231, 1.322e-05]","[nan, 1066.0, nan]","[nan, 0.05, nan]","[0.3, 3.4, 0.2]","[nan, nan, nan]","[nan, 1.03, nan]","[nan, nan, nan]","[nan, 0.30294117647058827, nan]","[nan, 0.038, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.04; [hs/ls]=0.32; Type ...
11,HD 40430,"[5.94e-06, 89.585, 5.94e-06]","[5.58e-06, -10.874762, 5.58e-06]","[nan, 5609.0, nan]","[nan, 0.22, nan]","[0.2, 2.3, 0.2]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.29565217391304355, nan]","[nan, 0.0025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.34; [hs/ls]=0.23; Type ...
12,HD 43389,"[1.084e-05, 93.946117, 1.084e-05]","[9.81e-06, -2.385622, 9.81e-06]","[nan, 1689.0, nan]","[nan, 0.08, nan]","[0.3, 1.8, 0.4]","[nan, nan, nan]","[nan, 0.72, nan]","[nan, nan, nan]","[nan, 0.39999999999999997, nan]","[nan, 0.043, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.35; [hs/ls]=0.76; Type ...
13,HD 44896,"[1.815e-05, 95.724037, 1.815e-05]","[1.694e-05, -33.614603, 1.694e-05]","[nan, 629.0, nan]","[nan, 0.02, nan]","[1.0, 3.0, 1.2]","[nan, nan, nan]","[nan, 0.96, nan]","[nan, nan, nan]","[nan, 0.32, nan]","[nan, 0.048, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.25; [hs/ls]=-0.09; Type...
14,HD 46407,"[4.275e-05, 98.195305, 4.275e-05]","[4.85e-05, -11.166385, 4.85e-05]","[nan, 457.0, nan]","[nan, 0.013, nan]","[0.7, 2.1, 0.6]","[nan, nan, nan]","[nan, 0.78, nan]","[nan, nan, nan]","[nan, 0.37142857142857144, nan]","[nan, 0.035, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.35; [hs/ls]=0.31; Type ...
15,HD 49641,"[1.086e-05, 102.372703, 1.086e-05]","[9.33e-06, 3.691706, 9.33e-06]","[nan, 1785.0, nan]","[nan, 0.07, nan]","[0.8, 2.7, 1.2]","[nan, nan, nan]","[nan, 0.91, nan]","[nan, nan, nan]","[nan, 0.337037037037037, nan]","[nan, 0.003, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.30; [hs/ls]=0.74; Type ...
16,HD 49841,"[2.367e-05, 102.662379, 2.367e-05]","[2.353e-05, 5.66287, 2.353e-05]","[nan, 897.0, nan]","[nan, 0.16, nan]","[0.2, 2.8, 0.2]","[nan, nan, nan]","[nan, 0.78, nan]","[nan, nan, nan]","[nan, 0.2785714285714286, nan]","[nan, 0.032, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.20; [hs/ls]=-0.06; Type ...
17,HD 50082,"[2.673e-05, 102.974829, 2.673e-05]","[2.417e-05, 6.6068, 2.417e-05]","[nan, 2896.0, nan]","[nan, 0.19, nan]","[0.2, 1.6, 0.3]","[nan, nan, nan]","[nan, 0.67, nan]","[nan, nan, nan]","[nan, 0.41875, nan]","[nan, 0.027, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.32; [hs/ls]=0.44; Type ...
18,HD 51959,"[5.26e-06, 104.792067, 5.26e-06]","[5.47e-06, -7.108898, 5.47e-06]","[nan, 9718.0, nan]","[nan, 0.53, nan]","[0.1, 1.2, 0.1]","[nan, nan, nan]","[nan, 0.47, nan]","[nan, nan, nan]","[nan, 0.39166666666666666, nan]","[nan, 0.0005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.21; [hs/ls]=-0.13; Type...
19,HD 53199,"[5.08e-06, 106.201188, 5.08e-06]","[4.39e-06, 13.238671, 4.39e-06]","[nan, 8314.0, nan]","[nan, 0.24, nan]","[0.1, 2.5, 0.1]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.284, nan]","[nan, 0.028, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.20; [hs/ls]=0.31; Type ...
20,HD 58121,"[1.503e-05, 111.11849, 1.503e-05]","[1.239e-05, 6.150253, 1.239e-05]","[nan, 1214.0, nan]","[nan, 0.14, nan]","[0.4, 2.6, 0.5]","[nan, nan, nan]","[nan, 0.73, nan]","[nan, nan, nan]","[nan, 0.28076923076923077, nan]","[nan, 0.015, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.01; [hs/ls]=0.10; Type ...
21,HD 58368,"[2.298e-05, 111.412367, 2.298e-05]","[1.969e-05, 7.560846, 1.969e-05]","[nan, 672.0, nan]","[nan, 0.22, nan]","[0.2, 2.6, 0.1]","[nan, nan, nan]","[nan, 0.73, nan]","[nan, nan, nan]","[nan, 0.28076923076923077, nan]","[nan, 0.021, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.04; [hs/ls]=0.27; Type m...
22,HD 59852,"[5.63e-06, 112.94398, 5.63e-06]","[5.03e-06, -4.359804, 5.03e-06]","[nan, 3464.0, nan]","[nan, 0.15, nan]","[0.3, 2.5, 0.2]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.284, nan]","[nan, 0.0022, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.22; [hs/ls]=0.06; Type ...
23,HD 77247,"[7.31e-06, 135.884467, 7.31e-06]","[3.92e-06, 53.108283, 3.92e-06]","[nan, 80.0, nan]","[nan, 0.09, nan]","[0.2, 3.9, 0.1]","[nan, nan, nan]","[nan, 0.94, nan]","[nan, nan, nan]","[nan, 0.24102564102564103, nan]","[nan, 0.005, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.13; [hs/ls]=-0.02; Type...
24,HD 84678,"[3.938e-05, 145.46907, 3.938e-05]","[1.075e-05, -75.664277, 1.075e-05]","[nan, 1630.0, nan]","[nan, 0.06, nan]","[0.5, 2.3, 0.6]","[nan, nan, nan]","[nan, 0.83, nan]","[nan, nan, nan]","[nan, 0.36086956521739133, nan]","[nan, 0.062, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.13; [hs/ls]=0.63; Type ...
25,HD 88562,"[1.82e-05, 153.124761, 1.82e-05]","[1.614e-05, -15.889798, 1.614e-05]","[nan, 1445.0, nan]","[nan, 0.2, nan]","[0.1, 1.0, 0.1]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, 0.048, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.53; [hs/ls]=0.41; Type ...
26,HD 91208,"[1.563e-05, 157.888064, 1.563e-05]","[1.447e-05, -17.076536, 1.447e-05]","[nan, 1754.0, nan]","[nan, 0.17, nan]","[0.2, 2.3, 0.1]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.29565217391304355, nan]","[nan, 0.022, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.16; [hs/ls]=0.05; Type ...
27,HD 92626,"[3.227e-05, 160.208219, 3.227e-05]","[2.283e-05, -48.025103, 2.283e-05]","[nan, 918.0, nan]","[nan, 0.0, nan]","[0.6, 3.1, 0.4]","[nan, nan, nan]","[nan, 0.98, nan]","[nan, nan, nan]","[nan, 0.3161290322580645, nan]","[nan, 0.042, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.15; [hs/ls]=1.02; Type ...
28,HD 95193,"[1.882e-05, 164.861565, 1.882e-05]","[1.447e-05, -14.171594, 1.447e-05]","[nan, 1653.0, nan]","[nan, 0.13, nan]","[0.1, 2.7, 0.1]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.28148148148148144, nan]","[nan, 0.026, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.04; [hs/ls]=-0.07; Type...
29,HD 98839,"[2.274e-05, 170.706575, 2.274e-05]","[2.233e-05, 43.482698, 2.233e-05]","[nan, 16471.0, nan]","[nan, 0.56, nan]","[0.2, 4.3, 0.2]","[nan, nan, nan]","[nan, 1.0, nan]","[nan, nan, nan]","[nan, 0.23255813953488372, nan]","[nan, 0.056, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.05; [hs/ls]=0.19; Type ...
30,HD 101013,"[2.846e-05, 174.470837, 2.846e-05]","[2.258e-05, 50.618186, 2.258e-05]","[nan, 1711.0, nan]","[nan, 0.2, nan]","[0.3, 1.7, 0.3]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.4, nan]","[nan, 0.037, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.40; [hs/ls]=0.10; Type ...
31,HD 104979,"[3.519e-05, 181.302216, 3.519e-05]","[2.853e-05, 8.733019, 2.853e-05]","[nan, 19295.0, nan]","[nan, 0.08, nan]","[0.2, 2.7, 0.1]","[nan, nan, nan]","[nan, 0.75, nan]","[nan, nan, nan]","[nan, 0.27777777777777773, nan]","[nan, nan, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.26; [hs/ls]=0.31; Type ...
32,HD 107541,"[9.74e-06, 185.450318, 9.74e-06]","[5.83e-06, -34.780037, 5.83e-06]","[nan, 3570.0, nan]","[nan, 0.1, nan]","[0.1, 1.1, 0.2]","[nan, nan, nan]","[nan, 0.54, nan]","[nan, nan, nan]","[nan, 0.4909090909090909, nan]","[nan, 0.029, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.63; [hs/ls]=0.75; Type ...
33,HD 119185,"[5.16e-06, 205.489634, 5.16e-06]","[4.22e-06, -13.027725, 4.22e-06]","[nan, 22065.0, nan]","[nan, 0.6, nan]","[0.2, 1.7, 0.2]","[nan, nan, nan]","[nan, 0.57, nan]","[nan, nan, nan]","[nan, 0.3352941176470588, nan]","[nan, nan, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.42; [hs/ls]=0.32; Type ...
34,HD 121447,"[7.4e-06, 208.94569, 7.4e-06]","[6.17e-06, -18.249024, 6.17e-06]","[nan, 185.7, nan]","[nan, 0.015, nan]","[0.1, 1.6, 0.1]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.37499999999999994, nan]","[nan, 0.025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.90; [hs/ls]=0.84; Type ...
35,HD 123949,"[2.496e-05, 212.747131, 2.496e-05]","[1.669e-05, -19.143952, 1.669e-05]","[nan, 8523.0, nan]","[nan, 0.92, nan]","[0.1, 1.3, 0.3]","[nan, nan, nan]","[nan, 0.58, nan]","[nan, nan, nan]","[nan, 0.4461538461538461, nan]","[nan, 0.046, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.23; [hs/ls]=0.35; Type ...
36,HD 134698,"[5.99e-06, 227.923757, 5.99e-06]","[5.06e-06, -10.507657, 5.06e-06]","[nan, 10005.0, nan]","[nan, 0.95, nan]","[0.2, 1.5, 0.2]","[nan, nan, nan]","[nan, 0.53, nan]","[nan, nan, nan]","[nan, 0.35333333333333333, nan]","[nan, 0.054, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.57; [hs/ls]=0.02; Type ...
37,HD 139195,"[2.124e-05, 234.123225, 2.124e-05]","[2.081e-05, 10.010147, 2.081e-05]","[nan, 5324.0, nan]","[nan, 0.35, nan]","[0.1, 2.6, 0.1]","[nan, nan, nan]","[nan, 0.74, nan]","[nan, nan, nan]","[nan, 0.2846153846153846, nan]","[nan, 0.026, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.07; [hs/ls]=-0.17; Type...
38,HD 143899,"[1.636e-05, 240.932528, 1.636e-05]","[1.033e-05, -19.575203, 1.033e-05]","[nan, 1461.0, nan]","[nan, 0.19, nan]","[0.1, 2.4, 0.1]","[nan, nan, nan]","[nan, 0.71, nan]","[nan, nan, nan]","[nan, 0.29583333333333334, nan]","[nan, 0.017, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.29; [hs/ls]=0.19; Type ...
39,HD 154430,"[1.757e-05, 257.226142, 1.757e-05]","[7.86e-06, -59.287852, 7.86e-06]","[nan, 1668.0, nan]","[nan, 0.11, nan]","[0.7, 2.3, 1.4]","[nan, nan, nan]","[nan, 0.81, nan]","[nan, nan, nan]","[nan, 0.35217391304347834, nan]","[nan, 0.034, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.36; [hs/ls]=0.71; Type ...
40,HD 178717,"[6.27e-06, 287.341706, 6.27e-06]","[6.33e-06, 10.241178, 6.33e-06]","[nan, 2866.0, nan]","[nan, 0.43, nan]","[0.7, 1.6, 0.9]","[nan, nan, nan]","[nan, 0.66, nan]","[nan, nan, nan]","[nan, 0.4125, nan]","[nan, 0.006, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.52; [hs/ls]=0.18; Type ...
41,HD 180622,"[1.131e-05, 289.295952, 1.131e-05]","[1.078e-05, 0.497366, 1.078e-05]","[nan, 4049.0, nan]","[nan, 0.06, nan]","[0.2, 1.8, 0.3]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.07, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.03; [hs/ls]=-0.13; Type ...
42,HD 183915,"[6.1e-06, 292.856266, 6.1e-06]","[6.36e-06, 11.627951, 6.36e-06]","[nan, 4382.0, nan]","[nan, 0.27, nan]","[0.6, 1.8, 1.0]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.3333333333333333, nan]","[nan, 7e-05, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m->s; [Fe/H]=-0.59; [hs/ls]=0.91; Ty...
43,HD 196673,"[0.00015632, 309.434684, 0.00015632]","[0.00012222, 33.366492, 0.00012222]","[nan, 7780.0, nan]","[nan, 0.59, nan]","[0.1, 5.0, 0.0]","[nan, nan, nan]","[nan, 1.1, nan]","[nan, nan, nan]","[nan, 0.22000000000000003, nan]","[nan, 0.02, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=0.12; [hs/ls]=0.23; Type m...
44,HD 199939,"[1.454e-05, 314.681226, 1.454e-05]","[1.047e-05, 44.414578, 1.047e-05]","[nan, 584.9, nan]","[nan, 0.28, nan]","[0.4, 2.8, 0.4]","[nan, nan, nan]","[nan, 0.93, nan]","[nan, nan, nan]","[nan, 0.3321428571428572, nan]","[nan, 0.025, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.22; [hs/ls]=0.41; Type ...
45,HD 200063,"[7.83e-06, 315.266853, 7.83e-06]","[3.36e-06, 1.034923, 3.36e-06]","[nan, 1735.0, nan]","[nan, 0.07, nan]","[0.9, 2.0, 1.3]","[nan, nan, nan]","[nan, 0.64, nan]","[nan, nan, nan]","[nan, 0.32, nan]","[nan, 0.058, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.34; [hs/ls]=0.38; Type ...
46,HD 201657,"[2.283e-05, 317.639716, 2.283e-05]","[1.589e-05, 16.979567, 1.589e-05]","[nan, 1710.0, nan]","[nan, 0.17, nan]","[0.4, 1.8, 0.5]","[nan, nan, nan]","[nan, 0.7, nan]","[nan, nan, nan]","[nan, 0.38888888888888884, nan]","[nan, 0.004, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.34; [hs/ls]=0.82; Type ...
47,HD 201824,"[6.18e-06, 318.073264, 6.18e-06]","[5.64e-06, -8.356904, 5.64e-06]","[nan, 2837.0, nan]","[nan, 0.34, nan]","[0.2, 1.7, 0.4]","[nan, nan, nan]","[nan, 0.68, nan]","[nan, nan, nan]","[nan, 0.4, nan]","[nan, 0.04, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.40; [hs/ls]=0.64; Type ...
48,HD 202109,"[2.575e-05, 318.234108, 2.575e-05]","[2.478e-05, 30.226899, 2.478e-05]","[nan, 6489.0, nan]","[nan, 0.22, nan]","[0.4, 3.4, 0.2]","[nan, nan, nan]","[nan, 0.87, nan]","[nan, nan, nan]","[nan, 0.25588235294117645, nan]","[nan, 0.023, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.03; [hs/ls]=-0.10; Type...
49,HD 204075,"[7.217e-05, 321.666794, 7.217e-05]","[4.614e-05, -22.41132, 4.614e-05]","[nan, 2378.0, nan]","[nan, 0.28, nan]","[0.2, 4.5, 0.3]","[nan, nan, nan]","[nan, 1.03, nan]","[nan, nan, nan]","[nan, 0.2288888888888889, nan]","[nan, 0.004, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.09; [hs/ls]=-0.43; Type...
50,HD 205011,"[9.08e-06, 322.958936, 9.08e-06]","[5.92e-06, 23.845163, 5.92e-06]","[nan, 2837.0, nan]","[nan, 0.24, nan]","[0.3, 1.8, 0.3]","[nan, nan, nan]","[nan, 0.6, nan]","[nan, nan, nan]","[nan, 0.3333333333333333, nan]","[nan, 0.034, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.26; [hs/ls]=-0.02; Type...
51,HD 210946,"[1.715e-05, 333.458969, 1.715e-05]","[1.789e-05, 1.60893, 1.789e-05]","[nan, 1529.0, nan]","[nan, 0.13, nan]","[0.4, 1.8, 0.5]","[nan, nan, nan]","[nan, 0.59, nan]","[nan, nan, nan]","[nan, 0.3277777777777778, nan]","[nan, 0.041, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.29; [hs/ls]=0.07; Type ...
52,HD 211594,"[4.018e-05, 334.562273, 4.018e-05]","[3.919e-05, -5.841626, 3.919e-05]","[nan, 1019.0, nan]","[nan, 0.06, nan]","[0.2, 2.0, 0.3]","[nan, nan, nan]","[nan, 0.76, nan]","[nan, nan, nan]","[nan, 0.38, nan]","[nan, 0.014, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s; [Fe/H]=-0.29; [hs/ls]=0.75; Type ...
53,HD 218356,"[2.975e-05, 346.778091, 2.975e-05]","[1.933e-05, 25.468271, 1.933e-05]","[nan, 111.0, nan]","[nan, 0.0, nan]","[1.1, 4.3, 0.2]","[nan, nan, nan]","[nan, 1.0, nan]","[nan, nan, nan]","[nan, 0.23255813953488372, nan]","[nan, 4e-05, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.06; [hs/ls]=0.35; Type ...
54,HD 223617,"[4.184e-05, 357.778324, 4.184e-05]","[2.228e-05, 2.237851, 2.228e-05]","[nan, 1294.0, nan]","[nan, 0.06, nan]","[0.1, 1.4, 0.1]","[nan, nan, nan]","[nan, 0.51, nan]","[nan, nan, nan]","[nan, 0.3642857142857143, nan]","[nan, 0.0064, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: m; [Fe/H]=-0.20; [hs/ls]=0.14; Type ...
55,NGC 2420-173,"[5.59e-06, 114.612357, 5.59e-06]","[4.19e-06, 21.558695, 4.19e-06]","[nan, 1479.0, nan]","[nan, 0.43, nan]","[0.4, 3.0, 0.3]","[nan, nan, nan]","[nan, 0.8, nan]","[nan, nan, nan]","[nan, 0.26666666666666666, nan]","[nan, 0.008, nan]",barium star,white dwarf,[RV],[2019A&A...626A.127J],Ba class: s->m; [Fe/H]=-0.26; [hs/ls]=-0.26; T...

## Finally convert and save your table to hdf5 format

In [ ]:

save_triplet_columns_and_metadata(df, triplet_cols, DATA_DIR / "result_tables/.h5")

print(f"Built {len(df)} systems and saved to barium_stars.h5")
print(df[["System Name","Period","Eccentricity","M1","M2","q","Mass Function"]].head())

Built 56 systems and saved to barium_stars.h5
   System Name              Period      Eccentricity               M1  \
0  DM -64 4333   [nan, 386.0, nan]  [nan, 0.03, nan]  [0.1, 1.4, 0.1]
1  DM -42 2048  [nan, 3260.0, nan]  [nan, 0.08, nan]  [0.5, 1.9, 0.7]
2  DM -14 2678  [nan, 3470.0, nan]  [nan, 0.22, nan]  [0.2, 3.0, 0.2]
3  DM -01 3022  [nan, 3253.0, nan]  [nan, 0.28, nan]  [0.1, 1.6, 0.1]
4      HD 5424  [nan, 1881.0, nan]  [nan, 0.23, nan]  [0.3, 1.3, 0.4]

                 M2                                q      Mass Function
0  [nan, 0.61, nan]   [nan, 0.4357142857142857, nan]  [nan, 0.068, nan]
1  [nan, 0.74, nan]   [nan, 0.3894736842105263, nan]  [nan, 0.065, nan]
2   [nan, 0.8, nan]  [nan, 0.26666666666666666, nan]  [nan, 0.023, nan]
3  [nan, 0.55, nan]              [nan, 0.34375, nan]  [nan, 0.016, nan]
4  [nan, 0.59, nan]   [nan, 0.4538461538461538, nan]  [nan, 0.005, nan]