# Extract the EL CVn's listes  


### Discoveries and Properties of EL CVn–type Binaries in the TESS Survey 
### Xiong et al. 2025


https://ui.adsabs.harvard.edu/abs/2025ApJ...979..108X/abstract

**They list the systems with their parameters in Appendix table A (raw latex shown below)**

```latex
\section{Appendix A}\label{AppendixA}
\begin{table*}[htbp]
\tiny 
\caption{Absolute parameters of 29 EL CVn-type binaries from TESS survey.}
\centering
\begin{tabular}{lccccccccccc}
\hline
\hline
  \multicolumn{1}{l}{TIC} &
  \multicolumn{1}{c}{Period (d)} &
  \multicolumn{1}{c}{$T\mathrm{_{1}}$ (K)} &
  \multicolumn{1}{c}{$T\mathrm{_{2}}$ (K)} &
  \multicolumn{1}{c}{\logg$_{1}$ [cgs]} &
  \multicolumn{1}{c}{\logg$_{2}$ [cgs]} &
    \multicolumn{1}{c}{$M\mathrm{_{1}}$ ($M_{\odot}$)} &
  \multicolumn{1}{c}{$M\mathrm{_{2}}$ ($M_{\odot}$)}&
  \multicolumn{1}{c}{$R\mathrm{_{1}}$ ($R_{\odot}$)} &
  \multicolumn{1}{c}{$R\mathrm{_{2}}$ ($R_{\odot}$)}\\
\hline
\hline
$^{1}$35399970 & 1.2908616 & 8597 $^{+ 68 }_{- 39 }$& 11378 $^{+ 83 }_{- 82 }$& 4.294 $^{+ 0.003  }_{- 0.003  }$& 4.971 $^{+ 0.005 }_{- 0.005  }$& 1.850  $^{+ 0.020  }_{- 0.020  }$& 0.193  $^{+ 0.002  }_{- 0.002  }$& 1.604  $^{+ 0.007  }_{- 0.007  }$& 0.238  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$83833793 & 2.17351686 & 7903 $^{+ 6 }_{- 49 }$& 10044 $^{+ 37 }_{- 35 }$& 3.871 $^{+ 0.004  }_{- 0.004  }$& 4.185 $^{+ 0.072  }_{- 0.072  }$& 2.050  $^{+ 0.020  }_{- 0.020  }$& 0.200  $^{+ 0.030  }_{- 0.030  }$& 2.749  $^{+ 0.016  }_{- 0.016  }$& 0.598  $^{+ 0.006  }_{- 0.006}$\\
$^{1}$121078334 & 0.92859504 & 7644 $^{+ 27 }_{- 6 }$& 10844 $^{+ 22 }_{- 22 }$& 4.143 $^{+ 0.002  }_{- 0.002  }$& 4.741 $^{+ 0.002  }_{- 0.002  }$& 1.680  $^{+ 0.020  }_{- 0.010  }$& 0.185  $^{+ 0.002  }_{- 0.002  }$& 1.818  $^{+ 0.006  }_{- 0.006  }$& 0.303  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$160081043 & 0.768701771 & 8020 $^{+ 3 }_{- 47 }$& 9985 $^{+ 30 }_{- 29 }$& 4.293 $^{+ 0.001  }_{- 0.001  }$& 4.427 $^{+ 0.001  }_{- 0.001  }$& 1.690  $^{+ 0.010  }_{- 0.010  }$& 0.196  $^{+ 0.001  }_{- 0.001  }$& 1.537  $^{+ 0.003  }_{- 0.003  }$& 0.447  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$35399970 & 1.2908616 & 8597 $^{+ 68 }_{- 39 }$& 11378 $^{+ 83 }_{- 82 }$& 4.294 $^{+ 0.003  }_{- 0.003  }$& 4.971 $^{+ 0.005 }_{- 0.005  }$& 1.850  $^{+ 0.020  }_{- 0.020  }$& 0.193  $^{+ 0.002  }_{- 0.002  }$& 1.604  $^{+ 0.007  }_{- 0.007  }$& 0.238  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$166874908 & 2.18931 & 7928 $^{+ 4 }_{- 30 }$& 11127 $^{+ 24 }_{- 22 }$&3.954 $^{+ 0.002  }_{- 0.002  }$& 4.702 $^{+ 0.010  }_{- 0.010  }$& 1.950  $^{+ 0.010  }_{- 0.010  }$& 0.197  $^{+ 0.004  }_{- 0.004  }$& 2.436  $^{+ 0.006  }_{- 0.006  }$& 0.327  $^{+ 0.002  }_{- 0.002}$\\
$^{1}$192990023 & 0.900898203 & 7198 $^{+ 8 }_{- 47 }$& 9288 $^{+ 34 }_{- 35 }$& 4.169 $^{+ 0.004  }_{- 0.004  }$& 4.633 $^{+ 0.005  }_{- 0.005  }$& 1.530  $^{+ 0.040  }_{- 0.040  }$& 0.193  $^{+ 0.005  }_{- 0.005  }$& 1.685  $^{+ 0.016  }_{- 0.016  }$& 0.350  $^{+ 0.003  }_{- 0.003}$\\
$^{1}$408351887 & 1.0731802 & 7113 $^{+ 2 }_{- 2 }$& 10263 $^{+ 4 }_{- 4 }$& 3.909 $^{+ 0.007}_{- 0.007}$& 4.633 $^{+ 0.017  }_{- 0.017  }$& 1.740  $^{+ 0.010  }_{- 0.010  }$& 0.196  $^{+ 0.005  }_{- 0.005}$& 2.425  $^{+ 0.021  }_{- 0.021  }$& 0.353  $^{+ 0.005  }_{- 0.005}$\\
$^{1}$149160359 & 1.120738 & 7827 $^{+ 22 }_{- 61 }$& 8583 $^{+ 49 }_{- 49 }$& 4.009 $^{+ 0.001  }_{- 0.001  }$& 4.306 $^{+ 0.001  }_{- 0.001  }$& 1.880  $^{+ 0.001  }_{- 0.001  }$& 0.188  $^{+ 0.001  }_{- 0.001  }$& 2.245  $^{+ 0.001  }_{- 0.001  }$& 0.505  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$416264037 & 1.15991 & 7101 $^{+ 15 }_{- 1 }$& 9649 $^{+ 13 }_{- 14 }$& 3.983 $^{+ 0.001}_{- 0.001}$& 4.517 $^{+ 0.001  }_{- 0.001  }$& 1.660  $^{+ 0.001  }_{- 0.001  }$& 0.178  $^{+ 0.001  }_{- 0.001}$& 2.175  $^{+ 0.001  }_{- 0.001  }$& 0.385  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$100011519 & 1.735248 & 7573 $^{+ 2}_{- 9 }$& 8447 $^{+ 6 }_{- 6 }$& 3.857 $^{+ 0.001  }_{- 0.001  }$& 4.183 $^{+ 0.001  }_{- 0.001  }$& 1.960  $^{+ 0.001  }_{- 0.001  }$& 0.204  $^{+ 0.001  }_{- 0.001  }$& 2.733  $^{+ 0.001  }_{- 0.001  }$& 0.606  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$219485855 & 0.660002 & 7808 $^{+ 69 }_{- 2 }$& 7903 $^{+ 52 }_{- 48 }$& 4.149 $^{+ 0.001}_{- 0.001}$& 4.217 $^{+ 0.001  }_{- 0.001}$& 1.740  $^{+ 0.001  }_{- 0.001 }$& 0.183  $^{+ 0.001  }_{- 0.001}$& 1.838  $^{+ 0.001  }_{- 0.001  }$& 0.552  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$399725538 & 1.293273 & 7761 $^{+ 66 }_{- 54 }$& 11555 $^{+ 99 }_{- 99 }$& 4.144 $^{+ 0.002  }_{- 0.002  }$& 5.131 $^{+ 0.002  }_{- 0.002  }$& 1.720  $^{+ 0.030  }_{- 0.010  }$& 0.189  $^{+ 0.002  }_{- 0.002  }$& 1.839 $^{+ 0.007  }_{- 0.007}$& 0.196  $^{+ 0.001  }_{- 0.001}$\\
$^{1}$464641792 & 1.369715 & 7499 $^{+ 1 }_{- 14 }$& 9750 $^{+ 10 }_{- 11 }$& 3.937 $^{+ 0.001}_{- 0.001}$& 4.583 $^{+ 0.001  }_{- 0.001  }$& 1.840  $^{+ 0.010  }_{- 0.010 }$& 0.184  $^{+ 0.001  }_{- 0.001}$& 2.415  $^{+ 0.005  }_{- 0.005  }$& 0.363  $^{+ 0.001  }_{- 0.001}$\\

$^{2}$54957535 & 0.792833 & 6650  $_{- 2  }^{+ 17  }$& 9371  $_{- 17  }^{+ 16  }$& 4.041 $_{- 0.002 }^{+ 0.002 }$& 4.706 $_{- 0.002 }^{+ 0.002 }$& 1.460 $_{- 0.020 }^{+ 0.020 }$& 0.171 $_{- 0.002 }^{+ 0.002 }$& 1.908 $_{- 0.009 }^{+ 0.009 }$& 0.303 $_{- 0.001 }^{+ 0.001 }$\\
$^{2}$142258314 & 0.8441541 & 8304  $_{- 37  }^{+ 84  }$& 10875  $_{- 92  }^{+ 89  }$& 4.214 $_{- 0.010 }^{+ 0.100 }$& 4.952 $_{- 0.017 }^{+ 0.017 }$& 1.830 $_{- 0.030 }^{+ 0.100 }$& 0.179 $_{- 0.007 }^{+ 0.007 }$& 1.749 $_{- 0.027 }^{+ 0.028 }$& 0.234 $_{- 0.005 }^{+ 0.005 }$\\
$^{2}$197604137 & 1.16189659 & 7044  $_{- 28  }^{+ 35  }$& 9731  $_{- 46  }^{+ 47  }$& 3.936 $_{- 0.016 }^{+ 0.014 }$& 4.846 $_{- 0.034 }^{+ 0.034 }$& 1.690 $_{- 0.020 }^{+ 0.020 }$& 0.189 $_{- 0.009 }^{+ 0.009 }$& 2.314 $_{- 0.040 }^{+ 0.040 }$& 0.272 $_{- 0.008 }^{+ 0.008 }$\\
$^{2}$400028476 & 0.64410724 & 7297  $_{- 11  }^{+ 3  }$& 9432  $_{- 9  }^{+ 9  }$& 4.145 $_{- 0.001 }^{+ 0.001 }$& 4.588 $_{- 0.001 }^{+ 0.001 }$& 1.550 $_{- 0.001 }^{+ 0.001 }$& 0.188 $_{- 0.001 }^{+ 0.001 }$& 1.744 $_{- 0.001 }^{+ 0.001 }$& 0.364 $_{- 0.001 }^{+ 0.001 }$\\
$^{2}$420947520 & 1.799427277 & 8291  $_{- 27  }^{+ 5  }$& 11597  $_{- 25  }^{+ 22  }$& 4.065 $_{- 0.006 }^{+ 0.006 }$& 5.039 $_{- 0.016 }^{+ 0.015 }$& 1.950 $_{- 0.030 }^{+ 0.030 }$& 0.189 $_{- 0.006 }^{+ 0.006 }$& 2.144 $_{- 0.018 }^{+ 0.018 }$& 0.218 $_{- 0.002 }^{+ 0.002 }$\\
$^{2}$464641792 & 1.369715 & 7499  $_{- 14  }^{+ 0  }$& 9750  $_{- 12  }^{+ 11  }$& 3.936 $_{- 0.001 }^{+ 0.001 }$& 4.583 $_{- 0.001 }^{+ 0.001 }$& 1.840 $_{- 0.010 }^{+ 0.010 }$& 0.184 $_{- 0.001 }^{+ 0.001 }$& 2.415 $_{- 0.005 }^{+ 0.005 }$& 0.363 $_{- 0.001 }^{+ 0.001 }$\\
$^{3}$28763683 & 0.892 & 8756  $_{- 1  }^{+ 5  }$& 9303  $_{- 4  }^{+ 3  }$& 3.998 $_{- 0.003 }^{+ 0.003 }$& 4.297 $_{- 0.004 }^{+ 0.004 }$& 2.210 $_{- 0.090 }^{+ 0.001 }$& 0.196 $_{- 0.005 }^{+ 0.005 }$& 2.465 $_{- 0.019 }^{+ 0.019 }$& 0.522 $_{- 0.004 }^{+ 0.004 }$\\
$^{3}$53896096 & 0.741 & 7923  $_{- 7  }^{+ 6  }$& 10578  $_{- 44  }^{+ 46  }$& 4.240 $_{- 0.025 }^{+ 0.023 }$& 5.098 $_{- 0.076 }^{+ 0.075 }$& 1.690 $_{- 0.010 }^{+ 0.020 }$& 0.171 $_{- 0.019 }^{+ 0.019 }$& 1.633 $_{- 0.043 }^{+ 0.048 }$& 0.192 $_{- 0.011 }^{+ 0.011 }$\\
$^{3}$65448527 & 0.66783 & 7843  $_{- 6  }^{+ 13  }$& 9805  $_{- 13  }^{+ 12  }$& 4.281 $_{- 0.001 }^{+ 0.001 }$& 4.566 $_{- 0.002 }^{+ 0.002 }$& 1.650 $_{- 0.020 }^{+ 0.020 }$& 0.168 $_{- 0.001 }^{+ 0.001 }$& 1.537 $_{- 0.003 }^{+ 0.003 }$& 0.354 $_{- 0.001 }^{+ 0.001 }$\\
$^{3}$165371937 & 0.79564 & 8097  $_{- 59  }^{+ 42  }$& 10598  $_{- 84  }^{+ 85  }$& 4.298 $_{- 0.004 }^{+ 0.004 }$& 4.796 $_{- 0.004 }^{+ 0.004 }$& 1.640 $_{- 0.010 }^{+ 0.080 }$& 0.188 $_{- 0.005 }^{+ 0.005 }$& 1.503 $_{- 0.015 }^{+ 0.014 }$& 0.287 $_{- 0.003 }^{+ 0.003 }$\\
$^{3}$430145146 & 0.744 & 8053  $_{- 9  }^{+ 18  }$& 10844  $_{- 21  }^{+ 21  }$& 4.222 $_{- 0.003 }^{+ 0.003 }$& 4.831 $_{- 0.005 }^{+ 0.005 }$& 1.740 $_{- 0.010 }^{+ 0.010 }$& 0.188 $_{- 0.002 }^{+ 0.002 }$& 1.691 $_{- 0.006 }^{+ 0.006 }$& 0.276 $_{- 0.001 }^{+ 0.001 }$\\
$^{3}$471013508 & 1.163 & 7470  $_{- 2  }^{+ 4  }$& 8824  $_{- 5  }^{+ 5  }$& 3.893 $_{- 0.002 }^{+ 0.002 }$& 3.627 $_{- 0.006 }^{+ 0.006 }$& 1.870 $_{- 0.010 }^{+ 0.010 }$& 0.239 $_{- 0.003 }^{+ 0.003 }$& 2.560 $_{- 0.007 }^{+ 0.007 }$& 1.245 $_{- 0.004 }^{+ 0.004 }$\\
$^{3}$85277226 & 0.977 & 7984  $_{- 37  }^{+ 25  }$& 8404  $_{- 110  }^{+ 102  }$& 4.289 $_{- 0.005 }^{+ 0.005 }$& 4.435 $_{- 0.042 }^{+ 0.040 }$& 1.680 $_{- 0.010 }^{+ 0.010 }$& 0.146 $_{- 0.013 }^{+ 0.013 }$& 1.538 $_{- 0.009 }^{+ 0.010 }$& 0.383 $_{- 0.004 }^{+ 0.004 }$\\
$^{3}$110981024 & 1.9793094 & 8398  $_{- 143  }^{+ 15  }$& 16557  $_{- 159  }^{+ 153  }$& 3.692 $_{- 0.013 }^{+ 0.013 }$& 5.037 $_{- 0.028 }^{+ 0.028 }$& 2.330 $_{- 0.090 }^{+ 0.090 }$& 0.214 $_{- 0.012 }^{+ 0.013 }$& 3.597 $_{- 0.070 }^{+ 0.071 }$& 0.232 $_{- 0.006 }^{+ 0.006 }$\\
$^{3}$177118177 & 2.5046225 & 8468  $_{- 6  }^{+ 10  }$& 14661  $_{- 15  }^{+ 15  }$& 3.916 $_{- 0.038 }^{+ 0.035 }$& 5.666 $_{- 0.093 }^{+ 0.085 }$& 2.170 $_{- 0.040 }^{+ 0.050 }$& 0.201 $_{- 0.032 }^{+ 0.032 }$& 2.685 $_{- 0.104 }^{+ 0.124 }$& 0.108 $_{- 0.006 }^{+ 0.006 }$\\
$^{3}$234874474 & 1.3159894 & 10647  $_{- 468  }^{+ 68  }$& 19846  $_{- 451  }^{+ 432  }$& 4.071 $_{- 0.006 }^{+ 0.006 }$& 5.361 $_{- 0.012 }^{+ 0.012 }$& 2.490 $_{- 0.010 }^{+ 0.02 }$& 0.228 $_{- 0.002 }^{+ 0.002 }$& 2.409 $_{- 0.017 }^{+ 0.018 }$& 0.165 $_{- 0.002 }^{+ 0.002 }$\\
$^{3}$424008045 & 1.1836627 & 7273  $_{- 3  }^{+ 2  }$& 9279  $_{- 4  }^{+ 4  }$& 3.900 $_{- 0.004 }^{+ 0.004 }$& 4.342 $_{- 0.013 }^{+ 0.013 }$& 1.800 $_{- 0.010}^{+ 0.010 }$& 0.179 $_{- 0.004 }^{+ 0.004 }$& 2.491 $_{- 0.011 }^{+ 0.012 }$& 0.473 $_{- 0.005 }^{+ 0.005 }$\\
\hline
\multicolumn{5}{l}{\footnotesize $^{1}$ previously discovered with parameters determined}\\
\multicolumn{5}{l}{\footnotesize $^{2}$ previously discovered}\\
\multicolumn{5}{l}{\footnotesize $^{3}$ new discovered}\\
\end{tabular}
\end{table*}

\end{appendices}

```

## First import the latex table into a df

In [15]:
# Lets start with some imports
import pandas as pd
import numpy as np
import re
import json
import sys
from pathlib import Path
from textwrap import dedent

# Query SIMBAD for RA/Dec coordinates (and spectral type if available)
from astroquery.simbad import Simbad
from astropy.coordinates import SkyCoord
import astropy.units as u


proj_root = Path('/Users/liekevanson/Documents/Projects/post_mt_review').resolve()
if str(proj_root) not in sys.path:
    sys.path.insert(0, str(proj_root))

# -------------------------------------------------
# Configuration
# -------------------------------------------------
from paths import RESULT_TABLES, RAW_JSON_DIR, DATA_DIR

### Read, clean and parse the LaTex table

In [21]:
def parse_latex_table(file_path):
    """
    Parse LaTeX table with asymmetric errors.
    Returns a pandas DataFrame with columns for each parameter.
    Format: value $^{+ upper}_{- lower}$ or value $_{- lower}^{+ upper}$
    """
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Extract table content between \hline\hline and final \hline
    table_match = re.search(r'\\hline\s*\\hline\s*(.*?)\s*\\hline\s*\\multicolumn', content, re.DOTALL)
    if not table_match:
        raise ValueError("Could not find table content")
    
    table_content = table_match.group(1)
    
    # Split into rows (lines ending with \\)
    rows = [line.strip() for line in table_content.split('\\\\') if line.strip()]
    
    systems = []
    
    for row in rows:
        # Skip empty rows
        if not row.strip():
            continue
            
        # Split by &
        cols = [c.strip() for c in row.split('&')]
        
        if len(cols) < 10:
            continue
        
        # Parse system name (remove superscripts like $^{1}$)
        name_raw = cols[0]
        name = re.sub(r'\$\^?\{[^}]*\}\$', '', name_raw).strip()
        
        # Skip if name is empty or non-numeric (TIC should be pure digits)
        if not name or not name.isdigit():
            continue
        
        # Parse each column with value and errors
        def parse_value_with_errors(text):
            """
            Extract value and asymmetric errors from formats like:
            - "1.850  $^{+ 0.020  }_{- 0.020  }$"
            - "8597 $^{+ 68 }_{- 39 }$"
            - "1.2908616" (no errors)
            """
            # Find the main value (first number)
            value_match = re.search(r'(-?\d+\.?\d*(?:[eE][+-]?\d+)?)', text)
            if not value_match:
                return [None, None, None]
            
            value = float(value_match.group(1))
            
            # Look for errors in format $^{+ X}_{- Y}$ or $_{- Y}^{+ X}$
            err_pattern1 = r'\$\s*\^\{?\s*\+\s*([\d.]+)\s*\}?\s*_\{?\s*-\s*([\d.]+)\s*\}?\s*\$'
            err_pattern2 = r'\$\s*_\{?\s*-\s*([\d.]+)\s*\}?\s*\^\{?\s*\+\s*([\d.]+)\s*\}?\s*\$'
            
            match1 = re.search(err_pattern1, text)
            match2 = re.search(err_pattern2, text)
            
            if match1:
                err_plus = float(match1.group(1))
                err_minus = float(match1.group(2))
            elif match2:
                err_minus = float(match2.group(1))
                err_plus = float(match2.group(2))
            else:
                # No errors found
                return [None, value, None]
            
            return [err_minus, value, err_plus]
        
        # Parse each parameter
        try:
            period = parse_value_with_errors(cols[1])
            T1 = parse_value_with_errors(cols[2])
            T2 = parse_value_with_errors(cols[3])
            logg1 = parse_value_with_errors(cols[4])
            logg2 = parse_value_with_errors(cols[5])
            M1 = parse_value_with_errors(cols[6])
            M2 = parse_value_with_errors(cols[7])
            R1 = parse_value_with_errors(cols[8])
            R2 = parse_value_with_errors(cols[9])
            
            system = {
                'TIC': name,
                'Period': period,
                'T1': T1,
                'T2': T2,
                'logg1': logg1,
                'logg2': logg2,
                'M1': M1,
                'M2': M2,
                'R1': R1,
                'R2': R2
            }
            
            systems.append(system)
            
        except Exception as e:
            print(f"Error parsing row: {row[:50]}... - {e}")
            continue
    
    # Convert to DataFrame
    df = pd.DataFrame(systems)
    print(f"Successfully parsed {len(df)} systems")
    print(f"\nFirst few systems:")
    print(df[['TIC', 'Period', 'M1', 'M2']].head())
    
    return df

In [24]:
latex_table_file = Path(DATA_DIR) / 'latex_input_data' / 'Xiong25.tex'

# Usage
df = parse_latex_table(latex_table_file)
print(f"\nSuccessfully parsed {len(systems)} systems")

Successfully parsed 30 systems

First few systems:
         TIC                     Period                  M1  \
0   83833793   [None, 2.17351686, None]  [0.02, 2.05, 0.02]
1  121078334   [None, 0.92859504, None]  [0.01, 1.68, 0.02]
2  160081043  [None, 0.768701771, None]  [0.01, 1.69, 0.01]
3   35399970    [None, 1.2908616, None]  [0.02, 1.85, 0.02]
4  166874908      [None, 2.18931, None]  [0.01, 1.95, 0.01]

                      M2
0      [0.03, 0.2, 0.03]
1  [0.002, 0.185, 0.002]
2  [0.001, 0.196, 0.001]
3  [0.002, 0.193, 0.002]
4  [0.004, 0.197, 0.004]

Successfully parsed 30 systems

# Draw the RA, DEC and some spectral type info from Simbad

In [25]:
# Configure Simbad to return decimal degrees and spectral type
simbad = Simbad()
simbad.TIMEOUT = 30
simbad.add_votable_fields('ra(d)', 'dec(d)', 'ra', 'dec', 'sp')

ra_list = []
dec_list = []
sp_list = []

for tic in df['TIC']:  # Changed from systems['TIC'] to df['TIC']
    try:
        result = simbad.query_object(f'TIC {tic}')
        if result is None or len(result) == 0:
            ra_list.append(None)
            dec_list.append(None)
            sp_list.append(None)
            print(f"TIC {tic}: Not found in SIMBAD")
            continue

        ra_deg = None
        dec_deg = None
        sp_val = None
        cols = result.colnames

        if 'ra' in cols and 'dec' in cols:
            ra_deg = float(result[0]['ra'])
            dec_deg = float(result[0]['dec'])
        else:
            coord = SkyCoord(result[0]['RA'], result[0]['DEC'], unit=(u.hourangle, u.deg))
            ra_deg = coord.ra.deg
            dec_deg = coord.dec.deg

        if 'SP_TYPE' in cols:
            sp_val = result[0]['SP_TYPE']
        elif 'sp_type' in cols:
            sp_val = result[0]['sp_type']
        elif 'SP' in cols:
            sp_val = result[0]['SP']

        if sp_val is not None and hasattr(sp_val, 'mask') and getattr(sp_val, 'mask', False):
            sp_val = None
        if sp_val is not None:
            sp_val = str(sp_val).strip() or None

        ra_list.append(ra_deg)
        dec_list.append(dec_deg)
        sp_list.append(sp_val)
        if ra_deg is not None and dec_deg is not None:
            if sp_val:
                print(f"TIC {tic}: RA={ra_deg:.6f} deg, Dec={dec_deg:.6f} deg, SpType={sp_val}")
            else:
                print(f"TIC {tic}: RA={ra_deg:.6f} deg, Dec={dec_deg:.6f} deg")
        else:
            print(f"TIC {tic}: Coordinates missing despite SIMBAD hit (columns: {cols})")
    except Exception as e:
        ra_list.append(None)
        dec_list.append(None)
        sp_list.append(None)
        print(f"TIC {tic}: Query error - {e}")

# Add RA/Dec/SpType to dataframe
df['RA'] = ra_list
df['Dec'] = dec_list
df['SpType'] = sp_list

print(f"\nAdded coordinates for {sum(1 for x in ra_list if x is not None)} systems")
print(f"Spectral types found for {sum(1 for x in sp_list if x)} systems")
display(df[['TIC', 'RA', 'Dec', 'SpType', 'Period', 'M1', 'M2']])

/var/folders/5d/vcxrsh5975l7d5n8t7vvc5pr0000gn/T/ipykernel_45747/3592799871.py:4: DeprecationWarning: 'dec(d)' has been renamed 'dec'. You'll see it appearing with its new name in the output table
  simbad.add_votable_fields('ra(d)', 'dec(d)', 'ra', 'dec', 'sp')
/var/folders/5d/vcxrsh5975l7d5n8t7vvc5pr0000gn/T/ipykernel_45747/3592799871.py:4: DeprecationWarning: 'ra(d)' has been renamed 'ra'. You'll see it appearing with its new name in the output table
  simbad.add_votable_fields('ra(d)', 'dec(d)', 'ra', 'dec', 'sp')

TIC 83833793: RA=217.465020 deg, Dec=-24.724273 deg, SpType=F0
TIC 121078334: RA=56.598694 deg, Dec=-21.972104 deg, SpType=A4IV
TIC 160081043: RA=352.053172 deg, Dec=-39.923251 deg
TIC 35399970: RA=315.371957 deg, Dec=-6.370801 deg
TIC 166874908: RA=59.659724 deg, Dec=-31.277309 deg, SpType=A3
TIC 192990023: RA=155.345141 deg, Dec=-28.694330 deg
TIC 408351887: RA=144.990610 deg, Dec=-19.328100 deg
TIC 149160359: RA=81.455091 deg, Dec=-64.989374 deg, SpType=A7V
TIC 416264037: RA=289.608635 deg, Dec=48.884104 deg, SpType=kA4hA7mA9
TIC 100011519: RA=173.003028 deg, Dec=60.112337 deg
TIC 219485855: RA=242.846723 deg, Dec=44.105816 deg, SpType=A3
TIC 399725538: RA=73.269408 deg, Dec=10.252742 deg, SpType=kA2hA7mA6
TIC 464641792: RA=287.656617 deg, Dec=-61.125651 deg
TIC 54957535: RA=130.985253 deg, Dec=-11.557658 deg
TIC 142258314: RA=131.495033 deg, Dec=53.036040 deg
TIC 197604137: RA=336.755745 deg, Dec=48.832474 deg, SpType=A5
TIC 400028476: RA=86.514983 deg, Dec=66.923496 deg
TIC 420947520: RA=273.572664 deg, Dec=48.188060 deg
TIC 464641792: RA=287.656617 deg, Dec=-61.125651 deg
TIC 28763683: RA=27.162968 deg, Dec=38.387356 deg, SpType=A1IV
TIC 53896096: RA=328.238816 deg, Dec=-24.797969 deg
TIC 65448527: RA=41.930768 deg, Dec=-25.263686 deg
TIC 165371937: RA=200.987578 deg, Dec=43.598733 deg, SpType=A1V
TIC 430145146: RA=96.338520 deg, Dec=23.204150 deg
TIC 471013508: RA=342.274875 deg, Dec=-69.567186 deg
TIC 85277226: RA=119.504062 deg, Dec=60.321206 deg
TIC 110981024: RA=291.691403 deg, Dec=25.141198 deg
TIC 177118177: RA=104.296999 deg, Dec=-66.025589 deg
TIC 234874474: RA=98.090335 deg, Dec=1.327485 deg, SpType=A1V
TIC 424008045: RA=10.167650 deg, Dec=41.422667 deg, SpType=F0

Added coordinates for 30 systems
Spectral types found for 12 systems

,TIC,RA,Dec,SpType,Period,M1,M2
0,83833793,217.465020,-24.724273,F0,"[None, 2.17351686, None]","[0.02, 2.05, 0.02]","[0.03, 0.2, 0.03]"
1,121078334,56.598694,-21.972104,A4IV,"[None, 0.92859504, None]","[0.01, 1.68, 0.02]","[0.002, 0.185, 0.002]"
2,160081043,352.053172,-39.923251,None,"[None, 0.768701771, None]","[0.01, 1.69, 0.01]","[0.001, 0.196, 0.001]"
3,35399970,315.371957,-6.370801,None,"[None, 1.2908616, None]","[0.02, 1.85, 0.02]","[0.002, 0.193, 0.002]"
4,166874908,59.659724,-31.277309,A3,"[None, 2.18931, None]","[0.01, 1.95, 0.01]","[0.004, 0.197, 0.004]"
5,192990023,155.345141,-28.694330,None,"[None, 0.900898203, None]","[0.04, 1.53, 0.04]","[0.005, 0.193, 0.005]"
6,408351887,144.990610,-19.328100,None,"[None, 1.0731802, None]","[0.01, 1.74, 0.01]","[0.005, 0.196, 0.005]"
7,149160359,81.455091,-64.989374,A7V,"[None, 1.120738, None]","[0.001, 1.88, 0.001]","[0.001, 0.188, 0.001]"
8,416264037,289.608635,48.884104,kA4hA7mA9,"[None, 1.15991, None]","[0.001, 1.66, 0.001]","[0.001, 0.178, 0.001]"
9,100011519,173.003028,60.112337,None,"[None, 1.735248, None]","[0.001, 1.96, 0.001]","[0.001, 0.204, 0.001]"
10,219485855,242.846723,44.105816,A3,"[None, 0.660002, None]","[0.001, 1.74, 0.001]","[0.001, 0.183, 0.001]"
11,399725538,73.269408,10.252742,kA2hA7mA6,"[None, 1.293273, None]","[0.01, 1.72, 0.03]","[0.002, 0.189, 0.002]"
12,464641792,287.656617,-61.125651,None,"[None, 1.369715, None]","[0.01, 1.84, 0.01]","[0.001, 0.184, 0.001]"
13,54957535,130.985253,-11.557658,None,"[None, 0.792833, None]","[0.02, 1.46, 0.02]","[0.002, 0.171, 0.002]"
14,142258314,131.495033,53.036040,None,"[None, 0.8441541, None]","[0.03, 1.83, 0.1]","[0.007, 0.179, 0.007]"
15,197604137,336.755745,48.832474,A5,"[None, 1.16189659, None]","[0.02, 1.69, 0.02]","[0.009, 0.189, 0.009]"
16,400028476,86.514983,66.923496,None,"[None, 0.64410724, None]","[0.001, 1.55, 0.001]","[0.001, 0.188, 0.001]"
17,420947520,273.572664,48.188060,None,"[None, 1.799427277, None]","[0.03, 1.95, 0.03]","[0.006, 0.189, 0.006]"
18,464641792,287.656617,-61.125651,None,"[None, 1.369715, None]","[0.01, 1.84, 0.01]","[0.001, 0.184, 0.001]"
19,28763683,27.162968,38.387356,A1IV,"[None, 0.892, None]","[0.09, 2.21, 0.001]","[0.005, 0.196, 0.005]"
20,53896096,328.238816,-24.797969,None,"[None, 0.741, None]","[0.01, 1.69, 0.02]","[0.019, 0.171, 0.019]"
21,65448527,41.930768,-25.263686,None,"[None, 0.66783, None]","[0.02, 1.65, 0.02]","[0.001, 0.168, 0.001]"
22,165371937,200.987578,43.598733,A1V,"[None, 0.79564, None]","[0.01, 1.64, 0.08]","[0.005, 0.188, 0.005]"
23,430145146,96.338520,23.204150,None,"[None, 0.744, None]","[0.01, 1.74, 0.01]","[0.002, 0.188, 0.002]"
24,471013508,342.274875,-69.567186,None,"[None, 1.163, None]","[0.01, 1.87, 0.01]","[0.003, 0.239, 0.003]"
25,85277226,119.504062,60.321206,None,"[None, 0.977, None]","[0.01, 1.68, 0.01]","[0.013, 0.146, 0.013]"
26,110981024,291.691403,25.141198,None,"[None, 1.9793094, None]","[0.09, 2.33, 0.09]","[0.012, 0.214, 0.013]"
27,177118177,104.296999,-66.025589,None,"[None, 2.5046225, None]","[0.04, 2.17, 0.05]","[0.032, 0.201, 0.032]"
28,234874474,98.090335,1.327485,A1V,"[None, 1.3159894, None]","[0.01, 2.49, 0.02]","[0.002, 0.228, 0.002]"
29,424008045,10.167650,41.422667,F0,"[None, 1.1836627, None]","[0.01, 1.8, 0.01]","[0.004, 0.179, 0.004]"

In [30]:
display(df)

,TIC,Period,T1,T2,logg1,logg2,M1,M2,R1,R2,RA,Dec,SpType
0,83833793,"[None, 2.17351686, None]","[49.0, 7903.0, 6.0]","[35.0, 10044.0, 37.0]","[0.004, 3.871, 0.004]","[0.072, 4.185, 0.072]","[0.02, 2.05, 0.02]","[0.03, 0.2, 0.03]","[0.016, 2.749, 0.016]","[0.006, 0.598, 0.006]",217.465020,-24.724273,F0
1,121078334,"[None, 0.92859504, None]","[6.0, 7644.0, 27.0]","[22.0, 10844.0, 22.0]","[0.002, 4.143, 0.002]","[0.002, 4.741, 0.002]","[0.01, 1.68, 0.02]","[0.002, 0.185, 0.002]","[0.006, 1.818, 0.006]","[0.001, 0.303, 0.001]",56.598694,-21.972104,A4IV
2,160081043,"[None, 0.768701771, None]","[47.0, 8020.0, 3.0]","[29.0, 9985.0, 30.0]","[0.001, 4.293, 0.001]","[0.001, 4.427, 0.001]","[0.01, 1.69, 0.01]","[0.001, 0.196, 0.001]","[0.003, 1.537, 0.003]","[0.001, 0.447, 0.001]",352.053172,-39.923251,None
3,35399970,"[None, 1.2908616, None]","[39.0, 8597.0, 68.0]","[82.0, 11378.0, 83.0]","[0.003, 4.294, 0.003]","[0.005, 4.971, 0.005]","[0.02, 1.85, 0.02]","[0.002, 0.193, 0.002]","[0.007, 1.604, 0.007]","[0.001, 0.238, 0.001]",315.371957,-6.370801,None
4,166874908,"[None, 2.18931, None]","[30.0, 7928.0, 4.0]","[22.0, 11127.0, 24.0]","[0.002, 3.954, 0.002]","[0.01, 4.702, 0.01]","[0.01, 1.95, 0.01]","[0.004, 0.197, 0.004]","[0.006, 2.436, 0.006]","[0.002, 0.327, 0.002]",59.659724,-31.277309,A3
5,192990023,"[None, 0.900898203, None]","[47.0, 7198.0, 8.0]","[35.0, 9288.0, 34.0]","[0.004, 4.169, 0.004]","[0.005, 4.633, 0.005]","[0.04, 1.53, 0.04]","[0.005, 0.193, 0.005]","[0.016, 1.685, 0.016]","[0.003, 0.35, 0.003]",155.345141,-28.694330,None
6,408351887,"[None, 1.0731802, None]","[2.0, 7113.0, 2.0]","[4.0, 10263.0, 4.0]","[0.007, 3.909, 0.007]","[0.017, 4.633, 0.017]","[0.01, 1.74, 0.01]","[0.005, 0.196, 0.005]","[0.021, 2.425, 0.021]","[0.005, 0.353, 0.005]",144.990610,-19.328100,None
7,149160359,"[None, 1.120738, None]","[61.0, 7827.0, 22.0]","[49.0, 8583.0, 49.0]","[0.001, 4.009, 0.001]","[0.001, 4.306, 0.001]","[0.001, 1.88, 0.001]","[0.001, 0.188, 0.001]","[0.001, 2.245, 0.001]","[0.001, 0.505, 0.001]",81.455091,-64.989374,A7V
8,416264037,"[None, 1.15991, None]","[1.0, 7101.0, 15.0]","[14.0, 9649.0, 13.0]","[0.001, 3.983, 0.001]","[0.001, 4.517, 0.001]","[0.001, 1.66, 0.001]","[0.001, 0.178, 0.001]","[0.001, 2.175, 0.001]","[0.001, 0.385, 0.001]",289.608635,48.884104,kA4hA7mA9
9,100011519,"[None, 1.735248, None]","[9.0, 7573.0, 2.0]","[6.0, 8447.0, 6.0]","[0.001, 3.857, 0.001]","[0.001, 4.183, 0.001]","[0.001, 1.96, 0.001]","[0.001, 0.204, 0.001]","[0.001, 2.733, 0.001]","[0.001, 0.606, 0.001]",173.003028,60.112337,None
10,219485855,"[None, 0.660002, None]","[2.0, 7808.0, 69.0]","[48.0, 7903.0, 52.0]","[0.001, 4.149, 0.001]","[0.001, 4.217, 0.001]","[0.001, 1.74, 0.001]","[0.001, 0.183, 0.001]","[0.001, 1.838, 0.001]","[0.001, 0.552, 0.001]",242.846723,44.105816,A3
11,399725538,"[None, 1.293273, None]","[54.0, 7761.0, 66.0]","[99.0, 11555.0, 99.0]","[0.002, 4.144, 0.002]","[0.002, 5.131, 0.002]","[0.01, 1.72, 0.03]","[0.002, 0.189, 0.002]","[0.007, 1.839, 0.007]","[0.001, 0.196, 0.001]",73.269408,10.252742,kA2hA7mA6
12,464641792,"[None, 1.369715, None]","[14.0, 7499.0, 1.0]","[11.0, 9750.0, 10.0]","[0.001, 3.937, 0.001]","[0.001, 4.583, 0.001]","[0.01, 1.84, 0.01]","[0.001, 0.184, 0.001]","[0.005, 2.415, 0.005]","[0.001, 0.363, 0.001]",287.656617,-61.125651,None
13,54957535,"[None, 0.792833, None]","[2.0, 6650.0, 17.0]","[17.0, 9371.0, 16.0]","[0.002, 4.041, 0.002]","[0.002, 4.706, 0.002]","[0.02, 1.46, 0.02]","[0.002, 0.171, 0.002]","[0.009, 1.908, 0.009]","[0.001, 0.303, 0.001]",130.985253,-11.557658,None
14,142258314,"[None, 0.8441541, None]","[37.0, 8304.0, 84.0]","[92.0, 10875.0, 89.0]","[0.01, 4.214, 0.1]","[0.017, 4.952, 0.017]","[0.03, 1.83, 0.1]","[0.007, 0.179, 0.007]","[0.027, 1.749, 0.028]","[0.005, 0.234, 0.005]",131.495033,53.036040,None
15,197604137,"[None, 1.16189659, None]","[28.0, 7044.0, 35.0]","[46.0, 9731.0, 47.0]","[0.016, 3.936, 0.014]","[0.034, 4.846, 0.034]","[0.02, 1.69, 0.02]","[0.009, 0.189, 0.009]","[0.04, 2.314, 0.04]","[0.008, 0.272, 0.008]",336.755745,48.832474,A5
16,400028476,"[None, 0.64410724, None]","[11.0, 7297.0, 3.0]","[9.0, 9432.0, 9.0]","[0.001, 4.145, 0.001]","[0.001, 4.588, 0.001]","[0.001, 1.55, 0.001]","[0.001, 0.188, 0.001]","[0.001, 1.744, 0.001]","[0.001, 0.364, 0.001]",86.514983,66.923496,None
17,420947520,"[None, 1.799427277, None]","[27.0, 8291.0, 5.0]","[25.0, 11597.0, 22.0]","[0.006, 4.065, 0.006]","[0.016, 5.039, 0.015]","[0.03, 1.95, 0.03]","[0.006, 0.189, 0.006]","[0.018, 2.144, 0.018]","[0.002, 0.218, 0.002]",273.572664,48.188060,None
18,464641792,"[None, 1.369715, None]","[14.0, 7499.0, 0.0]","[12.0, 9750.0, 11.0]","[0.001, 3.936, 0.001]","[0.001, 4.583, 0.001]","[0.01, 1.84, 0.01]","[0.001, 0.184, 0.001]","[0.005, 2.415, 0.005]","[0.001, 0.363, 0.001]",287.656617,-61.125651,None
19,28763683,"[None, 0.892, None]","[1.0, 8756.0, 5.0]","[4.0, 9303.0, 3.0]","[0.003, 3.998, 0.003]","[0.004, 4.297, 0.004]","[0.09, 2.21, 0.001]","[0.005, 0.196, 0.005]","[0.019, 2.465, 0.019]","[0.004, 0.522, 0.004]",27.162968,38.387356,A1IV
20,53896096,"[None, 0.741, None]","[7.0, 7923.0, 6.0]","[44.0, 10578.0, 46.0]","[0.025, 4.24, 0.023]","[0.076, 5.098, 0.075]","[0.01, 1.69, 0.02]","[0.019, 0.171, 0.019]","[0.043, 1.633, 0.048]","[0.011, 0.192, 0.011]",328.238816,-24.797969,None
21,65448527,"[None, 0.66783, None]","[6.0, 7843.0, 13.0]","[13.0, 9805.0, 12.0]","[0.001, 4.281, 0.001]","[0.002, 4.566, 0.002]","[0.02, 1.65, 0.02]","[0.001, 0.168, 0.001]","[0.003, 1.537, 0.003]","[0.001, 0.354, 0.001]",41.930768,-25.263686,None
22,165371937,"[None, 0.79564, None]","[59.0, 8097.0, 42.0]","[84.0, 10598.0, 85.0]","[0.004, 4.298, 0.004]","[0.004, 4.796, 0.004]","[0.01, 1.64, 0.08]","[0.005, 0.188, 0.005]","[0.015, 1.503, 0.014]","[0.003, 0.287, 0.003]",200.987578,43.598733,A1V
23,430145146,"[None, 0.744, None]","[9.0, 8053.0, 18.0]","[21.0, 10844.0, 21.0]","[0.003, 4.222, 0.003]","[0.005, 4.831, 0.005]","[0.01, 1.74, 0.01]","[0.002, 0.188, 0.002]","[0.006, 1.691, 0.006]","[0.001, 0.276, 0.001]",96.338520,23.204150,None
24,471013508,"[None, 1.163, None]","[2.0, 7470.0, 4.0]","[5.0, 8824.0, 5.0]","[0.002, 3.893, 0.002]","[0.006, 3.627, 0.006]","[0.01, 1.87, 0.01]","[0.003, 0.239, 0.003]","[0.007, 2.56, 0.007]","[0.004, 1.245, 0.004]",342.274875,-69.567186,None
25,85277226,"[None, 0.977, None]","[37.0, 7984.0, 25.0]","[110.0, 8404.0, 102.0]","[0.005, 4.289, 0.005]","[0.042, 4.435, 0.04]","[0.01, 1.68, 0.01]","[0.013, 0.146, 0.013]","[0.009, 1.538, 0.01]","[0.004, 0.383, 0.004]",119.504062,60.321206,None
26,110981024,"[None, 1.9793094, None]","[143.0, 8398.0, 15.0]","[159.0, 16557.0, 153.0]","[0.013, 3.692, 0.013]","[0.028, 5.037, 0.028]","[0.09, 2.33, 0.09]","[0.012, 0.214, 0.013]","[0.07, 3.597, 0.071]","[0.006, 0.232, 0.006]",291.691403,25.141198,None
27,177118177,"[None, 2.5046225, None]","[6.0, 8468.0, 10.0]","[15.0, 14661.0, 15.0]","[0.038, 3.916, 0.035]","[0.093, 5.666, 0.085]","[0.04, 2.17, 0.05]","[0.032, 0.201, 0.032]","[0.104, 2.685, 0.124]","[0.006, 0.108, 0.006]",104.296999,-66.025589,None
28,234874474,"[None, 1.3159894, None]","[468.0, 10647.0, 68.0]","[451.0, 19846.0, 432.0]","[0.006, 4.071, 0.006]","[0.012, 5.361, 0.012]","[0.01, 2.49, 0.02]","[0.002, 0.228, 0.002]","[0.017, 2.409, 0.018]","[0.002, 0.165, 0.002]",98.090335,1.327485,A1V
29,424008045,"[None, 1.1836627, None]","[3.0, 7273.0, 2.0]","[4.0, 9279.0, 4.0]","[0.004, 3.9, 0.004]","[0.013, 4.342, 0.013]","[0.01, 1.8, 0.01]","[0.004, 0.179, 0.004]","[0.011, 2.491, 0.012]","[0.005, 0.473, 0.005]",10.167650,41.422667,F0

# Now pour this into a json table

In [32]:
# Convert DataFrame to schema format
systems = []
for idx, row in df.iterrows():
    ra_triplet = [None, row['RA'], None] if row['RA'] is not None else [None, None, None]
    dec_triplet = [None, row['Dec'], None] if row['Dec'] is not None else [None, None, None]
    sp_type = row['SpType'] if 'SpType' in row and pd.notna(row['SpType']) and row['SpType'] else None

    system = {
        'System Name': f'TIC {row["TIC"]}',
        'RA': ra_triplet,
        'Dec': dec_triplet,
        'Period': row['Period'],
        'Eccentricity': [None, None, None],
        'M1': row['M1'],
        'M2': row['M2'],
        'Mass Function': [None, None, None],
        'evol_type_1': 'MS',
        'evol_type_2': 'WD',
        'obs_type_1': sp_type,
        'obs_type_2': 'pre-He WD',
        'system_class': 'EL CVn',
        'Detection Method': ['EB'],
        'Reference': ['2025ApJ...979..108X'],
        'Notes': f'Absolute parameters for EL CVn-type binary from Xiong et al. 2025. Additional measurements: T1={row["T1"]}, T2={row["T2"]}, logg1={row["logg1"]}, logg2={row["logg2"]}, R1={row["R1"]}, R2={row["R2"]}',
        'Simbad': f'https://simbad.cds.unistra.fr/simbad/sim-id?Ident=TIC+{int(row["TIC"])}' if row['RA'] is not None else None
    }
    systems.append(system)

output_file = Path(RESULT_TABLES) / 'raw_json' / 'Xiong2025_ELCVns.raw.json'
with open(output_file, "w") as f:
    f.write("[\n")
    for i, system in enumerate(systems):
        line = json.dumps(system, separators=(",", ": "), ensure_ascii=False)
        f.write("  " + line)
        if i < len(systems) - 1:
            f.write(",\n")
        else:
            f.write("\n")
    f.write("]\n")

print(f"Saved {len(systems)} EL CVn systems to {output_file}")
print("\nFirst system example:")
print(json.dumps(systems[0], indent=2))

Saved 30 EL CVn systems to /Users/liekevanson/Documents/Projects/post_mt_review/data/result_tables/raw_json/Xiong2025_ELCVns.raw.json

First system example:
{
  "System Name": "TIC 83833793",
  "RA": [
    null,
    217.46501989274,
    null
  ],
  "Dec": [
    null,
    -24.7242731219,
    null
  ],
  "Period": [
    null,
    2.17351686,
    null
  ],
  "Eccentricity": [
    null,
    null,
    null
  ],
  "M1": [
    0.02,
    2.05,
    0.02
  ],
  "M2": [
    0.03,
    0.2,
    0.03
  ],
  "Mass Function": [
    null,
    null,
    null
  ],
  "evol_type_1": "MS",
  "evol_type_2": "WD",
  "obs_type_1": "F0",
  "obs_type_2": "pre-He WD",
  "system_class": "EL CVn",
  "Detection Method": [
    "EB"
  ],
  "Reference": [
    "2025ApJ...979..108X"
  ],
  "Notes": "Absolute parameters for EL CVn-type binary from Xiong et al. 2025. Additional measurements: T1=[49.0, 7903.0, 6.0], T2=[35.0, 10044.0, 37.0], logg1=[0.004, 3.871, 0.004], logg2=[0.072, 4.185, 0.072], R1=[0.016, 2.749, 0.016], R2=[0.006, 0.598, 0.006]",
  "Simbad": "https://simbad.cds.unistra.fr/simbad/sim-id?Ident=TIC+83833793"
}

# OLD

In [ ]:
table_file = Path(DATA_DIR) / 'latex_input_data' / 'Xiong25.tex'

with open(table_file, 'r') as f:
    latex = f.read()

# Extract only data lines (skip \hline, captions, etc.)
lines = [
    ln for ln in latex.splitlines()
    if '&' in ln and r'\hline' not in ln and r'\contcaption' not in ln
]

# def parse_line(line):
#     parts = [p.strip().strip('$ ') for p in line.split('&')]
#     name_raw = parts[0].replace(r'^\mathrm{RV}', '^RV')
#     name = re.sub(r'\\\^\{\s*\\mathrm\{RV\}\s*\}', '^RV', name_raw)
#     name = re.sub(r'[{}\\$]', '', name).strip()
#     nums = [float(re.sub(r'[^\d\.\-eE]', '', p)) for p in parts[1:]]
#     return name, nums
def parse_line(line):
    parts = [p.strip() for p in line.split('&')]
    name_raw = parts[0].strip()
    
    # Clean up system name
    name = re.sub(r'\$\^\{[^}]*\}\$', '', name_raw)
    name = re.sub(r'[{}\\$]', '', name).strip()
    
    # Extract numbers using regex that finds actual numbers
    nums = []
    for p in parts[1:]:
        match = re.search(r'-?\d+\.?\d*(?:[eE][+-]?\d+)?', p)
        if match:
            nums.append(float(match.group()))
        else:
            nums.append(None)
    
    return name, nums
    
records = []
for val_line, err_line in zip(lines[0::2], lines[1::2]):  # pair value/err rows
    name, vals = parse_line(val_line)
    _, errs = parse_line(err_line)
    records.append((name, vals, errs))

cols = [
    "P_d", "i_deg", "M1_Msun", "M2_Msun",
    "R1_Rsun", "R2_Rsun", "T1_K", "T2_K",
    "logg1", "logg2"
]
df = pd.DataFrame([
    {"name": name, **{c: v for c, v in zip(cols, vals)},
     **{f"{c}_err": e for c, e in zip(cols, errs)}}
    for name, vals, errs in records
])

df.head()

,name,P_d,P_d_err,i_deg_err,M1_Msun_err,M2_Msun_err,R1_Rsun_err,R2_Rsun_err,T1_K_err,T2_K_err,logg1_err,i_deg,M1_Msun,M2_Msun,R1_Rsun,R2_Rsun,T1_K,T2_K,logg1
0,multicolumn1lTIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,multicolumn1cTmathrm_1 (K),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,multicolumn1clogg_1 [cgs],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,multicolumn1cMmathrm_1 (M_odot),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,multicolumn1cRmathrm_1 (R_odot),NaN,1.290862,8597.0,11378.0,4.294,4.971,1.85,0.193,1.604,0.238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Set

Columns: ['main_id', 'ra', 'dec', 'coo_err_maj', 'coo_err_min', 'coo_err_angle', 'coo_wavelength', 'coo_bibcode', 'matched_id']
Row 0:     main_id             ra              dec       coo_err_maj coo_err_min coo_err_angle coo_wavelength     coo_bibcode      matched_id
                       deg              deg           mas         mas          deg
--------------- ------------------ -------------- ----------- ----------- ------------- -------------- ------------------- ------------
TYC 5204-1575-1 315.37195674043994 -6.37080081665       0.029      0.0171            90              O 2020yCat.1350....0G TIC 35399970